### ISSUE TITLE
Postgres Type Provider can't resolve columns

### ISSUE THREAD

**Issue by trondd** [fsprojects/SQLProvider#104]
Hi. I am not sure if the title is entirely correct, but it describes the problem I am seeing. I am doing a little experiment with the Postgres type provider on a small test database running locally on my machine, but somehow the columns does not resolve. The database connection is working because the table names does auto-complete, but if I try to access a column in a record like this

        let b = query { for record in cnx.``[public].[myTable]`` do
                        select record.myField
                } |> Seq.toList

I get the following error:

````
****/Test.fs(34,34): Error FS3021: Unexpected exception from provided type 'FSharp.Data.Sql.SqlDataProvider,ConnectionString="Server=localhost;Port=5432;Database=****;user=****;",DatabaseVendor="2",ResolutionPath="****/packages/Npgsql.2.2.2/lib/net35"+dataContext+[public].[type]Entity' member 'GetMethods': The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: The given key was not present in the dictionary. (FS3021) (Foobar)
````

Any ideas?

* FSharp.Data.TypeProviders 4.3.0.0
* SQLProvider 0.0.9-alpha from NuGet
* Mono 3.10.0 ((detached/e204655)

**Comment by trondd** [comment]
Hi. I haven't tested this with .NET 4.5, only 4.0.

**Comment by colinbull** [comment]
I believe this is fixed now on development V1. See https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.Postgresql.fs#L129 

Closing for now..
