### ISSUE TITLE
Does this library create erased or generative types?

### ISSUE THREAD

**Issue by DamianReeves** [fsprojects/SQLProvider#107]
I may be missing where this is documented, but I can't seem to find any indication whether this library produces erased or generative types.

I'm looking for an F# data access library that works nicely from C# code FSharp.Data.SqlClient is erased types (except for the enum provider), what kind of types does this library provide?

**Comment by pezipink** [comment]
this is an erasing type provider.

**Comment by DamianReeves** [comment]
Thanks

**Comment by DamianReeves** [comment]
This should probably be noted in the documentation.
