### ISSUE TITLE
[Question] How to handle mutiple run time assigned connection strings

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/SQLProvider#109]
I really like the idea of using type providers for data access, but I struggle to see how to solve connecting to different databases (with same schema) when you don't know connection string until runtime.

I assume this is a case of major ignorance on my side so I'm hoping someone at least would be as kind as to point to the right place to start studying.

**Comment by pezipink** [comment]
You will notice that the GetDataContext() method has an overload that accepts a connection string.  This is the runtime connection string, should it be different to the static parameter.   You can have as many different runtime contexts as you want.  Of course, this assumes the runtime database schemas are the same as the one that was used to generate the type information and compile-time. 

Our documentation is somewhat lacking, it is known! (I must address that soon...) 

You can see this stuff working in my blog post here though http://pinksquirrellabs.com/post/2014/05/18/CRUD-Operations-and-Experimental-ODBC-support-in-the-SQLProvider.aspx

**Comment by Vidarls** [comment]
Thanks for replying.

DataContexts solves that problem it seems. But:

How do you handle the build time requirement for the connection string? It might be different on CI server and dev machine.

**Comment by pezipink** [comment]
Yes,  that is going to be a problem if you need more than one compile time connection string.  There is really no nice way around it, we need some compile time function evaluation like D can do!

The only other immediate, hacky solution I can think of is to pass multiple delimited connection strings and for it to try each one to see if it can connect.  Yuck.

**Comment by pezipink** [comment]
You should also be able to use 

#IF CI ,,
  [<Literal>]let connection = @""

if you are able to parameterize the CI build to define a symbol.

**Comment by Vidarls** [comment]
How is this issue handled in something like the entity fw provider?

**Comment by pezipink** [comment]
by the way, you can use my new mixin type provider to address this issue now.  https://github.com/pezipink/MixinProvider

**Comment by colinbull** [comment]
Bit late to the party here, but the TP also supports a 'ConnectionStringName' static parameter to point to a connection string in the app/web config file. You can then use config replacements for DEV and CI environments to swap out the connection string.

**Comment by Thorium** [comment]
Initial question has been answered in the documentation so I'll close this.
