### ISSUE TITLE
executeQueryScalar and Oracle

### ISSUE THREAD

**Issue by KristianSchmidt** [fsprojects/SQLProvider#111]
Hello

Doing a count on a table when using an Oracle DB results in an exception:
"Count returned something other than a 32 bit integer : System.Decimal "

The Oracle db library does this on purpose (see http://stackoverflow.com/questions/8539072/why-does-oledb-executescalar-method-return-decimal-when-querying-for-count ), so the issue is that the casting code in executeQueryScalar doesn't support converting a decimal to an int.

**Comment by pezipink** [comment]
So is this "decimal" only actually an integer? if so we can just cast it.  At the moment the code expects Int16, Int32 or Int64 (reasonably!)  We then have to possibly truncate it it a 32bit integer anyway because that is all LINQ supports.

**Comment by colinbull** [comment]
Yep... this is why I love oracle...

**Comment by Thorium** [comment]
I had to change this a bit as scalar can be sum or min or max or average with #264

**Comment by Thorium** [comment]
Can some Oracle user test this?

**Comment by colinbull** [comment]
I'm back in the oracle world, so I can test this on Monday..

**Comment by Thorium** [comment]
I'll close this for now. Please reopen if it is an issue still.
