### ISSUE TITLE
Can not get data from MS Access

### ISSUE THREAD

**Issue by demas** [fsprojects/SQLProvider#118]
This code works fine:

    let result = 
        query {
            for it in db.``[db].[Items]`` do
            where (it.Id <> "something")
            select it
        } |> Seq.toList

But if I comment where-clause:

    let result = 
        query {
            for it in db.``[db].[Items]`` do
            // where (it.Id <> "something")
            select it
        } |> Seq.toList

I get exception `System.ArgumentException : The input sequence was empty.`

Here is a connection string: `type dbSchema = SqlDataProvider< @"Provider=Microsoft.ACE.OLEDB.12.0; Data Source= C:\\\\Sources\\Experiments\\DbAccess\db.accdb", Common.DatabaseProviderTypes.MSACCESS>`

**Comment by bennylynch** [comment]
Hi Dimas -
I've fixed a few problems with MSAccessProvider (couldn't even get it to run, initially). Having done so, I cannot reproduce this problem, using an ACCDB I have locally, using the ACE.OLEDB provider. Could you provide some details of the 'db.accdb' you were using?

**Comment by demas** [comment]
Hmm...  Sorry, I can not reproduce the problem with last version too

**Comment by bennylynch** [comment]
Splendid.
