### ISSUE TITLE
Generated types should hold provider specific data types for columns

### ISSUE THREAD

**Issue by janno-p** [fsprojects/SQLProvider#123]
While trying to improve PostgreSQL type handling, I created some tests for trying out various type combinations and aliases available in PostgreSQL. But it doesn't work at all, since generated types don't hold provider specific type information and at runtime type detection isn't enough (since multiple provider types can map to single clr type).

For example, in postgre I have 4 types I could map to DateTime (time, timestamp: both with or without timezone info). They all should map to System.DateTime, but at the runtime the System.DateTime type picks always same provider type (currently NpgsqlDbType.Time, since it's first in the mappings). It's possible to change order of mappings as in PR#117, but it is not suitable for all types (like string, which can be various other types in addition to text).

It seems that SqlEntity should hold the provider specific type enum value in addition to data, because then it's more certain, the value gets correct type in query-s.

But this probably means that more code that is currently general, should be moved to provider specific implementation, so it's probably reasonable to implement when specialized type providers (PR#85) gets finished and approved.

This is probably not postgresql specific problem, but more general issue?

**Comment by janno-p** [comment]
Now that I come to think of it, I would be better of with using certain wrapper clr types for specific provider types. I will try out that approach first.

**Comment by pezipink** [comment]
How does Npgsql deal with this issue?  Presumably it does a similar thing where it "remembers" something that is now a CLR DateTime should actually be a NpgsqlDbType.Time, or is the user expected to manage this?

**Comment by janno-p** [comment]
Npgsql has internal mapping for various clr types (actually it seems they're making some changes in type system, future versions seem to implement typehandlers for all possible NpgsqlDbType enumeration values). But those mappings are overlapping for some enumeration values and system types.

Npgsql could probably handle types well most of the time, but current implementation might have some issues. If I remember correctly, then one issue is with `PostgreSQL.createCommandParameter` function. It first sets the value of the parameter and after that assigns `DbType` enumeration value. But in case of `ProcessUpdates` call, the type info is usually not given and defaults to String type. It's possible that most types handle it well, but I'll have to check (I don't remember what types exactly caused problems for me, if they're Npgsql specific geometric types, then it's not that much of a problem).

To recover I tryed some workarounds. One thing that works for `ProcessUpdates`, is to look up column info cached in provider and pass the mapping to parameter creation. That way the provider uses always same type it got from database (presuming the mappings are correct :)).

I was concerned, that this approach won't work for compiled assemblies. But tests proved, that they work. I was suprised to discover, that even after compilation type provider is doing schema discovery querys to database. Which brings me to next possible issue:

It seems that `ISqlProvider` and `ISqlDataContext` are too interrelated. To me it would seem more natural and practical when `ISqlProvider` handles design time operations (discovering schema, procedures, tables, and individuals) and `ISqlDataContext` handles CRUD at runtime. That would be possible thing to benefit if type enumeration is held with data, because then it wouldn't be necessary to do design time operations at runtime after compilation.

These are my thoughts at the moment, it's possible that I don't comprehend type providers at required level, so excuse me if the suggestions don't make any sense :) I'm experimenting with these ideas as we speak.

**Comment by pezipink** [comment]
Yeah, the overall design is largely that, but some of the crossover is unavoidable.

The biggest problem is that the data collected at compile-time is not easily translated across to the runtime times, as the quotations are limited to closing on value types only, which means you end up stuck with strings-and-reflection which is obviously both slow and ugly. 

I will think on this though, I wonder if my new type provider might be able to help out with this as well.

**Comment by janno-p** [comment]
This should be fixed now. Column info is passed along with SqlEntity which allows to look up expected NpgsqlDbType of each column before inserts or updates into database. Added thorough tests for each individual type and it seems that current solution at least allows to use most of the types without errors.
