### ISSUE TITLE
Double precision in Postgres does not work anymore

### ISSUE THREAD

**Issue by boeremak** [fsprojects/SQLProvider#125]
When using float8 in Postgresql it gets converted into "Double precision" database type. This does not get properly converted by the type provider.

I've added the following line into the Postgres provider and recompiled:

yield { ProviderTypeName = Some "double precision"; ClrType = (typeof<double>).ToString(); DbType = DbType.Double; ProviderType = Some 22; }

This does seem to work. As "double precision" seems to be just a different name for float8 I can't really say if this breaks anything.

If you could look into it I would be much obliged.

**Comment by pezipink** [comment]
@janno-p any thoughts on this? I know little to nothing about postgres !

**Comment by janno-p** [comment]
I'm familiar with the issue. I'll put together some fixes for postgres types what I've discovered so far. There are some additional types with same issue, and at the same time some mappings are not needed.

**Comment by boeremak** [comment]
Are we constrained by the types that Ado.Net provides? There are some more types that would be useful in the provider that Postgres provides.

**Comment by pezipink** [comment]
Yes, this a purely ADO.NET based system, we are constrained by whatever the chosen ADO.NET provider - in this case ngpsql - is able to give us.

**Comment by boeremak** [comment]
Ok, makes sense. Thanks
