### ISSUE TITLE
Create release.cmd

### ISSUE THREAD

**Issue by forki** [fsprojects/SQLProvider#13]
I assume you don't want to upload the nuget packages manually.
Here is what I do:

* Create a release.cmd file in the project root

    @echo off
    cls
    if not exist packages\FAKE\tools\Fake.exe (
      .nuget\nuget.exe install FAKE -OutputDirectory packages -ExcludeVersion -Prerelease
    )
    packages\FAKE\tools\FAKE.exe build.fsx Release "NugetKey=MYNUGETKEY"
    pause

* Replace MYNUGETKEY with your nuget key.
* Make sure the file is in .gitignore

With this helper you only have to modify the RELEASE_NOTES.md file.

/cc @pblasucci - maybe we find a way to put this into the scaffolding.

**Comment by Thorium** [comment]
I think this can be closed..?

**Comment by forki** [comment]
Was a reminder for @pezipink - it's now documented in http://fsprojects.github.io/ProjectScaffold/release-process.html
