### ISSUE TITLE
System.Data.SQLite.dll Operation is not supported Exception from HRESULT: 0x80131515

### ISSUE THREAD

**Issue by Ciantic** [fsprojects/SQLProvider#134]
I'm trying this on VS CTP 6, downloaded a bunch of DLL's from http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki and threw them in the bin directory of my project.

**Edit** I'm trying with 4.5.1 32-bit DLLs. Also tried with 4.5.1 64 bit (gives different error, something about format being wrong).

**Edit** Tried with Nuget package DLL's, same problem.

I'm getting this error.

```
The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not load file or assembly 'file:///C:\Projects\dotNET\FsharpUiNextSinglePageApp2\FsharpUiNextSinglePageApp2\bin\System.Data.SQLite.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)	FsharpUiNextSinglePageApp2	C:\Projects\dotNET\FsharpUiNextSinglePageApp2\FsharpUiNextSinglePageApp2\Client.fs	13
```

Error is coming from here:

```
type sql = SqlDataProvider< 
            ConnectionString = @"Data Source=C:\Projects\dotNET\FsharpUiNextSinglePageApp2\FsharpUiNextSinglePageApp2\test.db ;Version=3",
            DatabaseVendor = Common.DatabaseProviderTypes.SQLITE,
            ResolutionPath = @"C:\Projects\dotNET\FsharpUiNextSinglePageApp2\FsharpUiNextSinglePageApp2\bin\",
            IndividualsAmount = 1000,
            UseOptionTypes = true >
```

**Comment by boeremak** [comment]
Could you try and remove the trailing slash in the resolutionpath?

Like this:

    ResolutionPath = @"C:\Projects\dotNET\FsharpUiNextSinglePageApp2\FsharpUiNextSinglePageApp2\bin",

**Comment by Ciantic** [comment]
@boeremak didn't help unfortunately.

Tried also to see if the DLL is blocked or read-only, it isn't. (Googling that HRESULT found similar fixes for other people)

**Comment by colinbull** [comment]
Can you try putting the test.db in the bin path? 

I had lots of problems getting the test to work properly with `Sqlite`. You can see my solution on my fork https://github.com/colinbull/SqlProvider/blob/feat_nicer_naming/tests/SqlProvider.Tests/CrudTests.fs let me know if this helps.

**Comment by Ciantic** [comment]
I think this was fixed by rebooting the computer. I suspect it had something to do with DLL, not the database.

**Comment by pezipink** [comment]
lol.  Switch it off and on again!
