### ISSUE TITLE
Automatically creating Records from queries?

### ISSUE THREAD

**Issue by Ciantic** [fsprojects/SQLProvider#139]
I watched this: https://skillsmatter.com/skillscasts/6159-meta-programming-madness-with-the-mixin-type-provider and read this: http://www.pinksquirrellabs.com/post/2015/03/01/Introducing-The-Mixin-Type-Provider.aspx (**Edit** I must add, what an energy! It comes thru in the video especially)

If number one question is how can we get Record types out of SQLProvider is now solved with mixin type providers, can we expect to see it somehow supported by this module?

I think if I've understood this correctly, [example such as here](https://jamessdixon.wordpress.com/2015/01/20/f-record-types-with-sqlprovider-code-last/):

```
let GetPet(id: int)=
    query {for p in context.``[dbo].[Pet]`` do
           where (p.Id = id)
           select {Id=p.Id; ChildId=p.ChildId; GivenName=p.GivenName}}
    |> Seq.head
```

Gets even simpler and the select repetition is not required because it can automatically create records.

**Comment by pezipink** [comment]
The short answer is no, the two type providers are very different beasts so I don't think you can expect to see an "official" symbiosis of the two projects.  Infact I have one really crazy version that is an erasing-mixin sql type provider that can provide record types directly in the same TP !  It is very flaky though and would probably never be suitable for general use, lol.

In the example you showed though you would still need the query, it directly instantiates the record which has been previously declared, it would just mean you don't have to manually define the record type.

One other thing with records is it would complicate the change-tracking and create/update work (well, that simply would not work at all as it stands).

Ps, thanks for the comment on the talk, always nice to hear people have watched and enjoyed them
