### ISSUE TITLE
MySQL: Database table name case is different with Mono and Windows.

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#140]
I'm using SQLProvider from the NuGet-package (restored by Paket). The database is MySQL/MariaDB. I have two development environmets, Mono and Windows. Everything else works correctly, F#, Paket, SQLProvider, OWIN, etc, but: SQLProvider generates all the table names in lower case in Windows.

So I have to have differents source codes for each table query:

        #if MONO
            query {
                for c in context.``[mydb].[TableName]`` do
                select (d.Id, c.Name)
            }
        #else
            query {
                for c in context.``[mydb].[tablename]`` do
                select (d.Id, c.Name)
            }
        #endif
             |> Seq.toArray

This feels stupid.

- Is this just the Nuget-version issue, or also the GitHub-version?
- Can I help with the new version? 
- What would be minimum requirements to be fixed that the current NuGet-package could be updated?

**Comment by colinbull** [comment]
This is indeed stupid, although the table names are generated from the schema, which in turn is generated from the provider. So I think this is down to differences between the mono / windows MySQL provider implementations. 

If your feeling brave, you could try my branch https://github.com/colinbull/SqlProvider/tree/feat_nicer_naming which gives proper camel cased names and gives an intermediate type that represents the schema so you should end up with `ctx.MyDb.TableName`. I'd be interested to see the results.

**Comment by Thorium** [comment]
I did try that... Here are my findings:

1. Basically: MySQL/MariaDB in Windows works. MS-SQL in Windows works. MySQL/MariaDB works also in Mac/Mono. I didn't try others.

2. Everything is in upper case... (as stated in #94 )  Good thing is that now it's consistent! Bad thing is that I losed the CamelCase table names. Also it is a breaking change, but... This is already better than what is now available in the NuGet.

3. If you don't give an owner-property to MySQL (as you can leave it out), there is no tables at all. 
  The problem is that by default the query will be like this:

      select TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = '';

  And this will hit to zero rows as the table columns are:
| TABLE_SCHEMA    | TABLE_NAME               | TABLE_TYPE   |
|--------------------------------------------------------------------------------------|
| myDatabase             | MyDataTable1               | BASE TABLE    |
| myDatabase             | MyDataTable2               | BASE TABLE    |
| mysql                        | SomeSystemTables      | BASE TABLE    |
| information_schema | ALL_PLUGINS              | SYSTEM VIEW |
| information_schema | APPLICABLE_ROLES  | SYSTEM VIEW |

...so there would be multiple solutions to this, ``if String.IsNullOrEmpty MySql.owner then``:
   - Remove ``where TABLE_SCHEMA = ''`` from the query and fetch all the tables from the server. Assuming that the connection string user would have not been granted rights to all tables and also system tables. 
   - Or just say: ``MySql.owner <- con.Database`` I think this would be safer.

And some more minor things:

1. If you want to run scripts both in Win and Mono, the ``#r @"..\..\path\my.dll"`` should be changed to have different slashes and both ``#I @"../../path"`` and ``#r @"../../path/my.dll"``

2. Tests have hard coded references like ``@"D:\Appdev\SqlProvider\tests\SqlProvider.Tests"``
  Better solution would be using e.g. Paket to fetch these dlls and then use just:
  ``__SOURCE_DIRECTORY__ + @"/../../packages/MySql.Data/lib/net45/"``
   - My build.cmd in Windows fails in test run, probably just due to these paths...

3. If you run ``.paket\paket install``, it will update OctoKit hashcode to point a different version from GitHub...a version that breaks this build.

So quite small changes...should I do a PR?

**Comment by colinbull** [comment]
Awesome, investigation. A PR would be superb, especially around the changes you suggest to MySQL as I don't think me or @pezipink have had massive exposure to this DB. 

However with regard to the UPPER CASING of the table names. This shouldn't be the case, mainly due to this [module](https://github.com/colinbull/SqlProvider/blob/feat_nicer_naming/src/SQLProvider/Utils.fs#L67) in the `feat_nicer_naming` branch of my fork, if this is not working I'd like to investigate furthur. The upper case behaviour is what is currently on the master branch. 

In general thou, naming, paths, mono support, DB support, stability, tests; in fact any help at all to get this to at least v1.0 would also be massively appreciated :+1: as recently I only have limited access to environments I can test against and limited time and I pretty sure it is the same for @pezipink

**Comment by Thorium** [comment]
Yeah, right, thanks. Now I did run feat_nicer_naming and it seemd to be ok!
To reply my earlier post:

1. Also this branch seems to also work with MySQL and MS-SQL
2. Wow, the feature naming is way better I thought!
3. Added PR: In MySQL, if owner not defined, then owner = database name

And minor ones:

1. Fixed to MySQL test scripts, included in the PR
2. Fixed, included in the PR
3. This can still be a problem.
4. I think this is ok in this branch.

One note:
Seems like you can't do complex query join with the context object directly, you have to capture the database to the temp object first:

    let hr = ctx.Hr
    query {
            for emp in hr.Employees do
            for manager in emp.employees_ibfk_3 do
            join dept in hr.Departments on (emp.DepartmentId = dept.DepartmentId)
            where ((dept.DepartmentName |=| [|"Sales";"Executive"|]) && emp.FirstName =% "David")
            select (emp.FirstName, emp.LastName, manager.FirstName, manager.LastName )
    } |> Seq.toList

This shouldn't be a problem as ``let hr = ctx.Hr`` won't do a database execution by itself, right?

**Comment by Thorium** [comment]
@colinbull There seems to be some issue with mono:

        type Employee = {
            EmployeeId : int32
            FirstName : string
            LastName : string
            HireDate : DateTime
        }

        //***************** Individuals ***********************//
        let indv = ctx.Hr.Employees.Individuals.``As FirstName``.``100, Steven``

This gives error:
 /SqlProvider/tests/SqlProvider.Tests/scripts/MySqlTests.fsx(29,20): error FS3021: Unexpected exception from provided type 'FSharp.Data.Sql.SqlDataProvider,DatabaseVendor="3",ConnectionString="Server=localhost;Database=HR;Uid=admin;Pwd=password;",ResolutionPath="/Users/tuomashietanen/Documents/SqlProvider/tests/SqlProvider.Tests/scripts/../../../packages/MySql.Data/lib/net40/",Owner="HR"+dataContext+hr.EMPLOYEESEntity' member 'GetMethods': The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: The given key was not present in the dictionary.

The Individuals do exist and they are shaped:

    val it : SqlDataProvider<...>.dataContext.hr.EMPLOYEESEntity =
    FSharp.Data.Sql.Common.SqlEntity
    {ColumnValues = seq
                      [("EMPLOYEE_ID", 100); ("FIRST_NAME", "Steven");
                       ("LAST_NAME", "King"); ("EMAIL", "SKING"); ...];
     DataContext = FSharp.Data.Sql.Runtime.SqlDataContext;
     Table = {Schema = "hr";
              Name = "EMPLOYEES";
              Type = "";};
     _State = Unchanged;}

So: 
        ctx.Hr.Employees.Individuals.``100``

and there is no ``As FirstName``. Also the call:

    query {
        for emp in ctx.Hr.Employees do
        select (emp.FirstName, emp.LastName)
    } |> Seq.toList

fails with:

     /SqlProvider/tests/SqlProvider.Tests/scripts/MySqlTests.fsx(39,17): error FS0193: Type constraint mismatch. The type 
    SqlDataProvider<...>.dataContext.hr.EMPLOYEESEntity    
    is not compatible with type
    Employee     
    The type 'SqlDataProvider<...>.dataContext.hr.EMPLOYEESEntity' is not compatible with the type 'Employee'

**Comment by Thorium** [comment]
I solved my case by renaming all the data tables (but not columns) to lower case.

**Comment by colinbull** [comment]
Cool, promise ill get round to creating a release with all the fixes on a new branch soon. Time is my enemy at the minute. @pezipink any time from you? 

-----Original Message-----

**Comment by pezipink** [comment]
Yes, sorry for being terrible, I am back on some F# stuff now out of hours so hopefully I can get this sorted out soon
