### ISSUE TITLE
Update is not commiting the changes. (MySQL, current NuGet package version)

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#142]
It seems that the CRUD operations work well, except Update which won't give any error, but won't actually commit the changes: when I say SubmitUpdates to the context and then fetch the data again, there are the original values.

I assume that these unit tests should have asserts also to check that the value in the database has actually changed:

    antartica.REGION_NAME <- "ant"
    ctx.SubmitUpdates()
    
    antartica.Delete()
    ctx.SubmitUpdates()

**Comment by pezipink** [comment]
this seems very odd, is it sql server? I have stuff in production that uses the update stuff.  I will have a look this week.

**Comment by pezipink** [comment]
oh, MySql, did not read the subject.  Ok, cool, I will try to have a look, I don't really have access to a MySql db at the moment.

**Comment by Thorium** [comment]
Actually I used the [MariaDB](https://downloads.mariadb.org/mariadb/10.0.20/) which is the free version of the MySQL, but it is the same... 
`mysql -u root -p`

    CREATE USER 'admin'@'localhost' IDENTIFIED BY 'password';
    CREATE DATABASE HR;
    GRANT ALL ON HR.* TO 'admin'@'localhost';
    FLUSH PRIVILEGES;

and then `mysql -u root -p HR -e "myscript.sql"`

**Comment by Thorium** [comment]
Still have to verify but it seems that this is problem with the NuGet-version but not with the current Github-version.

**Comment by Thorium** [comment]
Ok the problem was that entity modifications were not added to pendingChanges as I was just calling `e.SetData(myData)` and when I replaced it with `myData |> Seq.iter(fun (k,o) -> e.SetColumn(k, o)))` everything started to work.

SQLProvider is using "silent update" for SetData:

		type SqlEntity(...) = 
			member e.SetColumnSilent(key,value) =
				data.[key] <- value                
		
			member e.SetColumn<'t>(key,value : 't) =        
				data.[key] <- value
				e.UpdateField key        
				e.TriggerPropertyChange key
			
			member e.SetData(data) = data |> Seq.iter e.SetColumnSilent  
		
		type public SqlDataContext (...) =
		interface ISqlDataContext with
			member this.SubmitChangedEntity e = pendingChanges.Add e |> ignore

**Comment by pezipink** [comment]
This is by design, `SetData` is not really supposed to be called from the client except in advanced scenarios.  It is there mainly so the entity can maintain data, for example - setting the primary key after an update without triggering another update. 

In your original example you were using the <- assignment operator, this should be calling SetColumn, are you saying this is not the case?

**Comment by Thorium** [comment]
Yes. My code is this and now it's working correctly:
https://github.com/Thorium/WebsitePlayground/blob/master/backend/SignalRHubs.fs (line 101)
:-)
