### ISSUE TITLE
Update fails with Option type

### ISSUE THREAD

**Issue by mathias-brandewinder** [fsprojects/SQLProvider#144]
Working with LocalDB. UseOptionTypes=true works just fine for the querying part, but when I try to update a field that is optional, I get the following error:

```The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error in the context of provided type 'FSharp.Data.Sql.SqlDataProvider,ConnectionString="Data Source=(LocalDB)\\v11.0;AttachDbFilename=blah.mdf\";Integrated Security=True",UseOptionTypes="True"+dataContext+[dbo].[RouteOptTrips]Entity', member 'set_rotPickupETA'. The error: GenericArguments[0], 'System.Int32', on 'Void SetColumnOption[a](System.String, Microsoft.FSharp.Core.FSharpOption`1[a])' violates the constraint of type 'a'.```

I am getting this doing both
```
target.rotPickupETA <- 123
target.rotPickupETA <- Some(123)
```
I have a workaround (I ended up using a context without option types for the writes), but was wondering if I was doing something wrong, or if this was a limitation / bug. Cheers!

**Comment by pezipink** [comment]
I am pretty sure this is fixed now if you try from master, we will be releasing a new package in the near future (finally!)
