### ISSUE TITLE
Using connection string from configuration file

### ISSUE THREAD

**Issue by mathias-brandewinder** [fsprojects/SQLProvider#145]
The API docs seem to hint that it is possible to use a connection string from a config file:
http://fsprojects.github.io/SQLProvider/reference/fsharp-data-sql-sqldataprovider.html
However, I can't figure out how to make that work, and don't see the ConnectionStringName anymore in the constructor options, which suggests it's gone. Any pointers on how to do that?
Cheers!

**Comment by colinbull** [comment]
I'm not sure that this, along with a host of other fixes has been deployed on NuGet yet (that package is nearly a year old). Can you try by building master yourself from source and let me know if the issues disappear?
