### ISSUE TITLE
When will be the latest nuget package released?

### ISSUE THREAD

**Issue by tamizhvendan** [fsprojects/SQLProvider#146]
Hi folks,

Thanks for developing an incredible library.

I'd like to use the POSTGRES sql provider to access data from tables in a different schema other than "public". But it seems the current nuget version of SQLProvider doesn't support it.

Upon checking the source code in github I found out that it has been fixed and hardcoded reference of the schema name 'public' has been replaced with the parameter 'owner'.

The current version of nuget has been released on "May 21 2014" which is very old.

It would be very helpful if we release the latest codebase.

**Comment by tamizhvendan** [comment]
Tried by building the code locally. I am able to access tables only from 'public' namespace. The other namespaces are not working even if I change the owner name in SqlDataProvider type creation.

**Comment by colinbull** [comment]
Yeah, this is a work in progress there are a lot of changes pending. Me and @pezipink are currently discussing the best way to merge all of the changes, once we have a strategy we will do a release.

**Comment by tamizhvendan** [comment]
Thanks @colinbull. Looking forward :-)

**Comment by Thorium** [comment]
+1

Yes I would also like to see the current GitHub version in NuGet. There is the All-target in build.fsx which does the release so it should be quite simple to do the next release. 

It don't have to be perfect, it just would make it easier to do more contributions for the next version: now it is not clear which issues are from the nuget package version and what are from the GitHub version.

**Comment by TheAngryByrd** [comment]
+1

**Comment by kunjee17** [comment]
:+1: waiting for postgres support.
