### ISSUE TITLE
Strange MSSQL barf on "UPPER"

### ISSUE THREAD

**Issue by psfblair** [fsprojects/SQLProvider#147]
Connecting to MS SQL Server during compilation of my project I'm seeing this:

`Db.fs(17,11): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Invalid object name 'UPPER'. [websharper-warp-sqlprovider.fsproj]`

Db.fs is fairly innocuous (and I believe it connects, since earlier attempts with different connection strings didn't):

    [<Literal>] 
    let compileTimeConnectionString = """
    Server=.\SQLEXPRESS;
    Database=hello;
    User Id=user;
    Password=pass;
    max pool size=32767
    """

    type Db = SqlDataProvider<DatabaseVendor    = Common.DatabaseProviderTypes.MSSQLSERVER, 
                          ConnectionString  = compileTimeConnectionString,      
                          UseOptionTypes    = true>

From what I can see this looks like it's probably coming from Providers.MsSqlServer.fs : 

    265          member __.GetTables(con,cs) = 
    266             let caseChane =  
    267                 match cs with 
    268                 | Common.CaseSensitivityChange.TOUPPER -> "UPPER(INFORMATION_SCHEMA.TABLES)" 
    269                 | Common.CaseSensitivityChange.TOLOWER -> "LOWER(INFORMATION_SCHEMA.TABLES)" 
    270                 | _ -> "INFORMATION_SCHEMA.TABLES" 
    271             MSSqlServer.connect con (fun con ->  
    272             use reader = MSSqlServer.executeSql ("select TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE from "+caseChane) con 
    273             [ while reader.Read() do  
    274                 let table ={ Schema = reader.GetSqlString(0).Value ; Name = reader.GetSqlString(1).Value ; Type=reader.GetSqlString(2).Value.ToLower() }  
    275                 if tableLookup.ContainsKey table.FullName = false then tableLookup.Add(table.FullName,table) 
    276                 yield table ]) 

I'm not exactly sure what's going on here, though. I'd submit a fix, but I'm not sure what's intended. Any ideas?

**Comment by psfblair** [comment]
MySQL provider also seems to have a similar problem:

    279         member __.GetTables(con,cs) = 
    280             let caseChane =  
    281                 match cs with 
    282                 | Common.CaseSensitivityChange.TOUPPER -> "UPPER(TABLE_SCHEMA)" 
    283                 | Common.CaseSensitivityChange.TOLOWER -> "LOWER(TABLE_SCHEMA)" 
    284                 | _ -> "TABLE_SCHEMA" 
    285             MySql.connect con (fun con -> 
    286                 use reader = MySql.executeSql (sprintf "select TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE from INFORMATION_SCHEMA.TABLES where %s = '%s'" caseChane MySql.owner) con 
    287                 [ while reader.Read() do  
    288                     let table ={ Schema = reader.GetString(0); Name = reader.GetString(1); Type=reader.GetString(2) }  
    289                     if tableLookup.ContainsKey table.FullName = false then tableLookup.Add(table.FullName,table) 
    290                     yield table ]) 

The intention here seems to be to change the case of the schema name depending on `cs`, but `caseChane` is never referenced. I'll submit a PR for this assuming that I understand it properly; however with MS SQL I'm not sure which columns are supposed to have their case changed.

**Comment by colinbull** [comment]
These are recent changes that where an attempt to fix the case sensitivity issues, caused by some mono providers. However this fix looks a little bizarre as it seems to be trying to upper case the table object, rather than the string. I might be missing something here though, as I haven't looked in detail. 

-----Original Message-----

**Comment by pezipink** [comment]
@Thorium any idea on this?

I will try and test here a bit later and see what's going on

**Comment by Thorium** [comment]
There was this problem that the SQLProvider didn't work on Case Sensitive databases (not MS-SQL nor MySQL) after the addition of the PostgreSQL support: If case change has been modified in the logic side, it has to be also modified in the SQL-clause.

**Comment by psfblair** [comment]
Yes, I confirmed that it works if I use Common.CaseSensitivityChange.ORIGINAL. Thanks!
