### ISSUE TITLE
this nuget package does not appear for search term "typeprovider"

### ISSUE THREAD

**Issue by gdennie** [fsprojects/SQLProvider#151]
The one word term, "typeprovider", is a sufficiently distinguishing usage in f# that it would be useful if SQLProvider included it as a searchable keyword reference in Nuget, if that is possible.

**Comment by pezipink** [comment]
I will make sure this is included in the next package (which should be soon!), I thought it already was.  This is still marked as pre-release though which messes up the search results somewhat as well
