### ISSUE TITLE
Changing database schema does not have effect in MySQL provider

### ISSUE THREAD

**Issue by jasonweiyi** [fsprojects/SQLProvider#152]
I first created a MySQL type provider by specifying Database=db1, and successfully got the types created. But when I change to Database=db2, the created types are still for db1. Meaning that when I try to do Intellisense, the suggested types does not contain db2, and when I try to write a query for db2, the query expression does not type check. I tried to restart Visual Studio, the problem does not go away.

The following is my code:

#r "../../packages/MySql.Data.6.9.7/lib/net45/MySql.Data.dll" 
#r "../../packages/SQLProvider.0.0.9-alpha/lib/net40/FSharp.Data.SqlProvider.dll"

open System
open System.Linq
open FSharp.Data.Sql
open MySql.Data

[<Literal>]
let ResolutionPath = @"SOME_FOLDER\packages\MySql.Data.6.9.7\lib\net45"

type sql = SqlDataProvider<"Server=SERVER_NAME;Database=db2;Uid=USER;Pwd=PASSWORD", Common.DatabaseProviderTypes.MYSQL,ResolutionPath=ResolutionPath>
let ctxt = sql.GetDataContext()

I used Database=db1 first, it worked. But when I change to Database=db2, the generated types does not contain the ones for db2. I do have db2 in my database and I can access it through MySQL workbench under the connection string.

**Comment by pezipink** [comment]
When you say you restarted visual studio, was that with the file saved with the db2 in the connection string?

If you change the type alias `sql` this will also force the type provider to refresh as it will see it as a new type provider.  

Unfortunately I don't have a MySQL database to try and replicate this issue with right now, though maybe @Thorium could try it ?  :)

**Comment by Thorium** [comment]
I think you have to add the Owner-parameter to SqlDataProvider-parameters when using MySQL. The Owner is the same as the database name.

Visual Studio does some kind of caching but it should fetch the tables quite often.

**Comment by pezipink** [comment]
I thought Owner was for Oracle only? @colinbull added that and I have never used it

**Comment by pezipink** [comment]
ahh yes you are correct, it does seem to use Owner.  @jasonweiyi if you can try that ....

**Comment by jasonweiyi** [comment]
I did the following

type sql2 =
SqlDataProvider<"Server=SERVER;Database=db2;Uid=USER;Pwd=PASSWORD",
Common.DatabaseProviderTypes.MYSQL,ResolutionPath=ResolutionPath,Owner="db2">
let ctxt2 = sql2.GetDataContext()

But the problem is still there.



On Tue, Aug 4, 2015 at 1:03 PM, Ross McKinlay <notifications@github.com>
wrote:

> ahh yes you are correct, it does seem to use Owner. @jasonweiyi
> <https://github.com/jasonweiyi> if you can try that ....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsprojects/SQLProvider/issues/152#issuecomment-127578188>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by Thorium** [comment]
I think using Dictionary<_, _> for caching inside providers is not optimal.
- We don't have cache invalidation methods. That's hard anyways as type providers support many editors, not only Visual Studio. 
- There has to be manual lock as there can be many threads (e.g. a web server) using the code. So .NET has this ConcurrentDictionary which could be better. Or something like this http://www.fssnip.net/7Pv

**Comment by Thorium** [comment]
"Works on my machine.": Changing the schema will update the database. This is a bit scary/weird even as connectionstring already has a database name. But seems to work.

(I still usually restart Visual Studio when working with solutions using different databases.)
