### ISSUE TITLE
The input sequence was empty issue

### ISSUE THREAD

**Issue by jasonweiyi** [fsprojects/SQLProvider#153]
(I'm not sure this is an issue or I'm missing something in the code)

I'm using SQLProvider to connect to MySQL. And the MySQL database has the table urls with two columns, one is "url:varchar(128)", the other is "length:int".

When I do the following in F#:
let result = 
    query {
        for v in ctxt.``[demo].[urls]`` do        
        select v.url
    }
    |> Seq.toArray

I got the correct result:
val result : string [] =
  [|"http://www.amazon.com"; "http://www.google.com";
    "http://www.microsoft.com"|]

But when I do:

let result = 
    query {
        for v in ctxt.``[demo].[urls]`` do        
        select v
    }
|> Seq.toArray

I got the following error:
System.ArgumentException: The input sequence was empty.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source)
   at FSharp.Data.Sql.QueryExpression.QueryExpressionTransformer.convertExpression(SqlExp exp, List`1 entityIndex, IDbConnection con, ISqlProvider provider) in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.QueryExpression.fs:line 143
   at FSharp.Data.Sql.Runtime.QueryImplementation.executeQuery(ISqlDataContext dc, ISqlProvider provider, SqlExp sqlExp, List`1 ti) in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.Linq.fs:line 36
   at FSharp.Data.Sql.Runtime.QueryImplementation.SqlQueryable`1.System-Collections-Generic-IEnumerable`1-GetEnumerator() in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.Linq.fs:line 77
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at <StartupCode$FSI_0051>.$FSI_0051.main@() in C:\jasonw\mbrace-starterkit-fork\azure\HandsOnTutorial\13-accessing-mysql.fsx:line 33
Stopped due to error

**Comment by pezipink** [comment]
Is this the nuget package or the latest from master?  the `Seq.head` call I cannot see in the source.  This problem seems very odd

**Comment by jasonweiyi** [comment]
It is installed from Nuget.

On Fri, Aug 7, 2015 at 12:36 PM, Ross McKinlay <notifications@github.com>
wrote:

> Is this the nuget package or the latest from master? the Seq.head call I
> cannot see in the source. This problem seems very odd
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsprojects/SQLProvider/issues/153#issuecomment-128680241>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by pezipink** [comment]
Ah, this is probably already fixed in master then - sorry about that, looking to do a new release soon.

**Comment by jasonweiyi** [comment]
When will you have a new release of SQLProvider to solve the problem?

On Fri, Aug 7, 2015 at 1:21 PM, Ross McKinlay <notifications@github.com>
wrote:

> Ah, this is probably already fixed in master then - sorry about that,
> looking to do a new release soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsprojects/SQLProvider/issues/153#issuecomment-128686518>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by Krishna-Desiraju** [comment]
Am also facing the same issue. Is there anyway the changes are continuously deployed to nuget

**Comment by pezipink** [comment]
We're working on it! The Development_V1 branch is what will be published very soon.

**Comment by xenocons** [comment]
Hello, I am not sure if this is the same one(let me know if its not I can create a new 1), but it looks similar, the culprit is https://github.com/fsprojects/SQLProvider/blob/Development_V1/src/SQLProvider/SqlRuntime.QueryExpression.fs#L185 

query allows to return user value instead of actual sql value, e.g.
```
query {
   for e in dbstuff.dbtable do
     where (e="123")
     select true
} |> Seq.toArray
```
will throw
```
System.ArgumentException: The input sequence was empty.
Parameter name: source
>    at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source)
```
