### ISSUE TITLE
SQLProvider not working with Npgsql 3.0

### ISSUE THREAD

**Issue by psfblair** [fsprojects/SQLProvider#154]
Upgraded to Npgsql 3.0 and everything's gone wonky with postgres.

Intellisense shows me dataContext.``[PUBLIC].[FORTUNE]`` but won't let me put .Individuals after it, and basically won't autocomplete anything at that point.

If I do:
dataContext.``[PUBLIC].[FORTUNE]`` |> Seq.map (fun row -> row.id)

It says "the field, constructor, or member 'id' is undefined." Autocomplete gives me members of SqlEntity such as ColumnValues and DataContext.

**Comment by janno-p** [comment]
I tried Npgsql 3.0 with current master and after fixing the issue with string types (#155), the test script loaded and everything the script expected was loaded correctly.

There seems to be an issue with stored functions at the runtime though. It looks that there are some changes regarding functions returning refcursor. Querying from such function returns `"<unnamed portal n>"` as a result. It seems Npgsql 2.x versions handle that result internally, but Npgsql 3.0 expects clients to handle the portals by themselves (or at least that portal is returned at the moment and it doesn't fit with record type constructor in `SqlEntity.MapTo` member method).

**Comment by kunjee17** [comment]
I tried using Npgsql 3.0.3 and things break. Type provider started crying for mono.security.dll. I don't know why. For now I rolled back to 2.2.7. 

let me know if any other details are needed for issue.

**Comment by colinbull** [comment]
Yeah, I had a look at this tonight and there is quiet a few things we need to change to support >= 3.0, so for the moment at least 2.2.7 will be the preferred postgres version. As I don't see an easy way of supporting both. Changing this to up-for-grabs ;)

**Comment by kunjee17** [comment]
@janno-p hey, you have a branch where Npgsql 3.0.3 working? I am so wanted to pull that one.

**Comment by janno-p** [comment]
Hey @kunjee17, my npgsql3.0 branch is actually the one where I tried using >= 3.0 version of Npgsql. I made some small changes as described in my previous comment, and these should be already merged into the main repository. So, nothing extra in there.

**Comment by colinbull** [comment]
Indeed these changes are merged. In the limited things I have tried, it seems that all the query support is there. The only thing that doesn't work is the stored procedures.

**Comment by kunjee17** [comment]
@janno-p and @colinbull thanks guys. I'll have a look again at my code with update. Will post the update. Thanks.

**Comment by kunjee17** [comment]
@janno-p hey, I was trying that again. But I guess current build is targeting 2.2.7 only. as per paket file.  And then I was trying to run with 3.x and getting weird error. Even nuget seems to be not updated. Any idea or way to help. 

cc/ @colinbull

**Comment by kunjee17** [comment]
"Exception has been thrown from the target of invocation" error is coming if I update to Npgsql.3.0.5. But updated nuget is working good with Npgsql.2.2.7. 

I know its still an open issue. I m just giving update as I finally got chance to test things.

**Comment by Thorium** [comment]
Is this still an issue?
