### ISSUE TITLE
Error during type provision: "Type mismatch when splicing expression into quotation literal"

### ISSUE THREAD

**Issue by Overlord-Zurg** [fsprojects/SQLProvider#156]
I am pointing this type provider at my database and try to code a call to a stored procedure.

    type dbSchema = SqlDataProvider<ConnectionString = "Data Source=(connection string)",
                                     DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER,
                                     UseOptionTypes = true>
    
    let DB = dbSchema.GetDataContext()

I get the following (compile-time) error:

    DB.fs(18,15): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error in the context of provided type 'FSharp.Data.Sql.SqlDataProvider,ConnectionString="(connection string)",DatabaseVendor="0",UseOptionTypes="True"+dataContext+SprocContainer', member '[dbo].[te_employee]'. The error: Type mismatch when splicing expression into quotation literal. The type of the expression tree being inserted doesn't match the type expected by the splicing operation. Expected 'FSharp.Data.Sql.Runtime.SqlDataContext', but received type 'System.Object'. Consider type-annotating with the expected expression type, e.g., (%% x : string) or (%x : string).
    
    Parameter name: receivedType

What does it mean? Is there anything I can do about it?

**Comment by pezipink** [comment]
Are you using the nuget package or the latest version? Please build from the source as the package is quite dated at the moment.

Does your stored procedure contain table-value parameters, XML types, or user defined types?

**Comment by Overlord-Zurg** [comment]
Yep, I was totes using the NuGet package. Works from source.  :)

**Comment by pezipink** [comment]
Aweome, sorry about  that, really am going to address the package thing soon
