### ISSUE TITLE
Connection to SQLite does not work

### ISSUE THREAD

**Issue by renkun-ken** [fsprojects/SQLProvider#16]
I try to use a simple SQLite v3 database but the type provider does not work.

``` F#
open System
open System.Linq
open FSharp.Data.Sql
open System.Data.SQLite
open System.Data.SQLite.Generic

let [<Literal>] connString = @"Data Source=d:\data\fmarket.sqlite;Version=3"
let [<Literal>] lib = @"D:\Programming\Projects\FSQLite\packages\System.Data.SQLite.1.0.90.0\lib\net451\"

type sql = SqlDataProvider<connString,Common.DatabaseProviderTypes.SQLITE,lib>
let context = sql.GetDataContext()
```

The code compiles with no error but 2 errors always appear:
Error   1   The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Exception has been thrown by the target of an invocation.    D:\Programming\Projects\FSQLite\FSQLite\Program.fs  12  12  FSQLite

Error   2   The field, constructor or member 'GetDataContext' is not defined    D:\Programming\Projects\FSQLite\FSQLite\Program.fs  13  19  FSQLite

At first, the code simply does not compile and I found I need to copy the SQLite.Interop.dll from x86/x64 folder to the program folder. However, it still does not work even as the code compiles. I cannot get a data context that provides any strong types in it. Since the database it quite simple, it works whenever I use SQLite official library to query it or somewhere else in R via RSQLite package.

What may be the problem?

**Comment by philsivyer** [comment]
Hi
I have a similar problem when desperately trying to connect to ORACLE.
I get error message "'FSharp.Data.Sql.SqlTypeProvider' reported an error: Exception has been thrown by the target of an invocation."
My code is:
#r @"C:\Users\Documents\Visual Studio 2013\Projects\Library2\packages\SQLProvider.0.0.9-alpha\lib\net40\FSharp.Data.SqlProvider.dll"

open System
open System.Linq
open FSharp.Data.Sql

// create a type alias with the connection string and database vendor settings
type sql = SqlDataProvider< 
              ConnectionString = @"Data Source=pmlbsgdev;Initial Catalog=data001;Integrated Security=True",
              DatabaseVendor = Common.DatabaseProviderTypes.ORACLE,
              ResolutionPath = @"C:\Users\Downloads\ODP.NET_Managed121020\odp.net\managed\common",
              IndividualsAmount = 1000,
              UseOptionTypes = true >
let ctx = sql.GetDataContext()

**Comment by pezipink** [comment]
Could you open a new issue with this information in it please? It will help us track it better.

Thanks!
