### ISSUE TITLE
`Exception has been thrown by the target of an invocation.` Error thrown with SQLite database.

### ISSUE THREAD

**Issue by bricef** [fsprojects/SQLProvider#160]
## Summary

Trying to run a very simple SQLite connection throws a `Exception has been thrown by the target of an invocation.` error. Without additional details about the cause of the exception, I am unsure how to proceed. No doubt the error is thrown by `System.Data.SQLite` but I'm not sure how to get to the root cause.

I'm probably doing something stupid due to inexperience.

## Platform versions

* Xamarin Studio 5.9.5
* Mac Yosemite 10.10.4
* SQLProvider 0.0.9-alpha
* Mono/.NET 4.0
* Build: Debug/x86
* System.Data.SQLite from nuget, version 1.0.98.1

## Details

Trying to run the following code in the FSI:

```fsharp
#I "/Users/brice/Projects/Tutorial/packages/SQLProvider.0.0.9-alpha/lib/net40"
#r "FSharp.Data.SQLProvider.dll"

#I "/Users/brice/Projects/Tutorial/packages/System.Data.SQLite.Core.1.0.98.1/lib/net40"
#r "System.Data.SQLite.dll"

open System
open System.Linq
open FSharp.Data.Sql

// create a type alias with the connection string and database vendor settings
type sql = SqlDataProvider< 
              ConnectionString = @"Data Source=./test.sqlite",
              DatabaseVendor = Common.DatabaseProviderTypes.SQLITE,
              ResolutionPath = @"/Users/brice/Projects/Tutorial/packages/System.Data.SQLite.Core.1.0.98.1/lib/net40",
              UseOptionTypes = true >

let ctx = sql.GetDataContext()
```

Leads to this output:

```
> 
F# Interactive for F# 3.1 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License
For help type #help;;

> 
--> Added '/Users/brice/Projects/Tutorial/packages/SQLProvider.0.0.9-alpha/lib/net40' to library include path
--> Referenced '/Users/brice/Projects/Tutorial/packages/SQLProvider.0.0.9-alpha/lib/net40/FSharp.Data.SQLProvider.dll' (file may be locked by F# Interactive process)
--> Added '/Users/brice/Projects/Tutorial/packages/System.Data.SQLite.Core.1.0.98.1/lib/net40' to library include path
--> Referenced '/Users/brice/Projects/Tutorial/packages/System.Data.SQLite.Core.1.0.98.1/lib/net40/System.Data.SQLite.dll' (file may be locked by F# Interactive process)
/Users/brice/Projects/Tutorial/Tutorial/Script.fsx(12,12): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Exception has been thrown by the target of an invocation.

> 
```

**Comment by colinbull** [comment]
I honestly, cant remember what the state of SQLlite support was in the nuget package, so cant guarantee the following will work. But I would just check a couple of things.

* make sure you have write permissions to the sqllite file as you aren't opening in read only mode.
* I think your referencing the windows sqlite package, if memory serves it is 'mono.data.sqlite' you want to use.

Let me know if I can help anymore.

**Comment by bricef** [comment]
Thanks @colinbull, will check these tips out.

**Comment by bricef** [comment]
The permissions were fine. 

When I changed the the resolution path to point to the `Mono.Data.Sqlite.dll` directory, the `SqlTypeProvider` is still looking for the `System.Data.Sqlite.dll`, which is naturally not there. In particular:

```
--> Referenced '/Library/Frameworks/Mono.framework/Versions/4.0.3/lib/mono/4.5/Mono.Data.Sqlite.dll' (file may be locked by F# Interactive process)
/Users/brice/Projects/Tutorial/Tutorial/Script.fsx(12,12): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not load file or assembly '/Users/brice/Projects/Tutorial/packages/Mono.Data.Sqlite.Portable.1.0.3.5/lib/net4/System.Data.SQLite.dll' or one of its dependencies. The system cannot find the file specified.
```

**Comment by pezipink** [comment]
this seems rather odd, we have supported mono for sqlite for a long time and people are using it, this in particular should be preventing this happening:

https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.SQLite.fs#L24

I will need to get a mono machine running to try it though.  

ps. you don't need to `#r` the sqlite assembly in your script, in fact that may well be confusing it.

**Comment by bricef** [comment]
Just checked, @pezipink, but still get the same error when removing the `#r`.

**Comment by SoulFireMage** [comment]
I have exactly the same issue but not with mono and tried copying over the interop file but simply get the following:

    Severity	Code	Source	Description	Project	File	Line
    Error		Build	A reference to the type
    'FSharp.Data.Sql.SqlDataProvider,ConnectionString="Data Source=C:\\Users\\Richard\\Source\\Workspaces\\Workspace\\Maths\\MCourse\\CRmathsdb.db;Version=3",DatabaseVendor="1",ResolutionPath="C:\\Users\\Richard\\Source\\Workspaces\\Workspace\\Maths\\MCourse\\packages\\System.Data.SQLite.Core.1.0.98.1\\lib\\net46\\",UseOptionTypes="True"' in assembly 'FSharp.Data.SqlProvider' was found, but the type could not be found in that assembly	fsquizlib	C:\Users\Richard\Source\Workspaces\Workspace\Maths\MCourse\fsquizlib\DataAccess.fs	8

**Comment by pezipink** [comment]
@SoulFireMage have you tried the fix from the "Known Issues" section on the project home page?

Also it may just be that you need to use a different version / architecture assembly, SQLIte its very funny with this stuff. I suggest you try to use the explicit 32bit build and see if that will work.  The "interop" assembly thing did not work if I recall.  You can see the one we are using here https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Tests

@bricef I guess you gave up on this, I do not know if the workaround listed on the front page applies to XS or Mono in general, I would be interested to know if you have any knowledge on that front, or have tried those fixes.

**Comment by bricef** [comment]
@pezipink I fixed my problem. Used another language (Haskell) to do the job instead and was finished in 15min. That's hardly a bug resolution though ;)

It's no longer a priority as far as I'm concerned, I'll try to dig through the links you posted when/if I get the time but can't commit to it.

**Comment by SoulFireMage** [comment]
@pezipink Thank you Ross, I'll try this today with a separate project see if I can get it to go.

**Comment by coopernurse** [comment]
FWIW I can repro this problem on Ubuntu 15.04 with Mono 4.2.1 and F# 4.0.  I ran into this independently inside FSI, but also tried copying the .fsx bits @bricef included in initial report above and got the same error:

```
/home/james/src/fsharp-examples/dbtest.fsx(12,12): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Exception has been thrown by the target of an invocation.
```

Dependencies are:

System.Data.SQLite 1.0.99
SQLProvider 0.0.9-alpha

I'm new to .NET so I'm unclear on the suggestion to use the Mono SQLite package.  Is the System.Data.SQLite assembly using native code somewhere?  I'm able to open that assembly in FSI, although I haven't done anything with it.

I may play around with the MySQL driver and see if I get the same behavior.  That will help clarify whether this is a SQLite driver issue, or a more general SQLProvider on mono issue, or possibly user error in my case, as I'm completely new to these tools.

**Comment by coopernurse** [comment]
Looks like it may be SQLite specific - a quick test with MySQL appeared to work fine.

**Comment by raymens** [comment]
I have the same error using VS2015, W10 x64, SQLProvider *1.0.6* and System.Data.SQLite.Core *1.0.101.0* (NuGet). It's unable to find the interop DLL.

**Comment by Thorium** [comment]
I think that the problem is that the nuget package doesn't contain SQLite.Interop.dll.

http://stackoverflow.com/a/18559177/17791

**Comment by Thorium** [comment]
Yes, the Nuget package doesn't contain `SQLite.Interop.dll`. 

This is more of a problem of the [SQLite Nuget package](https://www.nuget.org/packages/System.Data.SQLite.Core/) than SQLProvider.

You probably wouldn't need this dll if you run in 64bit mode, but Visual Studio and FSI are usually used in 32bit mode: http://stackoverflow.com/a/18559177/17791

**Comment by Thorium** [comment]
Hmm, GitHub seems to delete my answers to this thread...

SQLite Nuget package (
https://www.nuget.org/packages/System.Data.SQLite.Core/)
is missing SQLite.Interop.dll

This dll is needed when running in 32bit mode. (VS or FSI usually are in
32bit mode.)

I think this is problem of the Nuget package and not SQLProvider.
http://stackoverflow.com/a/18559177/17791

**Comment by Thorium** [comment]
Hmm, GitHub seems to delete my answers to this thread...

SQLite Nuget package (
https://www.nuget.org/packages/System.Data.SQLite.Core/)
is missing SQLite.Interop.dll

This dll is needed when running in 32bit mode. (VS or FSI usually are in
32bit mode.)

I think this is problem of the Nuget package and not SQLProvider.
http://stackoverflow.com/a/18559177/17791

**Comment by raymens** [comment]
The NuGet does contain the `SQLite.Interop.dll`, both the x64 as the x86 DLL. It's in de `build` subfolder and is automatically copied to the project compile output folder. I've also tried to set the `ResolutionPath` to a certain path and copied both the Interop as the default SQLite dll in it.

**Comment by Thorium** [comment]
Can you test if this gives more details now?

**Comment by raymens** [comment]
It does output helpful information now. I fixed it by copying over the 32bit interop DLL, stupid of me for not doing that earlier as you mentioned it. Thanks!

It is weird though when I use the following resolution path:
`[<Literal>]
let path = __SOURCE_DIRECTORY__ + @"../../packages/System.Data.SQLite.Core.1.0.101.0/build/net46/x86/"`

In the error message it mentions the right path but is unable to find the DLL located in it.

**Comment by colinbull** [comment]
AFAIK, Sqlite really doesn't like folder relative paths. I don't think it
will evaluate the ../../ it might be worth giving it ago without those
paths. Maybe the SQLite dirver in the TP should do this.

**Comment by Thorium** [comment]
@colinbull we can evaluate relative to real with `|> System.IO.Path.GetFullPath` but the problems are that by default the interop dll path is not the same that SQLite.Data.dll path (resolution path is string, not array) and this 32bit vs. 64bit interop problem.

**Comment by Thorium** [comment]
Now it also describes a special errors if any, in DLL loading.

**Comment by ckasesmith** [comment]
@SoulFireMage have you tried the fix from the "Known Issues" section on the project home page?

Also it may just be that you need to use a different version / architecture assembly, SQLIte its very funny with this stuff. I suggest you try to use the explicit 32bit build and see if that will work. The "interop" assembly thing did not work if I recall. You can see the one we are using here https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Tests

@bricef I guess you gave up on this, I do not know if the workaround listed on the front page applies to XS or Mono in general, I would be interested to know if you have any knowledge on that front, or have tried those fixes.

Spent over an hour trying to figure out why one row in my database was causing the invocation error, even null out the values, nothing worked until I finally set the build to X86.
