### ISSUE TITLE
sortBy with multiple columns fails

### ISSUE THREAD

**Issue by vilinski** [fsprojects/SQLProvider#164]
This works:

    let newAnnouncements = 
        query { for n in ctx.``[dbo].[FeatureDeleteAnnouncements]`` do
                sortBy n.pg_id
                select n
        }

but this fails:

    let newAnnouncements = 
        query { for n in ctx.``[dbo].[FeatureDeleteAnnouncements]`` do
                sortBy (n.pg_id,n.feature_id)
                select n
        }

with runtime error:

  System.Exception: unrecognised method call
     at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
  >    at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
     at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
     at Microsoft.FSharp.Linq.QueryModule.clo@1737-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
     at <StartupCode$FSI_0008>.$FSI_0008.main@()
  Stopped due to error

or how can I do this? Also interested on outer join on multiple columns

**Comment by pezipink** [comment]
Hi, you should be able to sort by multiple columns by including more than one `sortBy` or `sortByDescending` clauses, they will be processed in the order they are encountered.

For outer joins, the `leftOuterJoin` keyword is not supported as it requires us to implement `groupJoin` which in turns requires a bunch of other stuff that has not been done yet.  If your join is between fields with foreign keys setup, you can get it to left join by using the special `(!!)` operator within the `for..` syntax, eg  ` for prod in (!!) table1.MyForeignKey do... `

Cheers

**Comment by kmikeru** [comment]
Is it possible to do outer join on arbitrary columns (without PK/FK)?

**Comment by Thorium** [comment]
Original question is answered by pezipink and the second question is duplicate to #141

**Comment by Thorium** [comment]
You can use `thenBy` to sort by multiple columns.

> Is it possible to do outer join on arbitrary columns (without PK/FK)?
When this was asked it wasn't working, now it is.
