### ISSUE TITLE
Support for logging

### ISSUE THREAD

**Issue by zhengbli** [fsprojects/SQLProvider#166]
I was trying to check the generated SQL statements of the query expressions I wrote in F#, though I didn't find out a logging option to redirect them to `Console.Out`. It would be helpful to add supports for that. Thanks!

**Comment by colinbull** [comment]
There is an event to subscribe to you can see and example [here](https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Tests/OracleTests.fsx#L11)

Or it is simply 

     FSharp.Data.Sql.Common.QueryEvents.SqlQueryEvent |> Event.add (printfn "Executing SQL: %s")

**Comment by pezipink** [comment]
Ninja!  Just beat me :)

**Comment by zhengbli** [comment]
Super neat. Thanks for the work!
