### ISSUE TITLE
This control construct may only be used if the computation expression builder defines a 'For' method

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/SQLProvider#170]
I am attempting to use the Sql Provider against the Adventure Works database.  I can connect and the types are getting defined correctly.  When I attempt to create this computational expression

#r "../packages/SQLProvider.0.0.9-alpha/lib/net40/FSharp.Data.SQLProvider.dll"
open FSharp.Data.Sql

type AdventureWorks = SqlDataProvider<connectionString>
let context = AdventureWorks.GetDataContext()

let salesOrderQuery = query { for soh in context.``[Sales].[SalesOrderHeader]`` do
                              select soh} |> Seq.toArray

I get this exception
This control construct may only be used if the computation expression builder defines a 'For' method

Can you give me a suggestion on how to fix?  Thanks

**Comment by jamessdixon** [comment]
Interestingly, even though it returns that error in the script file, when I send it to the FSI, it works.  I am having a different problem now. Iam trying the in operator and it is failing

let salesOrderQuery = query { for soh in context.``[Sales].[SalesOrderHeader]`` do
                              join sod in context.``[Sales].[SalesOrderDetail]`` on (soh.SalesOrderID = sod.SalesOrderID)
                              join p in context.``[Production].[Product]`` on (sod.ProductID = p.ProductID)
                              where (soh.OrderDate > DateTime(2013,5,1) && p.ProductSubcategoryID |=| [|1 .. 3|]) 
                              select soh } |> Seq.toArray

Throws a
System.ArgumentException: No mapping exists from object type System.Object[] to a known managed provider native type.

Any ideas?

**Comment by colinbull** [comment]
Can you try lifting the construction of the array and the datetime out of the query expression and just replacing them with variables instead. I suspect we won't support constructors in query expressions. If this doesn't work, let me know and I'll have a look deeper when I have something more than my phone to hand.

**Comment by jamessdixon** [comment]
let productSubcategoryIDs = [|1 .. 3|]
let minOrderDate = DateTime(2013,5,1)
let salesOrderQuery = query { for soh in context.``[Sales].[SalesOrderHeader]`` do
                              join sod in context.``[Sales].[SalesOrderDetail]`` on (soh.SalesOrderID = sod.SalesOrderID)
                              join p in context.``[Production].[Product]`` on (sod.ProductID = p.ProductID)
                              where (soh.OrderDate > minOrderDate && p.ProductSubcategoryID |=| productSubcategoryIDs)
                              select (soh) } |> Seq.toArray


Still returns the same error

**Comment by pezipink** [comment]
there was a change to this stuff very recently. Coincidence?  
880f77e88fb2b40c748f82ba6659334e5a058b4b

**Comment by pezipink** [comment]
@jamessdixon are you using the latest development-v1 branch? or the old package?

**Comment by jamessdixon** [comment]
Nuget

I am using it in the book I am writing so I need to use Nuget…

**Comment by pezipink** [comment]
ah ok ouch.... that should really be working. the package is over a year old though and massively out of date (sorry). It is likely working in the dev v1 branch.  We did make a push for the new package, there is not a lot left to do but I / we got waylaid with other stuff and I will be tied up until the end of the year now :(

**Comment by jamessdixon** [comment]
I’ll pull the dev branch

Any objections if I create a nugget package from the latest on github and out it out there?

I really want to use it in my book.

**Comment by pezipink** [comment]
Sure thing, hopefully by the time you are finished, the V1 branch will be the published version anyway! 

Regarding the In operator, in this particular example you can get around using in by using > and <  but I know that is not ideal.

**Comment by jamessdixon** [comment]
Thanks

**Comment by jamessdixon** [comment]
So that did it

There are some changes:

 

type AdventureWorks = SqlDataProvider<Common.DatabaseProviderTypes.MSSQLSERVER,connectionString>

 

And SCREEMING CAPS for the entities and attributes

 

let salesOrderQuery = query { for soh in context.``[SALES].[SALESORDERHEADER]`` do

                              join sod in context.``[SALES].[SALESORDERDETAIL]`` on (soh.SALESORDERID = sod.SALESORDERID)

                              join p in context.``[PRODUCTION].[PRODUCT]`` on (sod.PRODUCTID = p.PRODUCTID)

                              where (soh.ORDERDATE > DateTime(2013,5,1) && p.PRODUCTSUBCATEGORYID  |=| [|1..3|])

                              select (soh) } |> Seq.toArray

 

Returns data.  Still getting the REPL complaining that For method is not implemented…

I’ll hold off on deploying to nugget until it is ready.  Until then, I will use it assuming that the neew version will be out by the time the books goes March 31, 2016

 

Thanks

**Comment by pezipink** [comment]
cool, I have not seen the For thing before, that is strange.  Is the actual schema in caps?  We have changed the way stuff is named, there was a time when everything was in caps but it is not anymore.  I think there is even a static parameter to control it.

Also do you know that you don't have to write those joins explicitly? you can just `for` over the relevant relationship property of the source type.

**Comment by pezipink** [comment]
is that deffo the dev-v1 branch?  not just the latest of master? you want this one 

https://github.com/fsprojects/SQLProvider/tree/Development_V1

I think you might be using the wrong one as the static parameters are in a different order now and I believe master still has the ALL CAPS!

**Comment by jamessdixon** [comment]
The schema is not in caps

 



I built the Developerment_V1 branch

 

 

Joins - no, I did not know that

Can you refactor my sample to show me?

**Comment by pezipink** [comment]
I can't show you exactly as the names will depend on the schema, but it will be like this, as opposed to the test above it : 

https://github.com/fsprojects/SQLProvider/blob/Development_V1/tests/SqlProvider.Tests/QueryTests.fs#L268

**Comment by jamessdixon** [comment]
Oh nice

Thanks!

**Comment by colinbull** [comment]
Is this closed? Now?

**Comment by pezipink** [comment]
yeah I think so

**Comment by Thorium** [comment]
I got the same error message while running unit tests and figured out the reason for my case:

```fsharp
    let query = 
        query {
            for cust in dc.Main.Customers do
            select cust.CustomerId
            contains "ALFKI2"
        }
```
If I run this once works ok. But running it second time `query {` doesn't any more refer to the `QueryBuilder` class but the new variable `let query` and that is not a builder, so result is mystical sounding `error FS0708: This control construct may only be used if the computation expression builder defines a 'For' method` without stacktrace.

The fix is simple:
```fsharp
    let qry = 
        query {
            for cust in dc.Main.Customers do
            select cust.CustomerId
            contains "ALFKI2"
        }
```
