### ISSUE TITLE
SubmitUpdates not thread safe

### ISSUE THREAD

**Issue by xenocons** [fsprojects/SQLProvider#173]
Hi,

I don't think this is an issue, as it relies on how .NET handles SQL stuff afaik, so feel free to close this.

Minimal repro:
```
let ctx1 = dbSchema.GetDataContext()
let duration eventName f =  
    let timer = new System.Diagnostics.Stopwatch()
    timer.Start()
    let returnValue = f()
    ctx1.``[DBO].[LOGGING]``.Create(
      DateTime.Now
      , sprintf "%O" timer.Elapsed
      ,eventName
      ,1) |> ignore
    ctx1.SubmitUpdates()
    returnValue
[| 0..2000|] |> Array.Parallel.map (fun k -> duration "abc" (fun () -> k+1))
```
This returns : ,"Unchanged entity encountered in update list - this should not be possible!"
Edit: fix typo

**Comment by pezipink** [comment]
Yes I think this a ok as it is. You are better off doing all your updates then calling SubmitUpdates once at the end, unless you dont want them all in one transaction for whatever reason.  I think it is reasonable for the client to come up with some sync strategy in a threaded scenario.

**Comment by xenocons** [comment]
agreed, closing
