### ISSUE TITLE
Option type not working in where clause

### ISSUE THREAD

**Issue by zhengbli** [fsprojects/SQLProvider#174]
I have the following code:
```fsharp
    type City = {
        Name: string
        State: string option
    }

    // The city table has two string columns: name, state
    // name is not nullable, and state is
    let getCityByRecord (r: City) =
        query {
            for c in ctx.``[DBO].[CITY]`` do 
            where (c.Name = r.Name)
            where (r.State.IsNone || c.State.IsNone || c.State.Value = r.State.Value)
            select c
        } |> Seq.tryHead
```

The code threw null reference exception when `r.State` is `None`. I guess option type should not show up in the where clause? However I can't really think of a clean way to do this.

**Comment by pezipink** [comment]
this code should work, we do support the `IsNone` and `.Value=...` syntax.  Could you try `IsNone` on it's own, maybe put those first two checks in their own `where` clause and try the second part in another `where` clause.  I am unsure to why this is not working, will have to have a look at this.

Are you using the V1 branch or the package?

**Comment by pezipink** [comment]
we are attempting to handle it yes https://github.com/fsprojects/SQLProvider/blob/Development_V1/src/SQLProvider/SqlRuntime.Linq.fs#L172

**Comment by zhengbli** [comment]
I'm on the master branch. Is the V1 branch newer? 

The `IsNone` and `.Value` is working if used independently, however the problem is the last part (`c.State.Value = r.State.Value`) gets evaluated even if `r` is `None`. 

I tried to separate the first two checks, though I couldn't figure out a way to do a conditional `where`. I tried to find items when either of `r` or `c` is `None` or they both have the same values.

**Comment by pezipink** [comment]
Yes Dev V1 is a lot newer, use that one.  I think the problem here is we might not currently support server side expressions on both sides of the predicate. We should be able to fix this by changing the patterns around to accommodate it (the place I linked above). I am not going to be able to get to it for a while though I am afraid :(

**Comment by Thorium** [comment]
I think this is working ok...
