### ISSUE TITLE
Table names are not quted in generated SQL in Development_V1 branch

### ISSUE THREAD

**Issue by zhengbli** [fsprojects/SQLProvider#175]
I got the following SQL 
```SQL
SELECT [x_11].[Id] as 'Id',[x_11].[Name] as 'Name',[x_11].[Email] as 'Email',[x_11].[Pwd] as 'Pwd',[x_11].[ProfileImage] as 'ProfileImage' 
FROM dbo.User as [x_11] 
```
From
```fsharp
query {
    for u in ctx.Dbo.User do select u
}
```

And that gave me an error because the `User` is a keyword in sql server.

I think it should generate `[dbo].[User]` instead of `dbo.User`

**Comment by pezipink** [comment]
Did this work in the other branch?  @colinbull do you know what happened to this?

**Comment by zhengbli** [comment]
This worked for me when I used `master`

**Comment by pezipink** [comment]
Ok, sorry about that, I did not think we had changed anything relating to the actual sql gen! Will try and look at this soon

**Comment by colinbull** [comment]
Hum nor was I I'll have a look at this tonight.

**Comment by colinbull** [comment]
@zhengbli @pezipink can you give this a test I don't have a SQL server instance to hand at the moment.

**Comment by zhengbli** [comment]
Sure I'll try it in a moment

**Comment by zhengbli** [comment]
The commit fixed the problem for me. Thanks!

**Comment by colinbull** [comment]
Closing..
