### ISSUE TITLE
Mapping over provided database types

### ISSUE THREAD

**Issue by forki** [fsprojects/SQLProvider#179]
@tforkmann and me are trying to convert from generated types to Domain model types:

    let private allElements = db.``[dbo].[C_Elements]``
    
    let mapToDomainModel element = 
      { X = element.X
        Y = element.Y
         ....
       }

    let AllElements = allElements |> Seq.map mapToDomainModel 

How can we tell mapToDomainModel that the input elements are of the generated type and the output elements are of `OurDomain.Element` type?

**Comment by colinbull** [comment]
There is an example of this https://github.com/fsprojects/SQLProvider/blob/Development_V1/tests/SqlProvider.Tests/scripts/PostgreSQLTests.fsx#L97. Which I think is available on the master branch. I'd just note there are a lot of bug fixes on the Development_V1 branch we are trying to get a nuget out and close the last few issues.

**Comment by forki** [comment]
cool. what is this generated mapping doing exactly?
Mapping by name and type?

**Comment by colinbull** [comment]
It is a very niave mapping by name. Really thats all we have at runtime since the types are erased. However there is an overload to the `MapTo` function that allows you to define your own mappings see here https://github.com/fsprojects/SQLProvider/blob/Development_V1/src/SQLProvider/SqlRuntime.Common.fs#L188

**Comment by pezipink** [comment]
If you need to write your own mappings you can get at the generated types to annotate them via the type name followed by the `dataContext` and then your mangled type name. eg

`CSMDB.dataContext.[api].[Benchmark]Entity`

**Comment by forki** [comment]
A mapTo with a lambda is pretty nice

**Comment by forki** [comment]
Yes what I'm looking for is the name of the type so that I can use it in the signature of my mapper function

**Comment by pezipink** [comment]
yes see my comment above, you can get to them.

**Comment by tforkmann** [comment]
@pezipink it worked! Thanks a lot!
