### ISSUE TITLE
PostgreSQL 'Owner' and schemas

### ISSUE THREAD

**Issue by xenocons** [fsprojects/SQLProvider#183]
Default owner seems to be 'public', one can change this, but only to a single schema, making it hard to span multiple schemas. (perhaps this is bad DB design?).

Anyway, a temporary hackaround (sql injection) is to do this:
```
type ps = SqlDataProvider<
              ConnectionString = @"Server=sql;Port=5432;Database=XXXDatabase;user id=XXXX; password=XXXX; Pooling=false",
              DatabaseVendor = Common.DatabaseProviderTypes.POSTGRESQL,
              Owner = "agent' OR table_schema = 'analysis' or table_schema = 'reporting' or table_schema = 'storage''">
```

I suggest:
1. the type provider SqlDataProvider is updated to use a list for the 'owner' field
2. the type provider SqlDataProvider updates the help to mention it can be used for Postg, currently it says the owner field is Oracle Only (ill try find this and add a pull req).

**Comment by Thorium** [comment]
Is this still a problem? This is kind of connected to #213

**Comment by Thorium** [comment]
This should be ok now. If you are not happy with the current implementation, please reopen the issue and describe why.

**Comment by JacobChang** [comment]
@Thorium I think the document should be updated as owner field is not Oracle Only anymore, I stuck with this today. If needed, I can add a PR on this

**Comment by Thorium** [comment]
It would be nice!
