### ISSUE TITLE
The world needs more type providers 

### ISSUE THREAD

**Issue by forki** [fsprojects/SQLProvider#19]
Instead of making the database provider a static parameter of a god type provider consider to create specialized type providers for every database vendor. 

This would make it easier to match optional parameters for the concrete provider (at least for the Dynamics NAV provider)

**Comment by Thorium** [comment]
Done.

**Comment by Thorium** [comment]
Hmm. We could do quite easily support for more ADO.NET / SQL -style providers:

- OLAP, supports ADO.NET and MDX is enough near SQL. Would be new domain to F# type providers? Also, interesting: e.g. https://bennyaustin.wordpress.com/2011/03/01/ssas-dmv-queries-cube-metadata/ 
- No-one uses DB2, right?

Odbc covers many cases but Odbc configs are a little bit clumsy. Then these more dynamic data sources, but maybe they could fetch design time schema data better with some independent type provider, and ODATA type provider already exists:
- Elasticsearch: Could be queried with SQL? https://github.com/NLPchina/elasticsearch-sql 
- MongoDB: No ADO but this: https://github.com/ElemarJR/LinqToMongo/tree/master/src although there is already easy non-TP way (maybe more natural?) to use mongo from F#
- Redis...?
