### ISSUE TITLE
Multiple joins

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/SQLProvider#198]
Hey,

is it possible to do mulitple joins in one queryrequest?

I tried following code but it didn't work:

let getdata = 
     query { for x in allx do
                  join y in ally on (y.name = x.name)
                  for m in allm do
                  join m in allm on (m.number = y.number)
                  for datapoints in alldatapoints do
                  join datapoints in alldatapoints on (m.accuntno = datapoints.accuntno)
                  where (...)
                  select (...)}

**Comment by colinbull** [comment]
Hi,

Yep it is, some examples of the joins that are available can be seen here https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Tests/scripts/SqlServerTests.fsx basically there are two types: 

* implicit - which uses typically use the 'for in' syntax an use the special navigation properties

* explicit - which uses the 'join in on' syntax. The limitation here is at the moment we don't support joining on composite keys e.g. (x.a,x.b) = (y.a,y.b) 

Hope this helps, apologies for the short answer I'll reply more fully this evening when I'm at a proper computer, rather than my phone

**Comment by pezipink** [comment]
I am not sure what you are trying to achieve with the query in your example.  How is `allm` related to `allx` or `alldatapoints`?  They look like 3 separate disjoint queries to me. What would you expect the generated SQL to look like?

**Comment by pezipink** [comment]
Sorry, I see now the queries does reference each other (it is early!).  You do not need the subsequent `for` blocks, you just do the joins and then select.

**Comment by tforkmann** [comment]
Got it working!

Thanks guys!

It's important to beginn with the variable of the dataset you want to add to instead of the variable of the new joined data.

It looks like this:

let getdata = 
query { for x in allx do
join y in ally on (x.name = y.name)
join m in allm on (y.number = m.number)
join datapoints in alldatapoints on (m.accuntno = datapoints.accuntno)
where (...)
select (...)}

**Comment by tforkmann** [comment]
Sorry to bother you guys again...

I still have some trouble with finding my mistakes with creating a multi join query.

As I mentioned before Visual Studio now accepts the Query form.

But while executing the query I run into errors.

Is there a way to trace the SQL statement then I might be able to find my mistake.

@forki

**Comment by forki** [comment]
just for sake of completeness please post the concrete query code and the concrete error message. This might make things easier.

**Comment by pezipink** [comment]
Yes, more information would be useful. You can see the SQL the TP is about to execute with this debug hook (event)

`Common.QueryEvents.SqlQueryEvent |> Observable.subscribe(printfn "%s")`

**Comment by tforkmann** [comment]
Thank you!

I was able to trigger the query and I might found a bug. 

He is what I got:

F# Code:
let getfinancialdataByEnergyPlants fpiName (ezbez:string) = 
     query { for energyplant in allEnergyPlants do
             join costcentrals in allCostCentrals on (energyplant.UserFibuKostenstelle = costcentrals.UserStatKst)
             join measures in allMeasures on (costcentrals.KstStelle = measures.KstStelle)
             join datapoints in allDatapoints on (measures.Sakto = datapoints.Sakto)
             where (energyplant.Bezeichnung.Contains ezbez &&  datapoints.UserGuVPos.Contains fpiName)
             select (measures.Betrag)}
    |> Seq.tryHead

The SQLQueryEvent posted following SQL Query:

SELECT [costcentrals].[Betrag] as '[costcentrals].[Betrag]' FROM [dbo].[EnmsSich
t_KstEnergiezentrale] as [energyplant] INNER JOIN  [dbo].[EnmsSicht_Kst] as [cos
tcentrals] on [energyplant].[USER_FIBUKostenstelle] = [costcentrals].[USER_StatK
ST] INNER JOIN  [dbo].[EnmsSicht] as [measures] on [measures].[KstStelle] = [mea
sures].[KstStelle] INNER JOIN  [dbo].[EnmsSicht_Datenpunkte] as [datapoints] on
[costcentrals].[Sakto] = [datapoints].[Sakto] WHERE (([energyplant].[Bezeichnung
]LIKE @param1 AND [datapoints].[USER_GuVPos]LIKE @param2))

I looked at the statement which I wanted to generate and found an little mistake. 
The Query should look like this: 

SELECT [measures].[Betrag] as '[measures].[Betrag]' FROM [dbo].[EnmsSich
t_KstEnergiezentrale] as [energyplant] INNER JOIN  [dbo].[EnmsSicht_Kst] as [cos
tcentrals] on [energyplant].[USER_FIBUKostenstelle] = [costcentrals].[USER_StatK
ST] INNER JOIN  [dbo].[EnmsSicht] as [measures] on [measures].[KstStelle] = [mea
sures].[KstStelle] INNER JOIN  [dbo].[EnmsSicht_Datenpunkte] as [datapoints] on
[costcentrals].[Sakto] = [datapoints].[Sakto] WHERE (([energyplant].[Bezeichnung
]LIKE @param1 AND [datapoints].[USER_GuVPos]LIKE @param2))

Could you guys maybe have a look into it?

Thanks in advance!

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/12113600/0c488834-b3a4-11e5-9a16-94ad4d9beaa6.png)

**Comment by forki** [comment]
wow so it's doing

   select (costcentrals .Betrag)}

instead of

    select (measures.Betrag)}

looks like a bug to me.

**Comment by pezipink** [comment]
Before we go any further with this, exactly how `allEnergyPlants`, `allCostCentrals`, `allMeasures` and `allDatapoints`  defined? are they simply aliases to the tables from the sql data context?

**Comment by forki** [comment]
yep aliases to tables from the same data context

**Comment by pezipink** [comment]
ok this looks very odd, unless this is a recent regression I will be amazed if no one has spotted it sooner. 

Do these tables and relationships have proper foreign keys setup? If so you can please try the alternative (and simpler) syntax that does the auto-joining for you and see if it makes any difference.  It will look like this (note the `for` syntax over the special named relationship)

    query {
            for emp in dbo.Employees do
            for manager in emp.``dbo.EMPLOYEES by EMPLOYEE_ID`` do
            ....

**Comment by tforkmann** [comment]
I tried the alternative syntax as well but it didn't worked.

F# Code:
```
let getfinancialdataByEnergyPlants fpiName (ezbez:string) = 
     query { for energyplant in allEnergyPlants do
             for costcentrals in allCostCentrals do
             for measures in allMeasures do
             for datapoints in allDatapoints do
             where (energyplant.Bezeichnung.Contains ezbez &&  datapoints.UserGuVPos.Contains fpiName)
             select (measures.Betrag) }
    |> Seq.tryHead
```

Produced error:

```
System.Exception bei Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e) bei Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence) bei Microsoft.FSharp.Linq.QueryModule.clo@1735-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 ).....
```

I might implemented it wrong though...

**Comment by pezipink** [comment]
yes it is wrong.  You will for example see special properties on the `energyPlant` instance that represent the relationships to other tables (assuming foreign keys are defined in the database), they will be of type `IQueryable<something>` - see my example above or have a look in the test files for other examples

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/12116492/7bf161c2-b3ba-11e5-8eec-637e3bf68064.png)

unfortunately we don't see these properties - maybe this db doesn't have proper foreign keys defined.

 @tforkmann can you ask a db admin?

**Comment by pezipink** [comment]
you really should have those setup if you want the database to perform well with these joins!  However, the original query should have worked from what I have seen so far... very odd

**Comment by forki** [comment]
mhm. seems we are working against Views. Maybe that's an issue

**Comment by pezipink** [comment]
Views should work just fine too.  This is very strange, we will look at it.  There may be a bug somewhere in the linq compiler, it is a bit of a pain to debug and reproduce, we certainly have many tests that use multiple joins and you are not doing anything weird.  I'll mark this as a bug for now, sorry guys.

**Comment by pezipink** [comment]
I have been looking at this a bit this morning, it looks like the problem might actually be to do with the table aliases. Could you please try the query for me using the datacontext.shcema.views directly and see if it makes any difference?

**Comment by pezipink** [comment]
I cannot seem to reproduce this,  I have tried 4-5 table joins using the implicit and explicit syntax, with and without aliases, with and without the where clauses and other query elements.   It all seems to be working fine here.  

I am not using F# 4.0, that is only other difference I can think of.  (You are using sql server right?)

It would be good if you guys could try and narrow this down a bit to a minimal repro - try it without the aliases. See if you still get the incorrect sql if you remove the where clause.  Try removing all but one of the joins and see if it still generates an incorrect query.

Ross

**Comment by forki** [comment]
we started from scatch to build the query. now it works. we have no idea why ;-(
we will monitor this very closely and if it comes back we will reopen this. Thanks for your help.

**Comment by pezipink** [comment]
if you were using FSI as your test bed, weird stuff can happen with `query` and old bound values, perhaps that was the problem?

**Comment by forki** [comment]
nope it was inside of compiled project.

2016-01-07 16:40 GMT+01:00 Ross McKinlay <notifications@github.com>:

**Comment by pezipink** [comment]
Ok,wtf, be interested to hear more on this !  

Thanks guys.

**Comment by tforkmann** [comment]
Thank you!

**Comment by tforkmann** [comment]
Btw. SQLProvider is awesome its helping me a lot!

**Comment by pezipink** [comment]
Great to hear! Thanks :)

**Comment by tforkmann** [comment]
That's the query which is running fine:

let getfinancialdataByEnergyPlants fpiName (ezbez:string)= 
     query { for eplant in db.Dbo.EnmsSichtKstEnergiezentrale do
             join costcentrals in db.Dbo.EnmsSichtKst on (eplant.UserFibuKostenstelle = costcentrals.UserStatKst)
             join measures in db.Dbo.EnmsSicht on (costcentrals.KstStelle = measures.KstStelle)
             join datapoints in db.Dbo.EnmsSichtDatenpunkte on (measures.Sakto = datapoints.Sakto)
             where (eplant.Bezeichnung.Contains(ezbez) && datapoints.UserGuVPos.Contains(fpiName))
             select (measures.Betrag)}
     |> Seq.tryHead

**Comment by pezipink** [comment]
just so you know we have a customer operator that will do like for you instead of using Contains.  

where (eplant.Bezeichnung =% ezbez) && datapoints.UserGuVPos =% fpiName))

**Comment by tforkmann** [comment]
awesome! will be implemented )

**Comment by pezipink** [comment]
Wait! the operator does not put the `%` in for you since it emulates Like.  `Contains` wraps the string in '`%%%s%%` for you :)

**Comment by pezipink** [comment]
Maybe you should stick to contains :)

**Comment by tforkmann** [comment]
Yeah already noticed it ;)

Am Donnerstag, 7. Januar 2016 schrieb Ross McKinlay :

> Maybe you should stick to contains :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsprojects/SQLProvider/issues/198#issuecomment-169709026>
> .
>


-- 
Tim Forkmann
Haubachstr. 30
10585 Berlin
0151-15813418
