### ISSUE TITLE
http://fsprojects.github.io/SQLProvider/ returns 404

### ISSUE THREAD

**Issue by MarcinJuraszek** [fsprojects/SQLProvider#199]

**Comment by pezipink** [comment]
Yes we are aware, thanks, it is being looked at!

**Comment by colinbull** [comment]
Fixed..

**Comment by pezipink** [comment]
Sort of fixed, looks like the new documentation structure is a bit broken / wonky / stuff doesn't quite work.  It was not tried on github before now so I will try to look at that soon and see if I can sort it out ...
