### ISSUE TITLE
Create a Travis CI build

### ISSUE THREAD

**Issue by forki** [fsprojects/SQLProvider#20]
- [x] Create account
- [x] Create build config for master branch (see https://github.com/fsprojects/SQLProvider/pull/21)
- [x] Show build status in readme: https://travis-ci.org/fsprojects/SQLProvider
- [x] Verify build
- [x] Enable unit tests

**Comment by colinbull** [comment]
Closing this as we have abuild and tests... although they are currently a little flakey
