### ISSUE TITLE
All identifiers in postgre should be double quoted 

### ISSUE THREAD

**Issue by garfeildma** [fsprojects/SQLProvider#209]
Since PostgreSQL's  identifiers (including column names, table names) are case sensitive, the generated table name in sql text should be "public"."AspNetRoles" instead of "public.AspNetRoles".

see http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by garfeildma** [comment]
I add an PR here https://github.com/fsprojects/SQLProvider/pull/210

**Comment by Thorium** [comment]
Merge has been done. Is the problem fixed?

**Comment by garfeildma** [comment]
this was fixed
