### ISSUE TITLE
mysql field, constructor or member not defined

### ISSUE THREAD

**Issue by AngelMunoz** [fsprojects/SQLProvider#213]
Hello, I'm learning F# and when I came with the database part I figured out that I wanted to use mysql instead sql server, the thing is that It's been quite hard to get this working and I find a lack of mysql examples
I've been looking at issues with mysql but couldn't fine one that suits me, so far I got this
```fs
open System.Linq
open FSharp.Data.Sql
module Db2 =
    type mysql = SqlDataProvider<
                   ConnectionString  = "server=localhost;user=Tuna;password=Admin123;persistsecurityinfo=True;database=personsdb;allowuservariables=True",
                   DatabaseVendor = Common.DatabaseProviderTypes.MYSQL,
                   UseOptionTypes = true,
                   ResolutionPath = @"C:\Program Files (x86)\MySQL\Connector.NET 6.9\Assemblies\v4.5"
               >
    let ctx = mysql.GetDataContext()
    let GetAllUsers = 
        query {
            for user in ctx.personsdb.persons do
        }
```
but after ctx in ``for user in ctx.Personsdb.persons do`` the message
> The field, constructor or member 'personsdb' is not defined

and well I can't get past there could anyone point me in the right direction please?
by the way I'm using the latest version from nuget

**Comment by mclang** [comment]
I have the same problem.

We need a working example about how to use this with MySql!

**Comment by colinbull** [comment]
Can you try using the 'Owner' static parameter set it to a user that owns the scheme.

**Comment by mclang** [comment]
Be scheme do you mean the database or the table?

I tried some of the users defined in the MySql server but in vain... Using one produced error:
```
SequoiaDataMultiplicator.fsx(22,12): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to connect to any of the specified MySQL hosts.
```
Using e.g 'root' made it possible to connect, but I still couldn't get the data context to work. And I tried both with Visual Studio and Atom (ionide).

**Comment by colinbull** [comment]
I mean something like,

     type MySQL = SqlProvider<ConnectionString=...,DatbaseVendor=MySQL,ResolutionPath=...,Owner="Tuna">

Basically the owner parameter is what we use to filter which tables we can present in the typespace. 

Sorry for the crappy replies on my phone, if this still doesn't work let me know I'll reply with a full example tomorrow.

**Comment by mclang** [comment]
Yes, that was what I tried.
I didn't change the user and password in the connection string but used that named 'Owner' parameter of SqlDataProvider.

**Comment by mclang** [comment]
Can firewall be the reason?
I tried disabling my BitDefender firewall module, but I'm not sure if it stops completely.

**Comment by colinbull** [comment]
Possibly. Although do you actually get any dot completion after context. Normally if you can't connect to the DB, you'll get a red squiggly under the type definition. With the error 'cannot connect to DB'. Sorry, didn't get a chance to investigate this further today, hopefully I'll get some time this weekend.

**Comment by AngelMunoz** [comment]
Hello! sorry for the late response I'm quite lost on what should I try, could you explain a little bit more to me please?

**Comment by mclang** [comment]
When using Atom, I don't get any dot completion after 'cxt.'

When trying same code with Visual Studio 2015 CE I got some dot completions, e.g 'ctx.GetConnection()' but nothing from my database. I can connect to the remote database using HeidiSQL, so the remote site is not the problem.

**Comment by mclang** [comment]
AngelMunoz, I think you should try to define your SqlDataProvider with 'owner' like this:
```
type mysql = SqlDataProvider<
                   ConnectionString  = "server=localhost;user=Tuna;password=Admin123; ... ",
                   DatabaseVendor = Common.DatabaseProviderTypes.MYSQL,
                   UseOptionTypes = true,
                   ResolutionPath = @"<path-to_MySql.Data.dll_folder>",
                   Owner = "Tuna"
               >
let ctx = mysql.GetDataContext()
```
Is there any more information that I could provide to help solve this issue for both of us?

**Comment by nwolverson** [comment]
I was having the same issue, but it seems that `Owner` actually means the database name

**Comment by mclang** [comment]
Thanks for the tip!

Now I can see tables inside my database using SqlDataProvider data context. But I though that `Owner` should be the database creator or some of that sort... So this seems a bug, right?

**Comment by colinbull** [comment]
It is because it is a bit overloaded. It was originally introduced to support Oracle. However it has found usages in other, providers as well. Your correct, thou, the name is confusing, maybe 'Schema' is better?

**Comment by nwolverson** [comment]
That might be better; but either way I guess the vendor-specific documentation page needs an update  (I can try to make a PR later)

**Comment by Thorium** [comment]
Do we have something to be fixed here, or is this ok? Like error reporting on empty contexts that "did you mean..."?

`Owner` and `CaseSensitivityChange` are two suspects if the ctx seems to be empty.

**Comment by Thorium** [comment]
Now there are working examples in the documentation and the error reporting is better than earlier.
E.g. in this case `mysql.PossibleError` property having tooltip to suggest what you should improve.

So this should be fine.
