### ISSUE TITLE
Unsupported expression. Ensure all server-side objects appear on the left hand side of predicates.

### ISSUE THREAD

**Issue by forki** [fsprojects/SQLProvider#215]
This dowsn't work:

    let getPlotDataByKst measureName (kst:string) =
        query { for measures in db.Dbo.EnmsSicht do
                where (kst = measures.KstStelle && measures.Saktobez.Contains measureName )
                select (measures.VuPeriode, measures.SumMenge)}
        |> Seq.toList

but this does:

    let getPlotDataByKst measureName (kst:string) =
        query { for measures in db.Dbo.EnmsSicht do
                where (measures.KstStelle = kst && measures.Saktobez.Contains measureName )
                select (measures.VuPeriode, measures.SumMenge)}
        |> Seq.toList

so `measures.KstStelle = kst` is correct syntax. 
It's easy for us to change, but is it possible to let the provider do it?
Or generate a compiler error?

/cc @tforkmann

**Comment by pezipink** [comment]
it's a big change to support the expressions in both directions, it just needs doing. It an artificial limitation. Unfortunately we can't detect this until runtime since we don't get passed the trees until then :(

**Comment by Thorium** [comment]
Old issue, but just a comment, the provider has been supporting both directions already for years now.
