### ISSUE TITLE
Compare DateTimes

### ISSUE THREAD

**Issue by archaeron** [fsprojects/SQLProvider#217]
I'm using the MySQL Provider and trying to compare dates.

When I execute this:

```f#
let getDatesAt (locationId : String) (startDate : DateTime) (endDate : DateTime) =
    query
        {
            for date in ctx.Main.Date do
            join location in ctx.Main.Location on (date.Location = location.Id)
            where (location.Id = locationId && date.Date >= startDate && date.Date < endDate)
            select location
        }
    |> Seq.toList
```

and I log the generated SQL with
```
FSharp.Data.Sql.Common.QueryEvents.SqlQueryEvent |> Event.add (printfn "Executing SQL: %s")
```

I get this:

```sql
SELECT
  `location`.`id`              AS '`location`.`id`',
  `location`.`city`            AS '`location`.`city`',
  `location`.`location`        AS '`location`.`location`',
  `location`.`description`     AS '`location`.`description`'
FROM heroku_main.date AS `date` INNER JOIN `heroku_main`.`location` AS `location`
    ON `date`.`location` = `location`.`id`
WHERE ((`date`.`date` < @param1 AND (`location`.`id` = @param2 AND `date`.`date` >= @param3)))
```

The query looks pretty good, but returns too many results.
When I take that query and execute it manually with the correct params it should use it does what I expect.

Am I comparing DateTimes the wrong way?
Is there a way to log the exact query that is being executed? (with the params).

**Comment by archaeron** [comment]
I tested it on a mac and a linux machine. Both return too few results.
And I tested the same thing on another windows Pc and it returns too many results as the first one. Seems to be pretty constant.

**Comment by Thorium** [comment]
There is discussion about this in #194

**Comment by archaeron** [comment]
thanks for the info. looks like exactly that.
since the other issue is closed I'll leave this open, since at least the version of MySql.Data will
need to be updated for this to be fixed.

**Comment by Thorium** [comment]
This should be now fixed.

**Comment by archaeron** [comment]
thanks :)
