### ISSUE TITLE
filter a list of Strings

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/SQLProvider#224]
Hi there,

I tried to filter a list of strings but somehow I didn't got it working.

I got following error message:
Microsoft.FSharp.Compiler.FSharpErrorSeverity: . None of the types 'string, string []' support the operator '|=|'. 

Do you have an idea what I could have done wrong?

Here the code:
`let list = [|"Sales";"IT"|]`
`let getEZperKstnames () =
    query { for energyplant in db.Dbo.EnmsSichtKstEnergiezentrale do
            sortBy energyplant.Bezeichnung
            where (energyplant.UserStatKst |=| list)
            select energyplant.Bezeichnung}
    |> Seq.toArray`

Thank you in advance!

**Comment by colinbull** [comment]
Hummm, can you try the following to see if the problem persists. 

```
let getEZperKstnames () = query { for energyplant in db.Dbo.EnmsSichtKstEnergiezentrale do sortBy energyplant.Bezeichnung where (energyplant.UserStatKst |=| [|"Sales";"IT"|]) select energyplant.Bezeichnung} |> Seq.toArray
```

**Comment by tforkmann** [comment]
Hi there,

sorry for the late response.

I tried it out like this:
`let getEZperKstnames () = 
    query { for energyplant in db.Dbo.EnmsSichtKstEnergiezentrale do
            sortBy energyplant.Bezeichnung
            where (energyplant.UserStatKst |=| [|"Sales";"IT"|]) 
            select energyplant.Bezeichnung } 
    |> Seq.toArray`
and i got the same error message:

Microsoft.FSharp.Compiler.FSharpErrorSeverity: . None of the types 'string, string []' support the operator '|=|'.

Do you have any idea how to solve this?

**Comment by colinbull** [comment]
Not really, I'm guessing, but we have samples of this `|=|` operator [working](https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Tests/scripts/OracleTests.fsx#L44). Can you try doing the where as the first clause then the sort by last?  

```
let getEZperKstnames () = query { 
      for energyplant in db.Dbo.EnmsSichtKstEnergiezentrale do 
      where (energyplant.UserStatKst |=| [|"Sales";"IT"|]) 
      select energyplant.Bezeichnung 
      sortBy energyplant.Bezeichnung
} |> Seq.toArray
```

Let me know how you get on. If it still doesn't work then I suspect this a regression that has been introduced.

**Comment by tforkmann** [comment]
Thank you!

Now the compiler responses with that message:

Microsoft.FSharp.Compiler.FSharpErrorSeverity: . This expression was expected to have type string but here has type unit. 

I also tried itwithout the sortBy-clause:
`let getEZperKstnames () = 
    query { 
      for energyplant in db.Dbo.EnmsSichtKstEnergiezentrale do 
      where (energyplant.UserStatKst |=| [|"Sales";"IT"|])
      select energyplant.Bezeichnung 
      } 
   |> Seq.toArray`

Then I get the same message like before....

Its not important. I just wanted to try it out because I believe it's a nice feature. 
Now I'm just wondering what I'm doing wrong.

**Comment by colinbull** [comment]
Ill give it ago when I get a chance, what DB provider is it? Oracle?

**Comment by tforkmann** [comment]
Thanks! MS Server

**Comment by Thorium** [comment]
> Microsoft.FSharp.Compiler.FSharpErrorSeverity: . None of the types 'string, string []' support the operator '|=|'.

This usually means you haven't open the namespace of `FSharp.Data.Sql`.

**Comment by tforkmann** [comment]
Thanks Thorium.

Tested it again with  `FSharp.Data.Sql`. It works now.

Closing it now!
