### ISSUE TITLE
Issue updating records in a table with a composite primary key

### ISSUE THREAD

**Issue by m-fitzpatrick** [fsprojects/SQLProvider#225]
Using SQLExpress, I am trying to update records in a table with a composite primary key. One key is a uniqueidentifier, the other is an int. I can record the SQL being generated on the update and only one key is being qualified in the update statement (ConsumerId). Here is my update code

`
let SaveConsumerRegion (consRegion: ConsumerRegion.T, consumerId: System.Guid) =
        try
            let existingRecord =
                query {
                    for cr in ctx.Dbo.ConsumerRegion do
                    where (cr.RegionId = consRegion.RegionId && cr.ConsumerId = consumerId)
                    select cr
                } |> Seq.tryHead

            let consumerRegionToUpdate = 
                match existingRecord with
                | Some cr -> cr
                | None -> let newRecord = ctx.Dbo.ConsumerRegion.Create()
                          newRecord.RegionId <- consRegion.RegionId
                          newRecord.ConsumerId <- consumerId
                          newRecord
            
            consumerRegionToUpdate.StartDate <- consRegion.EnrollmentDate
            consumerRegionToUpdate.SubAccountId <- consRegion.SubAccount
            consumerRegionToUpdate.TermDate <- consRegion.TermDate
            
            ctx.SubmitUpdates()

        with
        | _ -> ctx.ClearUpdates() |> ignore
               reraise()
`

Is this a known issue, or am I missing something?

thanks

**Comment by colinbull** [comment]
This looks like a bug to me. Can you send me the SQL that is being generated. Feel free to send it via e-mail, if you don't want it public.

**Comment by m-fitzpatrick** [comment]
Here is the generated SQL:
UPDATE dbo.ConsumerRegion SET TermDate = @param0,SubAccountId = @param1,StartDate = @param2 WHERE ConsumerId = @pk;

As you can see, only one of the keys is used to filter the update statement. 
FYI, I have addressed this problem by using a surrogate key. I don't feel like that's necessarily the best solution, but I needed to move forward.
Thanks 
Mike
Date: Tue, 1 Mar 2016 00:15:14 -0800

**Comment by pezipink** [comment]
Hello, at the moment we do not support composite keys for the CRUD features (as far as I recall!).  This would be a nice one for someone to pick up!

**Comment by Thorium** [comment]
Someone just picked up and fixed. PR #315
