### ISSUE TITLE
MySQL Date Column insert

### ISSUE THREAD

**Issue by nicholas-peterson** [fsprojects/SQLProvider#228]
SQLProvider identifies mysql **DATE** columns as a Datetime and throws exception on insert (probablt update as well).

I believe the Connector for .Net for MySQL is the source of identifying these columns as Datetime, because the query I saw in the source code obviously returns Date for the database column when ran against mysql.

I'm wondering if an explicit condition for date columns will need to be made?

example code:

```
let mutable row = ctx.Schemaname.TableName.Create()
row.ProductId <- Some prd.ProductId
row.EFromDate <- Some (DateTime(1998, 7, 24))
row.EToDate <- Some (DateTime(1998, 7, 24))
ctx.SubmitUpdates()`  //exception here. Without the date fields it works fine.
```

**Comment by Thorium** [comment]
I've had similar problems. As a workaround I have used 
`row.SetColumn("EFromDate", DateTime(1998, 7, 24))` 
which seems to work.

**Comment by nicholas-peterson** [comment]
Yes I noticed that method and got it working using a similar pattern, the same seems true of other datatypes, like bit.

**Comment by Thorium** [comment]
Ok, good.

Have you also found a solution to date comparison when doing select? :-)

**Comment by nicholas-peterson** [comment]
No unfortunately :( , I really need to up my F# game to the level of working understanding of type provider development. That way I can help resolve these.

**Comment by Thorium** [comment]
This should be ok now.
