### ISSUE TITLE
CaseSensitivityChange SqlDataProvider Parameter

### ISSUE THREAD

**Issue by xenocons** [fsprojects/SQLProvider#229]
Hello,

This parameter seems to do nothing in relation to table names, when set to `Common.CaseSensitivityChange.ORIGINAL` buildTableName (https://github.com/fsprojects/SQLProvider/blob/bc21b9240c449bca9c20184cde61d43080eaa051/src/SQLProvider/Utils.fs#L154) still converts table names to PascalCase instead of keeping originals, is this indended?

**Comment by Thorium** [comment]
No it's not indended... I think this worked before Colin's mega-merge of column-name refactoring. But I still prefer this new version with non-``-tablenames.

**Comment by Thorium** [comment]
`Common.CaseSensitivityChange.ORIGINAL` was meant to help to deal with case sensitive databases (when the case sensitivity setting is set on) on different environments (.NET and Mono). It's function is not to affect source code as long as single F# code will always work.
