### ISSUE TITLE
DateTime is null

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/SQLProvider#232]
Hi there,

probably an easy question for you guys.

In the where clause I want to set filter for an DateTime field which needs to be `null`.

I tried to filter like this:

`let requiredplants() =
    query { for plants in db.Dbo.EnmsSichtKstErzeuger
                where ( plants.DateField.IsNull)
                select plants.name 
               }`

and I also tried:

`let requiredplants() =
    query { for plants in db.Dbo.EnmsSichtKstErzeuger
                where ( plants.DateField = null)
                select plants.name 
               }`

Do you have an idea how to solve this?

Thanks in advance,

Tim

**Comment by Thorium** [comment]
Have you tried:
`SqlDataProvider<..., UseOptionTypes=true, ...>`
and then
`where (plants.DateField.IsNone)`
?

**Comment by tforkmann** [comment]
Thank you! Got it working!

Had to completely adjust my sql query structure but now it works fine!

Closing it now!
