### ISSUE TITLE
Unable to resolve assemblies. One of Npgsql.dll must exist in the paths

### ISSUE THREAD

**Issue by cechovsky** [fsprojects/SQLProvider#237]
### Description

When I try to connect to Posgresql I get following error.

'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to resolve assemblies. One of Npgsql.dll must exist in the paths: 

### Repro steps

I added Npgsql.dll via Nuget to my solution.

I use this code to init my SqlDataProvider

`type sql = SqlDataProvider<
              ConnectionString = "Server=localhost;Database=postgres;User Id=postgres;Password=password",
              DatabaseVendor = Common.DatabaseProviderTypes.POSTGRESQL,
              ResolutionPath = "{my-solution-path}\packages\Npgsql.3.0.5\lib\net45",
              IndividualsAmount = 1000,
              UseOptionTypes = true>`

In folder {my-solution-path}\packages\Npgsql.3.0.5\lib\net45 there is Npgsql.dll

Any idea what could the problem?

In the module PostgreSQL
https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.Postgresql.fs

there is `let mutable resolutionPath = String.Empty`

Is it correct?

**Comment by pierroz127** [comment]
I get exactly the same error with MySQL.

**Comment by cechovsky** [comment]
It is unbelievable, but I resolved it with double-backslashes. Like this

C:\\{my-solution-path}\\packages\\Npgsql.3.0.5\\lib\\net45

The error was sometimes the same despite of changes in the code, but after Visual Studio restart, error disappeared. 

I hope problems will be solved soon.

**Comment by colinbull** [comment]
As a note you can also use `@"C:\{my-solution-path}\packages\Npgsql.3.0.5\lib\net45"` instead of double quoting the backslashes

**Comment by vilinski** [comment]
the same problem with Oracle, tried anything with visual studio code

**Comment by cechovsky** [comment]
Even if you use double backslashes? Sometimes it looks like Visual Studio is not refreshed or something like this. When I close file and open again it possible could help.

**Comment by colinbull** [comment]
@vilinski is this with the managed oracle driver?

**Comment by vilinski** [comment]
@colinbull yes, Oracle.ManagedDataAccess package
@cechovsky used '@', should be the same. 
Got errors like "invalid character in path" or "no assemblies in path". Though loading assembly with this path works. 
Closed all VS, VSCode, fsi processes and tried again. Now its "Loading..." for a while. Probably due  to huge number of dbschemas and tables?
After that an error :
`SqlProvider.fsx(3,14): error FS3021: Unexpected exception from provided type 'FSharp.Data.Sql.SqlDataProvider,DatabaseVendor="4",ConnectionString="myconnectionstring",ResolutionPath="c:\\\\Some\\\\valid\\\\path\\\\to\\\\packages\\\\Oracle.ManagedDataAccess\\\\lib\\\\net40"+dataContext' member 'GetMethods': The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Column 'PACKAGE_NAME' doesn't belong to table Functions.`

create an issue?

**Comment by colinbull** [comment]
Yep, this isn't the same thing, can you create a separate issue.. This looks like something related to your oracle schema..

**Comment by Thorium** [comment]
I think the error reporting for this is now better, to tell the actual problem.
Is this still an issue?

**Comment by Thorium** [comment]
This issue had 2 separate issues: 
1) Resolution path not working. Should be ok now. 
2) Package_name, duplicate to #255 which is fixed.
