### ISSUE TITLE
Postgresql and schema selection support

### ISSUE THREAD

**Issue by cechovsky** [fsprojects/SQLProvider#240]
### Description

When I connect to postgresql with following code

````
[<Literal>]
let connString = @"Server=###;Database=###;Username=###;Password=###"
[<Literal>]
let resPath = @"C:\\Development\\MyProject\\packages\\Npgsql.3.0.5\\lib\\net45"
let dbVendor = Common.DatabaseProviderTypes.POSTGRESQL
let indivAmount = 1000
let useOptTypes  = true

type sql = SqlDataProvider< 
              ConnectionString = connString,
              DatabaseVendor = Common.DatabaseProviderTypes.POSTGRESQL,
              ResolutionPath = resPath,
              IndividualsAmount = 1000,
              UseOptionTypes = true >
let ctx = sql.GetDataContext()
````

and I want to work with concrete schema e.g. scheme1 it is not possible. 

My context ctx offers me only scheme public, like `ctx.Public` and I'm not able to access other schemes in my db, somthing like `ctx.Scheme1`

I tried to set scheme in connection string according to npgsql documentation
http://www.npgsql.org/doc/connection-string-parameters.html

let connString = @"Server=###;Database=###;**search_path=scheme1**;Username=###;Password=###"

but this solution doesn't work.

Any idea how to solve this issue?

**Comment by colinbull** [comment]
There is another literal, 'Owner' that should allow you to specify which schema to get the information from. Providing of course you actually have access.. 

     type sql = SqlDataProvider< 
                   ConnectionString = connString,
                   DatabaseVendor = Common.DatabaseProviderTypes.POSTGRESQL,
                   ResolutionPath = resPath,
                   IndividualsAmount = 1000,
                   UseOptionTypes = true,
                   Owner="scheme1" >
     let ctx = sql.GetDataContext()

**Comment by cechovsky** [comment]
thanks, this solved my issue

**Comment by colinbull** [comment]
No, problems.

**Comment by cechovsky** [comment]
But I have another question about PostgreSQL special types like hstore and postgis data types. SQLprovider doesn't support them and I can't access them. But I'll write this to another issue.
