### ISSUE TITLE
Allow Paket 3.0 debugging

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#248]
To use this repo source code directly in your project's references with Paket 3.0 do the following:

1. Modify your projects (the ones where you use SQLProvider) paket.dependencies file to contain:

```
nuget SQLProvider
git https://github.com/fsprojects/SQLProvider.git master build:"build.cmd PackNuGet", Packages: /bin/, bin OS:windows
git https://github.com/fsprojects/SQLProvider.git master build:"build.sh PackNuGet", Packages: /bin/, OS:mono
```

2. Fetch Paket 3.0 release with:
`.paket\paket.bootstrapper.exe prerelease`

3. Run install:
`.paket\paket.exe install`

...and now you are running the latest version!

**Comment by Thorium** [comment]
This is now working!

**Comment by forki** [comment]
![devops](https://cloud.githubusercontent.com/assets/57396/14706212/9f78cf2a-07bd-11e6-924f-faa72e22b6a6.gif)
