### ISSUE TITLE
Problems (and workarounds) with inserting Access data

### ISSUE THREAD

**Issue by jimfoye** [fsprojects/SQLProvider#252]
I encountered several problems when trying to insert data into Access, here's a list of the problems and what I did to solve each one.

**Reserved words**

This is the same problem I had with querying data before (now fixed). Inserting

`|> List.map (fun (name, value) -> (sprintf "[%s]" name, value))`

into the pipeline in createInsertCommand() worked for me.  (I suggest a unit test for all scenarios and all supported databases include a table with a key word as name for the table and one column. For example, in MS Access, a table called 'Year' with a column 'Year').

**Date/time**

See #191, this was a problem for me as the fix (hack?) for that is not called during the flow for inserting data. I think the root problem is that Access time values cannot include milliseconds (the exception that gets thrown here by OleDb is terrible). I got around this by simply truncating milliseconds before inserts.

```
// MS Access doesn't like milliseconds, avoid 
// 'OleDbException (0x80040E07): Data type mismatch in criteria expression'
let truncateMs (dt:DateTime) = 
    DateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, dt.Kind)
...
file.UploadDate <- truncateMs(DateTime.Now)

```
Personally, I would not be crazy about the type provider "fixing" this problem by silently truncating the data on my behalf. I suggest adding a "Troubleshooting" section in the docs with example code similar to the above to help users deal with this.

**IDENTITY Columns**

Retrieving values generated for IDENTITY columns is not implemented. I modified ProcessUpdates() to have the second, separate command (required by Access) to retrieve the value.

```
match pkLookup.TryGetValue(e.Table.FullName) with
| true, pk ->
    match e.GetColumnOption pk with
    | Some _ -> () // if the primary key exists, do nothing
                    // this is because non-identity columns will have been set 
                    // manually and in that case scope_identity would bring back 0 "" or whatever
    | None ->  
        // see http://stackoverflow.com/questions/26868911/select-identity-in-access-always-returning-0
        let cmd2 = OleDbCommand("SELECT @@IDENTITY", con :?> OleDbConnection)
        cmd2.Transaction <- trnsx :?> OleDbTransaction
        let id = cmd2.ExecuteScalar()
        // possibly need a null check here
        e.SetColumnSilent(pkLookup.[e.Table.FullName], id)
| _ -> ()

```

**Multi-column primary keys**

I realize this is not supported yet, but I really needed this. I found that by removing pk lookups in the insert code (these calls are currently used for anything), I was able to get my inserts to work.

I'm not sure how you will want to handle all of these issues. All my changes are in one file, so I'll just attach that here - feel free to use any of my changes, or I can submit pull requests, just tell me which of them you want.

**Exception handling**

The type provider eats exceptions. I don't think this is desirable behavior - any plans to change it? I had to set a breakpoint in library source to really get a handle on what was going on. Normally I would expect the data access layer to bubble up exceptions, and it's a given that I would need to wrap my own code for db calls with try/catch blocks and handle appropriately.

[Providers.MSAccess.zip](https://github.com/fsprojects/SQLProvider/files/233258/Providers.MSAccess.zip)

Thanks,
Jim

**Comment by Thorium** [comment]
We would accept changes rather as pull requests than zip-files.
I went through the source and it seems very similar to the current implementation.
So has it already been taken in as a pull request or can you do the corresponding changes to the current version and send it as a PR?

**Comment by Thorium** [comment]
Multi-column primary keys are not supported, there is a separate issue for that. I don't know about eating exceptions, haven't noticed that. I think other issues are now fixed. If there is still an open issues, please open a separate bug for that.
