### ISSUE TITLE
Oracle provider error: Column 'PACKAGE_NAME' doesn't belong to table Functions.

### ISSUE THREAD

**Issue by vilinski** [fsprojects/SQLProvider#255]
### Description

Subject error by using oracle type provider, probably due limited read rights

### Repro steps

1. Create an empty folder
2. Open it in VS Code
3. Paket init; Paket add NuGet SqlProvider
4. Create fsx file referencing the dll and defining some type with Oracle type provider
4. The oracle connection string for big instance with limited read/write rights

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

`SqlProvider.fsx(3,14): error FS3021: Unexpected exception from provided type 'FSharp.Data.Sql.SqlDataProvider,DatabaseVendor="4",ConnectionString="myconnectionstring",ResolutionPath="c:\\\\Some\\\\valid\\\\path\\\\to\\\\packages\\\\Oracle.ManagedDataAccess\\\\lib\\\\net40"+dataContext' member 'GetMethods': The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Column 'PACKAGE_NAME' doesn't belong to table Functions.`

### Known workarounds

No known workarounds

### Related information 

* Operating system Windows 7 Enterprise
* .NET Runtime 4.5

**Comment by mofus** [comment]
Has anyone found a workaround for this?

**Comment by pezipink** [comment]
one for you @colinbull  ?

**Comment by Thorium** [comment]
Quite optimistic for push to close the bug directly. :-)

**Comment by Thorium** [comment]
Can you test this with new version please?

**Comment by mofus** [comment]
I just tested this version and it works for me. Thanks for the great work!

**Comment by Thorium** [comment]
Great!

**Comment by vilinski** [comment]
Also tested and can confirm - the exception is away. Thank you!
Unfortunately it is still quite useless for me because of such crazy delays in the intellisence and compilation. The number of tables and columns in our corp server is just sick. Wonder whether there are some ways for improvement. May be table name filter like in "Oracle SQL Developer"

**Comment by colinbull** [comment]
Humm, we do have a lazy loading strategy for SQL server, maybe the same
thing could be employed for Oracle.. I don't really remember how the oracle
side works thou.

**Comment by pezipink** [comment]
In general the provider is supposed just load the names of the tables/views, then the columns of a table when you access it. What was killing us in the past was the sprocs, but I thought we fixed the lazyness of those? I don't remember how Oracle works either !

If even the names of tables is too much data, we could use a direct filter strategy via a static parameter, or optionally group the tables by their first letter or a similar strategy.

**Comment by vilinski** [comment]
There are thousands of tables even per first letter.
I have just tried to insert a table name prefix filter direct into [getTables](https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.Oracle.fs#L184) function, which should result into 4 tables with following results:
- creating a type in fsi - 7 minutes
- get a data context from it - 1 minute
- intellisence to get available members of data context instance (schema name, etc.) - 5 minutes
- get available members of schema member (table names) - another 2 minutes. I have got here too many member. May be fsi still took a vanilla dll without changes...

I think I better give up :)

**Comment by pezipink** [comment]
Yes that `getTables` still goes and gets all the names since it uses the inbuilt schema stuff that ado,net gives us.  You would have to change it to query the infromation_schema more directly and filter server side.  Sounds like a fun database..... !

**Comment by Thorium** [comment]
Bit off-topic but... VS seems to use multiple threads (which you can see if you open another VS, attach debugger to the development environment, pause the process and see Threads window).

Now, most dictionaries are already replaced with ConcurrentDictionary. It's way better than using any own locking mechanism in cases where you remove or add single key. That's good, but there is still code that uses dictionaries like this:

```
match myDictionary.TryGetValue key with
| true,data -> data
| _ -> 
   let result = (* make some queries *)
   myDictionary.GetOrAdd(key,result)
```
   
While this is ok, it may lead to execution of queries multiple times. There is a light-weight write-locking-mechanism inside ConcurrentDictionary (if any locking can be considered as "light-weight") and it would be used e.g. like this:

```
myDictionary.GetOrAdd(key, fun name ->
   let result = (* make some queries *)
   result)
```

The functionality is the same, but now the queries are inside a lock and executed only once. However, the queries should produce similar results so it shouldn't be so dangerous executing them by accident if the result size is not huge.

However, Oracle provider is having some custom solutions different from other providers, like 
`let mutable primaryKeyCache : IDictionary<string,PrimaryKey> = null`, I don't know why as I don't use Oracle.

**Comment by colinbull** [comment]
Pure laziness, on my behalf, for which I apologise. You are exactly correct
thou these should be changed as you say in your above comments
