### ISSUE TITLE
"System.Byte[]" is inserted as the value of BLOB (MySQL)

### ISSUE THREAD

**Issue by vain0** [fsprojects/SQLProvider#256]
### Repro steps
1. Create a table containing a field of BLOB type. (MySQL)
2. Insert a row into the table with SQLProvider.

This is an example.

```fsharp
open System.IO
open FSharp.Data.Sql

type sql =
  SqlDataProvider<
      Common.DatabaseProviderTypes.MYSQL
    , ConnectionString  = "Data Source=localhost; Port=3306; user=root; password=;"
    , ResolutionPath    = @"C:/Program Files (x86)/MySQL/MySQL Connector Net 6.9.8/Assemblies/v4.5"
    , UseOptionTypes    = true
    , Owner             = "test"
    >

[<EntryPoint>]
let main argv =
  let ctx = sql.GetDataContext()
  let db = ctx.Test
  let item = db.items.Create()
  item.Content <- Array.create 100 (byte 'a')
  ctx.SubmitUpdates()
  0
```

### Expected behavior

The assigned binary data (byte[]) should be inserted as the value of the field.

### Actual behavior

"System.Byte[]" (13byte) is inserted.

### Related information 
* Windows 10
* SQLProvider 1.0 (from NuGet)
* F#4.0
* .NET framework 4.5

**Comment by Thorium** [comment]
Tried and yes this still exists.

**Comment by Thorium** [comment]
Hmm, debugged a bit: It creates correct SQL clause `INSERT INTO test.Test (items) VALUES (@param0); SELECT LAST_INSERT_ID();` into `cmd:IDBCommand`, and adds the binary array to a parameter with 
`values |> Array.iter (cmd.Parameters.Add >> ignore)` when it's still correct binary. 

So this could be MySql.Data.dll problem with .Parameters.Add.

**Comment by vain0** [comment]
Thanks for your work.

Now I should try to insert a blob data by using only MySqlData.dll & Parameters. My script is the following, which succeeded to insert actual value of blob type.

```fsharp
open System.Configuration
open System.Data
open MySql.Data.MySqlClient

let connectionString =
  let b =
    MySqlConnectionStringBuilder
      ( UserID = "root"
      , Password = ""
      , Server = "localhost"
      , Database = "test"
      )
  in b.ConnectionString

let withDb f =
  use connection = new MySqlConnection(connectionString)
  try
    connection.Open()
    f connection
  finally
    connection.Close()

let insert connection =
  let value = Array.create 100 (byte 'a')
  let sql = "INSERT INTO tests (data) VALUES (@data)"
  let command = new MySqlCommand(sql, connection)
  command.Parameters.AddWithValue("data", value) |> ignore
  command.ExecuteNonQuery() |> ignore

[<EntryPoint>]
let main argv =
  withDb insert
  0
```

**Comment by vain0** [comment]
I revised my script to use `Parameters.Add` rather than `Parameters.AddWithValue` just in case. The result didn't changed (of course).

```fsharp
open System.Configuration
open System.Data
open MySql.Data.MySqlClient

let connectionString =
  let b =
    MySqlConnectionStringBuilder
      ( UserID = "root"
      , Password = ""
      , Server = "localhost"
      , Database = "test"
      )
  in b.ConnectionString

let withDb f =
  use connection = new MySqlConnection(connectionString)
  try
    connection.Open()
    f connection
  finally
    connection.Close()

let insert connection =
  let value = Array.create 100 (byte 'a')
  let sql = "INSERT INTO tests (data) VALUES (@param0)"
  let command = new MySqlCommand(sql, connection)
  let param = new MySqlParameter("param0", value)
  command.Parameters.Add(param) |> ignore
  command.ExecuteNonQuery() |> ignore

[<EntryPoint>]
let main argv =
  withDb insert
  0
```

**Comment by JohnDoeKyrgyz** [comment]
This issue is occuring because the insert and update statements are not setting the DBType for each parameter. I submitted pull request #278 to fix a similar issue for the SQLite provider. Someone could follow this pattern to apply this fix for MySql.

**Comment by vain0** [comment]
Thank you.
