### ISSUE TITLE
Create is quite un-usable. Hard to write and error messages are not clear.

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#267]
I try to CRUD Create table item that has 20 columns.
`Create [| "MyColumnA", "a" |> box; "MyColumnB", "b" |> box;  |]` can fail runtime if the columns are wrong.

`Create("a", "b", "c", ...)` is a problem if table columns are changed, I don't get notifications that actually values start to go to the wrong columns, if the data types match.

`Create("a", MyColumnB="b", MyColumnC="c", ...)` is best bet, but is really painful to write (as autocomplete won't help anything).

And then, if you have a typo or one column missing, you will get just an error message of "No overloads match for method 'Create'. The available overloads are shown below (or in the Error List window)." which is really slow to check totally manually that what is not matching or is having a wrong type.

**Comment by Thorium** [comment]
With this commit there comes this strange but nice method of adding just the items but all the columns are in the method name, so your build breaks if the columns changes.
The method is: 
```
.``Create(...)``(params)
```
For example:

```
dbContext.MyDatabase.Message.
    ``Create(FromId, MessageStatus, MessageText, MessageType, SentDateTime, Title, ToId)``(
               123u, "Unread",      "Hello",     "Note",      DateTime.Now, "Hello", 125u
    )

```

**Comment by jackmott** [comment]
That is fascinating.  Is there a limit on how long the method name can be?

**Comment by Thorium** [comment]
If there is, it's very long, I have have tried over 300 character method names. But I didn't include line changes to method name as they did look very weird.

**Comment by pezipink** [comment]
Nice touch :)
