### ISSUE TITLE
Deleted entities remain in pendingChanges which breaks next SubmitUpdates call

### ISSUE THREAD

**Issue by janno-p** [fsprojects/SQLProvider#274]
### Description

I think that 78abff37304847bea479de301a2b7537862c1ff1 broke library in a way that when pending changes contain deleted entities, all ctx.SubmitUpdates() calls (except the first) fail.

### Repro steps

1. delete entity
2. submit updates
3. submit updates

### Expected behavior

Continuous submit updates do not cause any exceptions.

### Actual behavior

Second SubmitUpdates call results with exception:

```
System.Exception: Error - you cannot delete an entity that does not have a primary key.
```

### Notes

After inspecting it a little bit, it seems, that previously mentioned commit causes entities which have _State value other than Unchanged to remain in pendingChanges dictionary (previously everything got removed). Looking at implementation of ProcessUpdates of provider implementations, deleted entities for some reason remain in Deleted state, so they remain in pendingChanges but this time, their primary id is removed, so next call to SubmitUpdates cannot succeed.

**Comment by Thorium** [comment]
Ok, the reason to not clear all was to easier find exceptions as there is also `ClearPendingChanges()`.
The reason deleted are not unchanged is probably because they are not coming back so not to mess those. Delete method returns the deleted entity. I made a quick fix for this, although it may be better to have some "delete done" -status.

**Comment by janno-p** [comment]
Issue is resolved.

**Comment by Thorium** [comment]
I still made a change that you have different Delete and Deleted status.
Previous version was in danger that if you happen to run 2 SubmitUpdates() in different threads to the same context, you can delete items from pending changes that were not deleted from the database.
Anyway I also added a lock to SubmitUpdates() as with the current implementation it's not thread-safe to keep database and pending-changes dictionaries in sync.
