### ISSUE TITLE
duplicated key when GetDataContext async invocation

### ISSUE THREAD

**Issue by ingted** [fsprojects/SQLProvider#279]
### Description

When trying to invoke 
async {
    .......
    let context = sql.GetDataContext() 
    .......
}
in main method and
declare 
type sql =
    SqlDataProvider<
          ConnectionString = connStr,
          DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER,
          IndividualsAmount = 1000,
          UseOptionTypes = true >

before main method

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

SqlRuntime.DataContext.fs
has 
providerCache.Add(typeName,prov)

it should be ok when static GetDataContext async invoked concurrently

(or it just throw an duplicated key exception)

### Actual behavior

it just throw an duplicated key exception

### Known workarounds

I change providerCache.Add(typeName,prov) with a key existence match

match providerCache.ContainsKey(typeName) with
 | false -> providerCache.Add(typeName,prov)
 | true -> ()

everything is ok now

### Related information 

* Operating system
Server 2012 R2
* Branch
master
* .NET Runtime, CoreCLR or Mono Version
4.6.1

**Comment by Thorium** [comment]
I think this is again not threadsafe to use `static let providerCache = Dictionary<string,ISqlProvider>()` and should use `static let providerCache = ConcurrentDictionary<string,ISqlProvider>()` with:

```
    let provider =
        providerCache.GetOrAdd(typeName,
            fun typeName -> 
                let prov = ProviderBuilder.createProvider providerType resolutionPath referencedAssemblies runtimeAssembly owner
                use con = prov.CreateConnection(connectionString)
                con.Open()
                // create type mappings and also trigger the table info read so the provider has
                // the minimum base set of data available
                prov.CreateTypeMappings(con)
                prov.GetTables(con,caseSensitivity) |> ignore
                if (providerType.GetType() <> typeof<Providers.MSAccessProvider>) then con.Close()
                prov)
```

**Comment by Thorium** [comment]
could you try this version?

**Comment by ingted** [comment]
OK!!! Few minutes!!! Thank you so mush!!!

**Comment by ingted** [comment]
Hi Thorium,

open System.Collections.Concurrent

static let providerCache = ConcurrentDictionary<string,ISqlProvider>()


    let provider =
        lock myLock1 (fun () ->
            match providerCache .TryGetValue typeName with
            | true, prov -> prov
            | _ ->
                let provider =
                    providerCache.GetOrAdd(typeName,
                        fun typeName -> 
                            let prov = ProviderBuilder.createProvider providerType resolutionPath referencedAssemblies runtimeAssembly owner
                            use con = prov.CreateConnection(connectionString)
                            con.Open()
                            // create type mappings and also trigger the table info read so the provider has
                            // the minimum base set of data available
                            prov.CreateTypeMappings(con)
                            prov.GetTables(con,caseSensitivity) |> ignore
                            if (providerType.GetType() <> typeof<Providers.MSAccessProvider>) then con.Close()
                            prov)
                provider)



It works great!!
Thank you so much!!!
