### ISSUE TITLE
NullReferenceException when using connectionStringName in web application

### ISSUE THREAD

**Issue by TheJayMann** [fsprojects/SQLProvider#283]
When attempting to use connectionStringName instead of connectionString in a web application, a null reference occurs when attempting to create the type.  I have found this appears to occur in the getConStringFromConfig function, when it attempts to invoke entryAssembly.Location, as entryAssembly will be null when the code is launched from a non-managed process (such as IIS or IIS Express).  It appears that if isRuntime were false, it would not have attempted to access any properties on the null object.  I'm not exactly sure what I would have to do to pass false to isRuntime, otherwise I would have tried that.  Also, changing the condition to (isRuntime && entryAssembly <> null) would help as well, as, even if the type provider is compiled with isRuntime = true, if the entryAssembly is null, there is no point attempting to access properties of entryAssembly.

**Comment by Thorium** [comment]
I'm wondering is there a reason to use this app.Config-feature at all or should it be removed?
As you can run `.GetDataContext connstr` on runtime.

**Comment by pezipink** [comment]
I believe the idea of the connectionStringName is so you can use the app.config value at _compile time_ instead of having to hardcode connection string literals in the application.  By default it then uses the same connection string at runtime, and it would be up to the user if they wanted to read a different connection string from the config file or some other location at runtime. /cc @colinbull

**Comment by TheJayMann** [comment]
As pezipink said, this is exactly the idea.  While developing and testing, I am using a connection string pointing to a QA database.  However, when I publish this, the connection string in the web.config is changed to our production database.  However, because IIS is not a managed application, the null reference occurs.

I could just use .GetDataContext, which means that I would have to load the connection string value from the web.config then pass it in, but it would be very convenient if this were done by the type provider, seeing as how many other database access frameworks already do this.

While I haven't tried it, I believe this would just work by testing if entryAssembly is null before attempting to access any properties or methods on it.  Given that Assembly.GetEntryAssembly() is documented to potentially return null, perhaps it would be more in the spirit of F# to write '  let entryAssembly = Assembly.GetEntryAssembly() |> Option.ofObj  '.

**Comment by colinbull** [comment]
Think looking at the code it is actually completely

**Comment by colinbull** [comment]
Wrong, for web applications it should be using webconfigurationmanager. And I don't think it should be using the assembly location thing at all I don't believe it is required now.

**Comment by TheJayMann** [comment]
I noticed the updated nuget package, updated it, saw (through ILSpy) that it had the new changes added to it.  I tested it, and it appears to work just fine in my case.
