### ISSUE TITLE
SQLite.Interop.dll could not load

### ISSUE THREAD

**Issue by holmescn** [fsprojects/SQLProvider#286]
### Description

I have run the whole weekend to get SQLProvider working, but I am failed. In order to access SQLite through System.Data.SQLite, I have installed "System.Data.SQLite Core" Package through NuGet. Then I just start a new console program that add reference to System.Data.SQLite and type just

~~~~(fsharp)
[<Literal>]
let connectionString = @"Data Source=:memory:;Version=3;"

[<Literal>]
let resolutionPath = __SOURCE_DIRECTORY__ + @"\..\packages\System.Data.SQLite.Core.1.0.101.0\build\net46\x64\"

type Sql = SqlDataProvider<Common.DatabaseProviderTypes.SQLITE,
                                             connectionString,
                                             ResolutionPath=resolutionPath>
~~~~

ResolutionPath has been tried with:

1. __SOURCE_DIRECTORY__ + @"\path\in\packages\...\x64\"
2. __SOURCE_DIRECTORY__ + @"\x64\" and copy the relevant SQLite.Interop.dll into folder
3. copy the SQLite.Interop.dll into the output dir

But the program could not be compiled. The error said that SQLite.Interop.dll could not be found. Error number is FS3033. Since I am using the Chinese version of Visual Studio, I could not translate the exact error message here. I have google around, but there are rare information there. Then I cloned the source code and look into the source code, nothing special. in `Utils.fs` there is a function that try to load remote assembly of System.Data.SQLite.dll, nothing about SQLite.Interop.dll. So I guess that loading SQLite.Interop.dll is in System.Data.SQLite source. Finally I tried to use raw System.Data.SQLite API, it seems working there.

### Related information 

* Windows 10
* Visual Studio Community 2015 Update 2
* .NET Runtime 4.6
* FSharp 4.0

**Comment by Thorium** [comment]
Yes, the problem is probably that your Visual Studio runs in 32 bit mode. We could add environment mode to the reflection loading error message to make things more clear.

**Comment by Thorium** [comment]
Hmm. Can you try the 32bit version of SQLite.Interop.dll ?

**Comment by holmescn** [comment]
both x64 and x86 are not working.... Now I have to move all database access functions into C# code.

**Comment by username1565** [comment]
1. Download [sqlite-netFx-source-1.0.113.0.zip](https://system.data.sqlite.org/downloads/1.0.113.0/sqlite-netFx-source-1.0.113.0.zip) from [official page](https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki)
2. Unpack this.
3. Try to build this from `sqlite-netFx-source-1.0.113.0\System.Data.SQLite\System.Data.SQLite.2010.csproj`
4. See `sqlite-netFx-source-1.0.113.0\bin\2010\Debug\bin\System.Data.SQLite.dll` have size 396 KB, and this said me: `SQLite.Interop.dll could not load`.
Then, I did the following steps:
1. Created `build.cmd`:
```
:: Set pathway with msbuild.exe into variable %msbuild%
set fdir=%WINDIR%\Microsoft.NET\Framework
set msbuild=%fdir%\v4.0.30319\msbuild.exe

::Build complete System.Data.SQLite.dll with System.Data.SQLite.Interop.dll inside:
%msbuild% System.Data.SQLite\System.Data.SQLite.Module.2010.csproj
%msbuild% SQLite.Interop\SQLite.Interop.2010.vcxproj

pause
```

3. Run `build.bat`

4. See `bin\2010\Win32\Debug\System.Data.SQLite.dll` (it have size with Interop, inside.)

5. Use this, instead of that smaller `System.Data.SQLite.dll`.


After all, I created the following `build.bat`:
```
:: Set pathway with msbuild.exe into variable %msbuild%
set fdir=%WINDIR%\Microsoft.NET\Framework
set msbuild=%fdir%\v4.0.30319\msbuild.exe

::Build System.Data.SQLite.dll without SQLite.Interop.dll
%msbuild% System.Data.SQLite\System.Data.SQLite.2010.csproj
:: out file: \sqlite-netFx-source-1.0.113.0\bin\2010\Debug\bin\System.Data.SQLite.dll not contains "SQLite.Interop.dll"

::Build complete System.Data.SQLite.dll with SQLite.Interop.dll inside:
%msbuild% System.Data.SQLite\System.Data.SQLite.Module.2010.csproj
:: out file: \sqlite-netFx-source-1.0.113.0\bin\2010\DebugModule\bin\System.Data.SQLite.netmodule need to build "System.Data.SQLite.dll" with "SQLite.Interop.dll" inside.
%msbuild% SQLite.Interop\SQLite.Interop.2010.vcxproj
:: out file: \sqlite-netFx-source-1.0.113.0\bin\2010\Win32\Debug\System.Data.SQLite.dll have larger size, and consains "SQLite.Interop.dll" inside.

pause
```
