### ISSUE TITLE
Add support for contains 

### ISSUE THREAD

**Issue by jackmott** [fsprojects/SQLProvider#290]
### Description

It looks like 'contains' is not currently supported. You can workaround this in general with "count" however contains is cleaner. More importantly, reducing the friction of SQLProvider use will really help adoption of it. Assuming it is not extremely tricky to add support for this, it may be worth it, as new users will expect little things like this to work and find it frustrating when they do not, especially since you do not find out until runtime, somewhat defeating the purpose of SQLProvider in the first place. Willing to help if someone can point me to the area to start on.

**Comment by Thorium** [comment]
I think it is supported... What is your use case, how would you like to use it?

**Comment by Thorium** [comment]
And I agree, F# itself already has a deep learning curve, we have to do our best to make things easier for users.

**Comment by jackmott** [comment]
- SQLProvider Version: 1.0.17 from Nuget
- PostgresSQL with Npgsql 3.1.4
- Win10 Visual Studio Update 2 2015


### Code
```fsharp
    let checkUsernameExists username =        
        query { for user in db.Users do 
                select user.Username 
                contains username }
```


### Error
```
Unsupported execution expression `value(FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[System.String]).Contains("admin")`


System.Exception: Unsupported execution expression `value(FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[System.String]).Contains("admin")` at Microsoft.FSharp.Linq.QueryModule.CallGenericStaticMethod@333.Invoke(Tuple`2 tupledArg) at Microsoft.FSharp.Linq.QueryModule.clo@1735-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 ) at AlphaFront.Db.checkUsernameExists(String username) in C:\projects\AlphaFront\AlphaFront\Db.fs:line 52 at AlphaFront.UserLogic.login@33-4.Invoke(LoginForm form) in C:\projects\AlphaFront\AlphaFront\UserLogic.fs:line 34 at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2) at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
```

**Comment by Thorium** [comment]
Ok. Is this the same as:

    let checkUsernameExists username =        
        query { for user in db.Users do 
                where (user.Username=username)
                take 1 } |> Seq.tryHead

**Comment by jackmott** [comment]
That is another workaround, I suppose that will tend to perform slightly better than count...at least I think it should!

**Comment by pezipink** [comment]
The problem here is that way are using `IQueryable` and thus `query { } ` - the inbuilt computation expression has support for a while bunch of extra keywords which we may not support yet - unfortunately there is no way for us to detect people using currently unsupported keywords at compile time.  The only way around this is to drop support for IQueryable / LINQ completely and use our own custom computation expression instead.  This is certainly not off the cards but it is a huge job.

(Just from historical perspective. I do of course agree and would love to dump `query` ! :) )

**Comment by pezipink** [comment]
The least we could do is list the supported keywords in the docs! :)

**Comment by jackmott** [comment]
Does contains not work in general, or only not for some databases?
It is very similar to exists which works. Is this a tricky one to support for subtle reasons?

**Comment by Thorium** [comment]
I'll do this for you, just a minute...

**Comment by jackmott** [comment]
That is great!
