### ISSUE TITLE
Nested IN-queries

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#293]
So this is my unit test. Notice that there is not any Seq.toArray in the query1:

```
[<Test >]
let ``simple select where in queryable query``() =
    let dc = sql.GetDataContext()
    let query1 = 
        query {
            for cust in dc.Main.Customers do
            where (cust.City="London")
            select cust.CustomerId
        }

    let query2 = 
        query {
            for cust in dc.Main.Customers do
            where (query1.Contains(cust.CustomerId))
            select cust.CustomerId
        } |> Seq.toArray
    let res = query
    CollectionAssert.IsNotEmpty query2
    Assert.AreEqual(6, query2.Length)
    Assert.IsTrue(query2.Contains("EASTC"))
```

Here I have only 6 but let's assume in production the first hits to 1500 records and the second would return only 3 records. So what happens is that the first query is executed n times (n=6) and the last is executed once:

```
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[CustomerID] IN (@param1,@param2,@param3,@param4,@param5,@param6))) - params @param1 - "AROUT"; @param2 - "BSBEV"; @param3 - "CONSH"; @param4 - "EASTC"; @param5 - "NORTS"; @param6 - "SEVES"; 
```

What would be so nice is if this could detect the in is SqlQueryable and then create a nested query and execute it only once:
```
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[CustomerID] IN (
   SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
   WHERE (([cust].[City]= @paramnested1))
))) - params @paramnested1 - "London";
```
So "if IN is SqlQueryable get the SQL-clause and rename `@param`s to `@paramnested`s".

If I say Seq.toArray to the first, I will get a result of:
```
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[City]= @param1)) - params @param1 - "London"; 
Executing SQL: 
SELECT [cust].[CustomerID] as 'CustomerID' FROM main.Customers as [cust] 
WHERE (([cust].[CustomerID] IN (@param1,@param2,@param3,@param4,@param5,@param6))) - params @param1 - "AROUT"; @param2 - "BSBEV"; @param3 - "CONSH"; @param4 - "EASTC"; @param5 - "NORTS"; @param6 - "SEVES"; 

```
...which is correct. But there is the problem of high network traffic if your first result set is large.

---

I tested quickly if this is possible:
- Detecting `IQueryable<_>`s is easy.
- Dynamic casting to generic objects is not so easy.
- Now, how could you say in each SQLProvider that please get the SQL-clause when you hit this new NestedIn operator? As the queryable is created QueryExpressionTransformer which is later than each provider

https://github.com/Thorium/SqlProvider/tree/nested-in

**Comment by colinbull** [comment]
In theory if you use the `query` type from [Composable Query](http://fsprojects.github.io/FSharp.Linq.ComposableQuery/) then this should be possible (Composable Query applies beta reduction to the query before it is executed so it should do exactly this type of optimization.

**Comment by Thorium** [comment]
Bad news is that you can't compose select-in-clauses if the SQL query generator don't support select select-clauses inside other SQL. Good news is that I did this in PR #299
