### ISSUE TITLE
special mysql column name, e.g. from

### ISSUE THREAD

**Issue by ingted** [fsprojects/SQLProvider#294]
### Description

insert update a mysql table with special word column name like 'from' will cause mysql command error

### Expected behavior

should be  `columnname`, not only columnname

### Known workarounds

insert:
("\`" + (String.Join("\`, \`",columnNames)) + "\`")

update:
(String.Join(",", data |> Array.map(fun (c,p) -> sprintf "\`%s\` = %s" c p.ParameterName ) ))

### Related information 

* Operating system
SERVER 2012 R2
* Branch
master
* .NET Runtime
4.6.1

**Comment by Thorium** [comment]
As there is this workaround, are you going to make a PR or are you expecting someone else fix this? :-)

**Comment by ingted** [comment]
Hi Tuomas,

I think you saw my code...
I will make a PR later in these days.^^

(Sorry for that I am not very familiar with Git mechanism, still in
learning.)

Regards
Anibal

**Comment by Thorium** [comment]
Great! Just push to your GitHub-fork and then go to your fork web page and press the pull-request button. :-)

I assume the parameter count for insert/update is never zero. :-)

Br
Tuomas

**Comment by Thorium** [comment]
Merged and in NuGet version 1.0.25.
