### ISSUE TITLE
Type mapping doesn't support ColumnType Date/Time (MSSQLSERVER)

### ISSUE THREAD

**Issue by MikeBild** [fsprojects/SQLProvider#301]
### Description

Type mapping doesn't support ColumnType Date/Time. (Reproducible in Mono Mono, Version 4.2.3.0 / Docker image fsharp/fsharp)

### Repro steps

1. Use a DB with MSSQLSERVER with ColumnType Date/Time

2. Run in Mono

### Expected behavior

-

### Actual behavior

* `System.ArgumentOutOfRangeException: No mapping exists from SqlDbType Date to a known DbType.`
* `System.ArgumentOutOfRangeException: No mapping exists from SqlDbType Time to a known DbType.`

### Known workarounds

PR #300 

### Related information 

* Mono, Version 4.2.3.0
* Docker image fsharp/fsharp

**Comment by MikeBild** [comment]
closed <- a771daec058481a943862644be6a2958218770ae

**Comment by Thorium** [comment]
Just tried to run SQLProvider on Mono (Docker) against Azure MsSql server and it was working great! Now just have to figure out how to allow my dynamic Docker (Bitbucket Pipelines) IPs securely to Azure test environment firewall...
