### ISSUE TITLE
Strange behavior MySQL

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/SQLProvider#306]
Hello guys, 
I just encounter some weird behavior using SQLProvider and MySQL (MariaDb).

It's like one of this four columns names is make the request invalid: Create, Read, Update, Delete

Here is the error that I got:
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Create,Read,Update,Delete) VALUES ('2016-07-28 14:49:02.096471','2016-07-28 14:4' at line 1`

I just use the same code as the one crashing but I change the name of the columns with CreateRight, ReadRight, UpdateRight, DeleteRight and it's working now.

Sorry I don't have more information on this problem but perhaps there is reserved word in the one that I used...

**Comment by MangelMaxime** [comment]
Perhaps there is a confusion with `Create` and `Delete` methods.

**Comment by Thorium** [comment]
I think this is duplicate with #294 and is now fixed...

**Comment by Thorium** [comment]
Tested with latest version. Working.
