### ISSUE TITLE
Supply User information to SQLConnection

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/SQLProvider#307]
Hey guys,

I want to pass the windows user information (username and password) to the mssqlserver.
So that the mssqlserver responses with the user specific data (filtered view).

Basically I want to set the credential property of the sqlconnection.
[https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.credential(v=vs.110).aspx](url)

Do you have any idea how I can implement that by using the sqlprovider?

Thanks in advance,

Tim

**Comment by pezipink** [comment]
Hi Tim

If the current windows user account of the executing process is setup on the sql server, you should be able to connect to it using a connection string with Trusted_Connection=True in it.  eg

`Server=myServerAddress;Database=myDataBase;Trusted_Connection=True;`

I don't think there is a way to pass an explict user name and password for a windows user for whatever security reasons.  I am pretty sure the SqlCredential object is for SQL Authentication, not windows (though I could be wrong..!)

**Comment by tforkmann** [comment]
@forki any thoughts?

**Comment by forki** [comment]
I think what tim wants is to login with the sql user.
As far as I understand all windows users are mapped to sql users. So the following situation occurs:

* user logs into website with windows credentials => username/password are in suave process
* suave (running on windows server with service windows user) needs to pass the credentials to the sql connection because the service user is useless

**Comment by tforkmann** [comment]
That's correct.

**Comment by pezipink** [comment]
If you setup IIS and the website for impersonation and integrated security, along with the Trusted Connection = true, this should pass along the credentials automatically for you

https://msdn.microsoft.com/en-us/library/bsz5788z.aspx

**Comment by pezipink** [comment]
(Assuming Suave is running under IIS!)

**Comment by forki** [comment]
Mhm we're on suave

**Comment by pezipink** [comment]
I know you can force the impersonation stuff manually with a bit of messing about, I don't know if this will "just work" with Suave though. We would need to make a (hopefully simple) change to the SQLProvider to support it this.  

Suggest a static parameter "force impersonation" or similar.

https://msdn.microsoft.com/en-us/library/ms131068.aspx

**Comment by forki** [comment]
before that, I assume we can just try to connect with sql user name and password. where would we specify that? on sql.GetDataContext() ?

**Comment by pezipink** [comment]
yes, for normal sql authentication just give it a connection string at runtime with the username/password

`Server=myServerAddress;Database=myDataBase;User Id=myUsername;
Password=myPassword;`

**Comment by Thorium** [comment]
I updated the documentation to display this in more visible place as this is about 3rd time I see a question about runtime connectionString.

**Comment by pezipink** [comment]
I assume you got this to work? can we close this?

**Comment by tforkmann** [comment]
For our authorization requirements I had to bring suave on IIS. I'm now able to perform an impersonation and windows authorization for the user.

Now I actually need to perform an "forced impersonation" to the sqlserver as described by @pezipink.

Do you think it's possible to implement that functionality to the sqlprovider?
