### ISSUE TITLE
Expose ContinueUpdateOnError on strongly typed data tables

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/SQLProvider#310]
### Description
It is sometimes necessary to perform an insert of records and continue inserting even if one record fails. With the raw DataAdapter you can set the ContinueUpdateOnError property, but this is not exposed by the strongly type data table model. Perhaps adding optional arguments on the Update() call would suffice?

**Comment by Thorium** [comment]
I kind of like this idea...

**Comment by Thorium** [comment]
What do you think of version in this branch thorium-exceptionhandling?

**Comment by isaacabraham** [comment]
Comments on the PR

**Comment by Thorium** [comment]
So basically wrong repo.
I'll close this for now.
