### ISSUE TITLE
GroupBy / Cannot get SqlExp object of an IQuerable object

### ISSUE THREAD

**Issue by ingted** [fsprojects/SQLProvider#317]
### Description

let a =
    query {
        for row in statDb.baasStat.RequestStatistics do
        select row 
    }
let b =
    query {
        for row in statDb.baasStat.RequestStatistics do
        select (row.ApplicationId, row.RequestLength)
    }

I could get the SqlExp object of a easily by IWithSqlService.SqlExpression.
But I tried a lot of way for b but in vain...

However, when execution the Seq.toArray, I could access IWithSqlService.SqlExpression with breakpoint...
### Repro steps

just select row/row.property then this situation just be reproduced...
### Expected behavior

Reflection should access SqlExpression for both queries...
### Actual behavior

SqlExpression for b is unavailable
### Known workarounds

None...

Please help!!!
Thank you so much!!

**Comment by Thorium** [comment]
What are you trying to do? IWithSqlService is an internal interface. Get an SQL-clause?
If so, try this:
```
FSharp.Data.Sql.Common.QueryEvents.SqlQueryEvent |> Event.add (printfn "Executing SQL: %s")
```
I would guess that it's lazy and not executed yet and that's why you get it after .toArray.

**Comment by pezipink** [comment]
SqlExp itself is internal as well - what are you trying to achieve exactly?

**Comment by ingted** [comment]
I have some modify for SqlRuntime.QueryExpression.fs like this:

`    type QueryExpressionTransformer2 =
        static member convertExpression2(exp, (entityIndex:string ResizeArray), con, (provider:ISqlProvider)) =
            convertExpression exp entityIndex con provider`

fsx script code:
`let typ_QryExpTrsform = 
    assm.GetType("FSharp.Data.Sql.QueryExpression.QueryExpressionTransformer+QueryExpressionTransformer2")`

`let qryExpTransformMbrs = typ_QryExpTrsform.GetMethods(bfsnp)  //|> Array.iter (fun x -> printfn "%s" x.Name)
let convertExp = (qryExpTransformMbrs |> Array.filter (fun x -> x.Name.like "convertExpression2")).[0]
`
`let bfinp = BindingFlags.Instance ||| BindingFlags.NonPublic
let bfsnp = BindingFlags.Static ||| BindingFlags.NonPublic`
`let (@.) (o:'a) (n:string) = 
    (o.GetType().GetFields(bfinp)
    |> Array.filter (fun x -> x.Name = n)
    |> Array.item 0).GetValue(o)`

So if I have a SqlExp object, I could get the sql statement like this:

`let sql,_,_,_ = convertExp.Invoke(null, [| box sqlExp; getRequest@."tupleIndex"; (statConn.baasStat ()); ISPfromSQP.baasStat |]) :?> string * System.Collections.Generic.List<System.Data.IDbDataParameter> * Delegate * Table
`

And why I must need the sql statement with specific column selection (e.g. only column1, column2, max(column3)) because I want to add 'group by column1, column2...' in the sql statement.


Briefly I tried to execute a sql 'select column1, column2, max(column3) from table1 group by column1, column2'

By some code like this:

`let newCmd_method = typ_ISqlProvider.GetMethod("CreateCommand")
let newParam_method = typ_ISqlProvider.GetMethod("CreateCommandParameter")
let paramProcess = fun provider (command : IDbCommand) (name, ordinal, value) ->        
    let qp = QueryParameter.Create(name, ordinal)
    let param = newParam_method.Invoke(provider, [|qp; value|]) :?> IDbDataParameter
    command.Parameters.Add(param) |> ignore

let openCmd = fun provider (con:IDbConnection) baseQuery params_ ->  
    let command = newCmd_method.Invoke(provider, [| con; baseQuery |]) :?> IDbCommand
    let paramProc = paramProcess provider command
    params_ |> Array.iter paramProc                
    match con.State with 
    | ConnectionState.Open -> ()
    | _ -> con.Open()
    command

let getCmdReader = fun provider (con:IDbConnection) baseQuery params_ ->  //name, ordinal, value
    let command = openCmd provider con baseQuery params_    
    let reader = command.ExecuteReader()
    reader`

Regards
Anibal

**Comment by Thorium** [comment]
I think that if we want to start to implement group by to this provider (not supported now, but you can use procedures meanwhile), it would be probably good idea to do it in its own branch, and not all at once. I think these would be the steps:

1) From the test project take the unit test `simple select query with groupBy` Ignore-attribute out of comments. (Close all code windows and restart VS on this solution so then you can actually run the test without VS locking the FSharp.Data.SqlProvider.dll all the time. You can also debug as long as you don't open the test .fsx file).

2) Then to the real SQLProvider solution, SqlRuntime.Common.fs:
Design GroupData parameter shape.
.NET seems to use anonymous object with key and entity. Do we want to support Having? Not yet?
There is now `and LinkData =
` it could be good idea to do similar
```fsharp
and GroupData =
 {
//...
}
```

Then add this to one of SqlExp options:
```fsharp
| GroupBy      of alias * GroupData * SqlExp     // alias and column names
//...
// also update the current:
with member this.HasAutoTupled() =
//...
| GroupBy(_,_,rest)
//...
```

Then for SqlQuery (I don't know the reason for this two-phased-parsing) we need data like
```fsharp
Grouping     : (some-tuple-of-data) list
// ... and add it to empty like others:
static member Empty = { Filters = []; Links = []; Grouping = []; Aliases = Map.empty;
```
and add it to ofSqlExp convert function like others:
```fsharp
| GroupBy(alias,groupdata,rest) ->
 
    convert { q with Grouping = (legaliseName alias, ...parse your some-tuple-of-data here...)::q.Grouping } rest
```

3) SqlRuntime.Linq.fs
as there is now `and SqlOrderedQueryable`, I think it would be easiest to add also: `and SqlGroupingQueryable` which basically handles the fact that groupby won't return `IQueryable<SqlEntity>` but some `IQueryable<IGrouping<...>>`.

Then we need to handle the incoming LINQ-query. That should be fairly easy (if anything is), something like this should do on a simple case:
```fsharp
| MethodCall(None, (MethodWithName "GroupBy" as meth),

                   [ SourceWithQueryData source;

                     OptionalQuote (Lambda([ParamName sourceAlias],SqlColumnGet(sourceTi,sourceKey,_)) as lambda)]) ->

// some simple parsing here, see the other methods
let sqlExp =
 GroupBy(sourceAlias,groupData,source.SqlExpression)
// dynamic creation of the new SqlGroupingQueryable<...> and some crazy complex casting to get runtime happy:
let ty = typedefof<SqlGroupingQueryable<...>>(...) :?> IQueryable<_>
```

4) Then, for all the providers the GenerateQueryText method should be updated to handle the SqlQuery Grouping parameter.

**Comment by Thorium** [comment]
started a group-by branch, feel free to help: https://github.com/fsprojects/SQLProvider/tree/group-by

**Comment by Thorium** [comment]
The status of this.... just occurred to me:

The LINQ Group-by-projection is actually
```fsharp
Select(Group(...), k => ...k.key...)
```

So first has to be parsed this group item (done in the branch), and then separately the aggregation (not done yet), as selection projection is not accessible from the inner groupby-operation itself.

**Comment by Thorium** [comment]
With the latest 1.1.72 version you can do simple join-groupby like this:
```fsharp
    let qry = 
        query {
                for cust in dc.Main.Customers do
                join order in dc.Main.Orders on (cust.CustomerId = order.CustomerId)
                groupBy cust.City into g
                select (g.Key, g.Count())
            }
    let res = qry |> dict  
```

...or bit more complex like this:

```fsharp
    let qry = 
        query {
                for cust in dc.Main.Customers do
                join order in dc.Main.Orders on (cust.CustomerId = order.CustomerId)
                groupBy (cust.City, order.ShipCity) into g
                select (g.Key, g.Max(fun (c,o) -> c.PostalCode))
            }
    let res = qry |> dict  
```
