### ISSUE TITLE
Error When Creating Connection to Access DB

### ISSUE THREAD

**Issue by jon49** [fsprojects/SQLProvider#324]
### Description

Error When Creating Connection to Access DB

### Repro steps

Not sure. DB is proprietary. I'll look into it though when I have more time.

### Expected behavior

Am able to create a TypeProvider Type.

### Actual behavior

The code:

```
type AccessEnglishDB = SqlDataProvider<Common.DatabaseProviderTypes.MSACCESS, @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\Users\jon\Downloads\Data\data_7.15.16.mdb">
```

Produces:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unspecified error	parser	C:\r\parser\parser\Databases.fs	28	
```

### Known workarounds

Use `System.Data.OleDb`

### Related information 

* Windows 10
* SQLProvider.1.0.29
* .NET Framework 4.5.2, FSharp.Core 4.4.0.0

**Comment by Thorium** [comment]
For me Access works very well.

Does this work for you:
https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Tests/scripts/MSAccessTests.fsx

**Comment by jon49** [comment]
I tried the script you provided. When I run it, it works fine. But once I start writing a query against `Northwind` it shows the same error as before and won't give me intellisense.

**Comment by Thorium** [comment]
It would be nice to know more about this. If you can, please open 2 Visual Studios, other with SQLProvider.sln (and build this first and then) other with SQLProvider.Test.sln (with MSAccessTests.fsx) and attach the SQLProvider.sln to devenv.exe (or both FSI.exe:s if you run your code in interactive) and you should see the actual place where it breaks.

**Comment by Thorium** [comment]
Ok, now I got the error. It comes from System.Data.OleDb.OleDbException.

If I have to guess, I would say that there are multiple connections opened to the database and it can handle only one at a time. That's why it works for a few seconds. It has been working, I don't know directly what has broke it. Something leaves the connection open and then CreateTypeMappings() call fails.
