### ISSUE TITLE
Wrong branch shown on AppVeyor CI status

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#326]
Readme.md shows the latest build status of all AppVeyor CI builds.

I would like it to show either master branch only or the correct branch.

As now, group-by branch is having some not-yet-working unit tests
and the master branch Readme.md shows red status for this reason.
Because the last commit was to group-by branch.

https://ci.appveyor.com/project/colinbull/sqlprovider-ogy2l

Ping @colinbull ?

**Comment by colinbull** [comment]
Fixed..
