### ISSUE TITLE
ODBC access for Redshift

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/SQLProvider#327]
### Description

When using the ODBC driver to access Amazon's Redshift, the provider correctly identifies tables etc., but when sending through queries to the service, it surrounds all fields with ``'`` which cause the service to reject the query.

Is there a way to stop these quotes getting added?

**Comment by Thorium** [comment]
There is `cOpen` and `cClose` in ODBC. The hard thing is that ODBC means so many data sources. Should this be somehow configured by how?

Currently there is just naïve code:
```fsharp
    let mutable cOpen = '`' //char separator in query for table aliases `alias` or [alias]
    let mutable cClose = '`' 
    //...
        if con.Driver.Contains("sql") then
            cOpen <- '['
            cClose <- ']'
```

**Comment by isaacabraham** [comment]
Perhaps a parameterised argument to the TP itself - char separators or something?

**Comment by Thorium** [comment]
Any ideas @pezipink ? 

@isaacabraham what is the correct separator in your case, if the table name contains spaces?

**Comment by Thorium** [comment]
Done.
http://fsprojects.github.io/SQLProvider/core/odbc.html
The sad thing is that as constructor parameters have to be literal, there is no easy way to refactor them to nice option-types or anything.

**Comment by isaacabraham** [comment]
@Thorium works beautifully, thanks. FYI - Redshift uses double quotes for quoted identifiers, see http://docs.aws.amazon.com/redshift/latest/dg/r_names.html.

Cheers
