### ISSUE TITLE
Update command is not using brackets [ ] to avoid keywords

### ISSUE THREAD

**Issue by amieres** [fsprojects/SQLProvider#338]
### Description
Hi

I'm trying to update a table called [CS].[User]
This is the generated SQL:

UPDATE CS.User SET language_code = @param0,user_email = @param1,user_name = @param2 WHERE user_code = @pk0

since user is a keyword I get the error: "Incorrect syntax near the keyword 'User'."

**Comment by Thorium** [comment]
What database are you using?

**Comment by amieres** [comment]
I'm using SQL Server

**Comment by amieres** [comment]
Thank you very much
