### ISSUE TITLE
nicePascalName/niceCamelCase strips out first number after single letter

### ISSUE THREAD

**Issue by kellerd** [fsprojects/SQLProvider#339]
### Description

nicePascalName/niceCamelCase provides a strange name resolution to some of my tables/fields.  Our standard, archaic as it may be are names like 

ZC963_AUDIT_LOG
TC001_USERS
A21_SERVICE

_Just logging this here for tracking as it would have wide scoping breaking changes if corrected._
### Repro steps

Table name, stored procedure, column,ect with single letter (uppercase) followed by numbers will strip numbers of first digit
### Expected behavior

> nicePascalName "Z963_TABLESPACE" 
> val it : string = "Z963Tablespace"
> nicePascalName "A21_SERVICE"
> val it : string = "A21Service"
### Actual behavior

> nicePascalName "Z963_TABLESPACE" 
> val it : string = "Z63Tablespace"
> nicePascalName "A21_SERVICE"
> val it : string = "A1Service"
### Known workarounds

More than one character before the number

> nicePascalName "TC001_USERS"
> val it : string = "Tc001Users"
> nicePascalName "ZC963_AUDIT_LOG"
> val it : string = "Zc963AuditLog"

Lowercase first letter

> nicePascalName "z963_TABLESPACE"
> val it : string = "Z963Tablespace"
### Related information
- Operating system : Windows
- Branch : master
- .NET Runtime, CoreCLR or Mono Version : .NET Runtime

**Comment by Thorium** [comment]
Fixed in version 1.0.39.
