### ISSUE TITLE
Column names with numbers and generated properties

### ISSUE THREAD

**Issue by sheganinans** [fsprojects/SQLProvider#354]
Using the SQLProvider I connect to a database which has a table called: History

It has columns named: Kind1, Kind2, and Kind3

However when I use the generated types:

```fsharp
type DBSchema =
    SqlDataProvider<
        ConnectionString = connString,
        DatabaseVendor = dbVendor,
        IndividualsAmount = 1000,
        UseOptionTypes = true >

let db = DBSchema.GetDataContext().Dbo

let foo () = query {
    for x in db.History do
    head }

let test () = printfn "%A" <| foo().Kind
```

When I use Intellisense to autocomplete `foo().Kind`, `Kind` is the only suggestion. When I run it, it gives the value of `Kind1`. However Intellisense also reports that there are 3 properties. So all is not lost.

They look like:

```
property SqlDataProvider<...>.datacontext.dbo.HistoryEntity.Kind: Option<int>
property SqlDataProvider<...>.datacontext.dbo.HistoryEntity.Kind: Option<int>
property SqlDataProvider<...>.datacontext.dbo.HistoryEntity.Kind: Option<int>
```

So it seems that it does have access to all 3 tables. I thought at first that it was an indexed property, so I tried:

```fsharp
let test () = printfn "%A" <| foo().Kind.[0]
```

But that did not work either, since `Value` is not defined. So now I'm stuck. I absolutely need to have access to all 3 different fields and I absolutely cannot change the names of the columns.

### Related information 

* MSSQL
* Windows 10
* .NET 4.5.2

**Comment by sheganinans** [comment]
Apparently I can get it with:

```fsharp
let test () = 
    printfn "%A" <| foo().GetColumn "Kind1"
    printfn "%A" <| foo().GetColumn "Kind2"
    printfn "%A" <| foo().GetColumn "Kind3"
```

But I find that a bit sub-optimal, since I am not getting all the type safety that I'm supposed to get from this library.

**Comment by Thorium** [comment]
Probably related to #339

**Comment by sheganinans** [comment]
@Thorium Definitely a duplicate, however, like I mentioned. I cannot change the names of the columns.

**Comment by Thorium** [comment]
Hmm, I'm not able to reproduce this with SQLProvider (nuget 1.0.36) even if it shouldn't have this fix yet. Can you add here a creation SQL-script of the table that has this problem?

**Comment by Thorium** [comment]
This is fixed.
