### ISSUE TITLE
A query throws System.Exception while being interpreted.

### ISSUE THREAD

**Issue by DotGoodies** [fsprojects/SQLProvider#357]
### Description

A query throws System.Exception while being interpreted.

### Repro steps
Query:

``` F#
        let q = query{
            for elementData in database.Dbo.HierarchyElementData do
            groupBy (elementData.SubsetId) into agg
            select(agg.Key, agg)
        }
```
HierarchyElementData is a flat table without foreign keys. So subsetId is just an integer. 

### Expected behavior
Query is translated into SQL statement.

### Actual behavior
The following is thrown:
System.Exception was unhandled
Message: An unhandled exception of type 'System.Exception' occurred in FSharp.Core.dll
Additional information: unrecognised method callvalue(FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[FSharp.Data.Sql.Common.SqlEntity]).GroupBy(elementData => elementData.GetColumn("SubsetId"))

   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
   at Microsoft.FSharp.Linq.QueryModule.clo@1735-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )

### Related information 

* SQL server 2016
* Windows 8.1
* Nuget package version 1.0.36
* .Net framework 4.6.1

**Comment by pezipink** [comment]
groupBy is not yet supported, as specified in the documentation.  There is some work being done on it in another branch, but it is a complex problem.  

In the meantime you can either do the grouping client-side, or put the logic into a sproc / function of some description.

**Comment by Thorium** [comment]
Now there is a PR for this.
Just curious: What would you expect to get as a type for your `agg` when you don't do any specific select?
