### ISSUE TITLE
Offline: Intellisense is not working outside SQLProvider types.

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#363]
If you are offline, with no database connection, the design time `con.Open()` will throw some `System.Data.SqlClient.SqlException`, which is happening on multiple threads and taking a lot of time, leading to situation that VS is busy, or intellisense shows "Loading...". **This happens to all types, not only SQLProvider query-code.** So I expect these exceptions break the whole VS intellisense.

Probably better would be swallowing the exception and e.g. adding it to XMLDocs.

Also, it would be probably better to have a lock to not connect the database multiple times in parallel in SqlDesignTime.fs method `createTypes`. On the other hand we may not want to cache the design time connection as the connection/database is often changed during design time.

**Comment by pezipink** [comment]
lock / swallow sounds alright, and yes the design time connection was never cached in the original design for the reasons mentioned.  Maybe we can implement a very simple sliding cache type mechanism for it ?

**Comment by Thorium** [comment]
No problems with the latest VS / FSharp.
