### ISSUE TITLE
4 hours wasted on silly error, pointless, please remove

### ISSUE THREAD

**Issue by yetanotherlogonfail** [fsprojects/SQLProvider#365]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Used database
* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by Thorium** [comment]
Should we hold a silent minute for the memory of the wasted 4 hours or will we get the actual problem description and a suggestion what we could do about it? :-)
