### ISSUE TITLE
Incorrect UPDATE syntax when updating multiple columns in Oracle

### ISSUE THREAD

**Issue by object** [fsprojects/SQLProvider#366]
### Description

Attempt to update multiple columns of a table results in the Oracle exception ORA-01767

### Repro steps

Code to reproduce the problem using Oracle.ManagedDataAccess (12.1.24160719)

let record = query { /* some query returing a db record */ } |> Seq.head
record.Column1 <- val1
record.Column2 <- val2
dbContext.SubmitUpdates()

2. Step B

### Expected behavior

Expected no failure.

### Actual behavior

Oracle.ManagedDataAccess.Client.OracleException with the message:
"ORA-01767: UPDATE ... SET expression must be a subquery"

### Known workarounds

Generated code:
UPDATE MYDB.MYTABLE SET (COLUMN1,COLUMN2) = (:param0,:param1) WHERE ID = 1489589

Working code:
UPDATE MYDB.MYTABLE SET (COLUMN1,COLUMN2) = (select :param0,:param1 from dual) WHERE ID = 1489589;

**Comment by object** [comment]
I submitted a PR for this issue.

**Comment by Thorium** [comment]
Ping @colinbull
