### ISSUE TITLE
Joins + Select case

### ISSUE THREAD

**Issue by j-u-l-i-e-n** [fsprojects/SQLProvider#376]
### Description

I have been trying to perform a self join on a table on a nullable field (using another field as a default when the value was null). To mimic the "select case" clause, I added an intermediary step which doesn't work (except when queries are combined).

### Repro steps
I have the following table structure : 

```
CREATE TABLE currencies (
    id                           INTEGER       PRIMARY KEY AUTOINCREMENT NOT NULL,
    ticker                       VARCHAR (3)   NOT NULL,
    offshore_hedging_currency_id INTEGER       REFERENCES currencies (id)
);
```

I have been trying to replicate this :
```
SELECT c.ticker, hc.ticker 
FROM currencies c
LEFT JOIN currencies hc on hc.id = (CASE WHEN c.offshore_hedging_currency_id IS NULL THEN c.id ELSE c.offshore_hedging_currency_id END)
```

I unsuccessfully tried this :
```
let q = 
  query {
    for c in db.Main.Currencies do  
    let tmp = if c.OffshoreHedgingCurrencyId.IsSome then c.OffshoreHedgingCurrencyId.Value else c.Id
    join hc in db.Main.Currencies on (tmp = hc.Id) 
    select (c.Ticker, hc.Ticker)
  } 
```

### Actual behavior

The query throws the following exception :

```
System.Exception: unrecognised method call value(FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject`2[FSharp.Data.Sql.Common.SqlEntity,System.Int64]]).Join(value(FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[FSharp.Data.Sql.Common.SqlEntity]), tupledArg => tupledArg.Item2, ohc => ohc.GetColumn("id"), (tupledArg, ohc) => new AnonymousObject`3(Item1 = tupledArg.Item1, Item2 = tupledArg.Item2, Item3 = ohc))
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
   at Microsoft.FSharp.Linq.QueryModule.clo@1741-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at <StartupCode$FSI_0042>.$FSI_0042.main@()
Stopped due to error
```

### Known workarounds

The following did, however.
```
let q = 
  query {
    for ccy in db.Main.Currencies do  
    let tmp = if ccy.OffshoreHedgingCurrencyId.IsSome then ccy.OffshoreHedgingCurrencyId.Value else ccy.Id
    select (ccy, tmp)
  } 

let q2 = 
  query {
    for (ccy, tmp) in q do
    join ohc in db.Main.Currencies on (tmp = ohc.Id)
    select (ccy.Ticker, ohc.Ticker)
  }
```

But I am not sure what the generated SQL command is... I am not sure whether this comes from this library or from the FSharp or Linq libraries.

**Comment by Thorium** [comment]
@pezipink, would it be possible to call CreateQuery already on design time, to get the possible query errors already on design time? (But not execute the query.)

`AddXmlDocComputed` works on TypeProvider but what would be actually nice, would be generating the SQL-query as tooltip for `IQueryable<_>`. But it probably is not possible to replace IQueryable-tooltips on-the-fly, not with TypeProvider, nor FSharp.Compiler.Service.

Yet again I don't want to generate extra queries in non-design-time compiled execution.

**Comment by Thorium** [comment]
Now, what comes to `let` variables, the "correct" way to transfer LINQ-expression trees to with let-clauses would be having nested select in from-clause. What I mean by that is (simplified example):

```fsharp
let q = query {
    for x in xs do  
    let tmp = x+1
    where (tmp>2)
    select (x, tmp)
  }
```
translates to SQL

```sql
SELECT x, tmp
FROM (
   SELECT x, (x+1 AS tmp) FROM xs
)
WHERE tmp>2
```

...but as far as I know, not all the databases we support can parse this kind of SQL.
Now we don't support nested queries in from-clauses. Compared to EntityFramework that does support this, it introduces more performance related problems:

 - Developer is even further away from understanding what the code does.
 - There are easily 7 nested queries with long LINQ-clauses.
 - Harder to hit database indexes. 
 - Flooding large queries to procedure cache that will never hit again. 
 - Creates the need to profile your SQL.

So I'm not sure if we even want to go to that direction.

**Comment by j-u-l-i-e-n** [comment]
Would there be anyway to generate
`(SELECT CASE ... END)`

Incidentally, a problem may also be with the join as it seems it requires table columns on both sides of the join, with the previous table as the left-hand side of the equality.

The following thus raises an exception
```
query {
  for c in db.Main.Currencies do  
  join hc in db.Main.Currencies on (1L = hc.Id) 
  select (c.Ticker, hc.Ticker,  if c.OffshoreHedgingCurrencyId.IsSome then c.OffshoreHedgingCurrencyId.Value else c.Id)
} |> Seq.toArray
```

And the following will not compile
```
query {
  for c in db.Main.Currencies do  
  join hc in db.Main.Currencies on (hc.Id = 1L) 
  select (c.Ticker, hc.Ticker,  if c.OffshoreHedgingCurrencyId.IsSome then c.OffshoreHedgingCurrencyId.Value else c.Id)
} |> Seq.toArray
```

But I don't know if this a query builder issue, or a LINQ one ? (Or perhaps it's done purposely !)

**Comment by Thorium** [comment]
If you really would like to do things that way, I would try using the custom left-join operator `!!` from namespace `FSharp.Data.Sql` as used in some of our documentation, then select both Id OffshoreHedgingCurrencyId and filter out the one that you need in the select-clause, not join.

On the other hand, looking to your SQL-clause, you are joining table to itself? That is usually anti-pattern on some level if you don't have a tree-structure and correct indexing. Why not just make simpler query without any joins, and do the data-parsing/-manipulation in F# business-logics side? Which is kind of more near the SQLProvider ideology: Make some simple queries, and do the business logic in pure F# as it's powerful language to do data manipulation.

**Comment by Thorium** [comment]
This is now working, just left the `let` away and do the condition directly to join condition.
