### ISSUE TITLE
Create longer version does not contains the primary key

### ISSUE THREAD

**Issue by diegobfernandez** [fsprojects/SQLProvider#378]
### Description

The ``Create()`` method does not contains the table primary key.

### Repro steps

1. Create table
```
CREATE TABLE unidadeDeMedida (
  codigo INT PRIMARY KEY,
  descricao NVARCHAR(250) NOT NULL
)
```
2. Define type
```
type Db =
    SqlDataProvider<Common.DatabaseProviderTypes.MYSQL,
                    DesignConnectionString,
                    ResolutionPath = ResolutionPath,
                    UseOptionTypes = true,
                    CaseSensitivityChange = CaseSensitivityChange.ORIGINAL>
``` 
3. Try to access ``Create(codigo, descricao)``
```
let InserirUnidadesDeMedida connectionString unidadesDeMedida =
  let ctx = Db.GetDataContext connectionString
  unidadesDeMedida
  |> Seq.map (fun x ->
    ctx.Mdic.UnidadeDeMedida.``Create(codigo, descricao)``(x.Codigo, x.Descricao))
  |> ignore

  ctx.SubmitUpdates ()
```

### Expected behavior

The Create(codigo, descricao) should exist.

### Actual behavior

Compile error
```
FS0039: The field, constructor or member 'Create(codigo, descricao)' is not defined
```

### Known workarounds

Do not use Create(...) method

### Related information 

* Used database: MariaDB 10.1.21
* Operating system: Fedora 25
* Branch: The one from Nuget (1.0.42)
* .NET Runtime, CoreCLR or Mono Version: Mono 4.6.2.16

**Comment by Thorium** [comment]
Another workaround is to generate ids in database:
```sql
CREATE TABLE unidadeDeMedida (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`codigo`)  COMMENT ''
)
```

**Comment by diegobfernandez** [comment]
@Thorium I tried your script and it still does not work.
I forgot to mention there is only a method `Create(descricao)` in both cases.

**Comment by Thorium** [comment]
Yes, at least in the later case there shouldn't be codigo at all, because it's database generated, so you don't insert primary key manually but database will generate it when the item is inserted. You are right that in the first case you should be able to insert a primary key, but I don't know if we know if primary keys are generated or not. Anyways you can use the method missing the primary key and then try to set it later, like

```fsharp
let InserirUnidadesDeMedida connectionString unidadesDeMedida =
  let ctx = Db.GetDataContext connectionString
  unidadesDeMedida
  |> Seq.iter (fun x ->
    let itm = ctx.Mdic.UnidadeDeMedida.``Create(descricao)``(x.Descricao)
    itm.codigo <- x.Codigo
    )
  ctx.SubmitUpdates ()
```

**Comment by diegobfernandez** [comment]
Got it, my problem is that the PK has to be user defined.
I'll keep setting fields individually.

Can we keep this issue open or open another to track it?
When I have some time I'll give it a try.
