### ISSUE TITLE
I want to be able to compare two SQL-columns in where clause

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#380]
I want to do this kind of query:

```fsharp
    let qry = 
        query {
            for item in dc.Main.Products do
            where (item.ExpiryDate > item.ShipmentDate)
            select item
        } |> Seq.toArray
```
This is not supported right now, but the support is kind of easy to add (and get rid of where-left-side-only limitation).

It will be as Expression:
```
.Call $item.GetColumn("ExpiryDate ") > .Call $item.GetColumn("ShipmentDate")
```

...but the problem is that we have to identify the bound variables vs. free variables. Because this will be totally different query, the date is actually coming outside the query even if the item is entity with GetColumn method (and this is working now):

```fsharp
    let newEntity = dc.Main.Products.``Create(ExpiryDate, ShipmentDate)``(...)
    dc.SubmitUpdates()
    let qry = 
        query {
            for item in dc.Main.Products do
            where (item.ShipmentDate > newEntity.ShipmentDate)
            select item
        } |> Seq.toArray
```

As expression this is:
```
.Call $item.GetColumn("ShipmentDate ") > .Call .Constant<FSharp.Data.Sql.Common.SqlEntity>(FSharp.Data.Sql.Common.SqlEntity).GetColumn("ShipmentDate")
```

**Comment by pezipink** [comment]
I believe we are close to being able to do this already - we track the items bound inside the query via the tuple index thing, any other type that has GetColumns on it that is not one of these must be from outside?

Nice one on the removal of the "left hand side" artifical restiction

**Comment by Thorium** [comment]
The PR made is working: I just check that nodetype of GetColumns is a parameter, which means it is coming from the current lambda.

**Comment by pezipink** [comment]
Ah cool, I didn't actually look at it :)
