### ISSUE TITLE
Database table and column descriptions/comments to xml tooltips

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#385]
I was wondering in VS that what is a column for...

Feature request:
Some databases can have comments / descriptions in tables and columns. I want those to XML-tooltip-comments. Rather in a way that won't hurt the performance.

**Comment by Thorium** [comment]
This is kind of ready, but I need help with **Oracle** and **Postgresql** as I don't have those databases:
Can you un-comment method `__.GetTableDescription` and `__.GetColumnDescription` and test if it works.

Ping @colinbull and @janno-p

**Comment by Thorium** [comment]
![tooltips](http://i.imgur.com/WG1kuslg.png)

**Comment by Thorium** [comment]
String/varchar max-length may be interesting so that's also good to have to tooltip. So I included the datatype (and also max-length but not to Oracle or Postgresql).

**Comment by Thorium** [comment]
Done.

**Comment by pezipink** [comment]
Very nice :)
