### ISSUE TITLE
FS0078: Unable to find the file 'FSharp.Data.SQLProvider.dll' 

### ISSUE THREAD

**Issue by whitetigle** [fsprojects/SQLProvider#387]
### Description

I am trying to make a .fsx script work on linux. **This script already works well on Windows 10.**

I have installed SQLProvider on ubuntu via Paket.
When I load the script with fsharpi I get the following error: 

`FS0078: Unable to find the file 'FSharp.Data.SQLProvider.dll' in any of
[list of paths]
`

In the list of paths, the path to the dll is listed correctly. 

I am loading the library via 
```
#I @"../packages/SQLProvider/lib"
#r "FSharp.Data.SQLProvider.dll"
```

I have also testd with absolute paths. Neither work. It can't find the file.

I have other scripts that work well on the same machine and the same directory.

I have also verified that the dll exists in the correct path.

It seems just like the dll does not exists.

So I am a little bit stuck here. 

Would you have Any idea? 
Thanks in advance for your help!

### Related information 

* Used database: postgreSQL
* Operating system: ubuntu
* Branch: nuget
* Mono Version: 4.2.1

**Comment by whitetigle** [comment]
It seems the build is failing on linux: https://travis-ci.org/fsprojects/SQLProvider 
Does it mean the .dll in the nuget package works only in windows?

**Comment by whitetigle** [comment]
Ok after I asked on slack, I finally managed to make it work using:

`#r @"../packages/SQLProvider/lib/FSharp.Data.SqlProvider.dll"`

**Comment by Thorium** [comment]
Please make a PR or suggest some additions to the documentation if something is missing. :-)
