### ISSUE TITLE
Impossible to use the "in" operator on a column substring?

### ISSUE THREAD

**Issue by josselinauguste** [fsprojects/SQLProvider#388]
### Description

I'd like to test if a substring of a column is included in an array of values (cf. repro steps), and it seems that it is not possible with the current version of SQLProvider. I get the following error, which I can trace back to the sourcecode:

```
System.Exception: Unsupported expression. Ensure all server-side objects won't have any .NET-operators/methods that can't be converted to SQL. The In and Not In operators only support the inline array syntax. (get_IsSome
(user.GetColumnOption("cp")) AndAlso op_BarEqualsBar(user.GetColumnOption("cp").Value.Substring(0, 2), new [] {"19", "23", "87", "33", "64", "24", "40", "47", "16", "17", "79", "86"}))
  at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation (Microsoft.FSharp.Quotations.FSharpExpr e) [0x000c7] in <58b68702dff9fae1a74503830287b658>:0
  at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner (Microsoft.FSharp.Linq.QueryModule+CanEliminate canElim, Microsoft.FSharp.Quotations.FSharpExpr queryProducingSequence) [0x00011] in <58b68702dff9fae1a74503830287
b658>:0
```

I'd like to know if this behaviour is expected, or if it is a bug or a missing feature? I guess I could find some time to try to fix this if you think it is relevant.

### Repro steps

This query returns the previous error when run:

```
query {
  for user in ctx.Db.Users do
  where
    (user.Cp.IsSome && user.Cp.Value.Substring(0, 2) |=| [| "33"; "86" |])
  select (user.Name)
}
```

### Related information 

* Used database : MySQL 5.5
* Operating system : macOS Sierra
* Branch : version 1.0.47 from nuget
* .NET Runtime, CoreCLR or Mono Version : Mono 4.8.0

**Comment by Thorium** [comment]
Yes, you have to think a bit more SQL-like approach.

This  is because we don't translate .NET functions like `Substring()` to SQL. I don't know if there even exist standard SQL-operation for splitting a string. Instead of in-operator `|=|` you should use like-operator `=%`:
`(user.Cp.IsSome && (user.Cp.Value =% "33%" || user.Cp.Value =% "86%")`
which would say in SQL `user.Cp like '33%'` which is somewhat "starts with" that you are looking for.

Would your operation have decent amount of possibilities to survive with OR instead of IN?

**Comment by Thorium** [comment]
There is non-standard-MID function in MySQL, but MySQL probably can't use index to perform the string concatenations, nor LIKE-searches, so your operation will be slow if you have a lot of data. More performant solution would be adding a separate column to database containing only the searched first two character values and then you can use IN.

**Comment by josselinauguste** [comment]
In that specific case I could indeed use a bunch of `LIKE`, but I'm afraid it will not always be possible. Here I use F# as a tool to crunch data in a legacy database, so my use cases rarely match those of my domain, and I would prefer not to evolve the schema as I am not the primary consumer of the DB. That's where string manipulation functions come in handy.

**Comment by Thorium** [comment]
Please try with the latest version (either master-branch or 1.0.55 from NuGet).

**Comment by josselinauguste** [comment]
It just works, thanks a lot!

When I see your PR, I have to admit I would have had a lot of difficulties to implement it!
