### ISSUE TITLE
SQL Server String Operations

### ISSUE THREAD

**Issue by adam-becker** [fsprojects/SQLProvider#390]
This is more of a question than anything else. Are there any plans to support the SQL Server string operations - Left, Right, Substring, etc?

I have plenty of queries that use these, and the only workable solution at the moment is to create an SP that does the query and call that using this library. However I've run into a case where I'm not allowed to create an SP on the database I'm querying.

Example:

```fsharp
    select
      { Field1 = e.Id;
        Field2 =
          if (e.Id =% "[0-9]%_[0-9]%" && e.Id <>% "%_0[0-9]%") ||
             (e.Id =% "%_[0-9]%_0%")
          then Left( e.Id, 5 )
          else e.Id;
      }
```

I don't see any way to accomplish the same thing without these string operations.

**Comment by Thorium** [comment]
Good question!

There would be string operations to different providers available. I'm not big fan of that. But what would you / our users think?

Pros:

* Get things done on some non-common use-cases
* To do this now you have to either duplicating data in database (to have partial strings in some separate column) or create a procedure

Cons:

* Will even more blur the line of .NET and SQL, what is supported, and what is executed and where.
* May cause queries not to hit database indexes, so the queries would be slow on large tables.
* We couldn't create here a compile-time verification anyways
* May not be standard, so the functionality may differ a bit on each provider.
* Solving string-parsing problems in 2017 is usually sign of poor domain modelling.

Related to #388

**Comment by adam-becker** [comment]
I wouldn't mind seeing database specific operations exposed in their own modules. Projects like Xamarin attempt to create a flat API surface for all devices, but still expose device specific functionality if you want to use it.

When working with a database, you know which database you're accessing. It's akin to storing a connection string which are typically database specific, so I don't see any problems with this sort of thing. Something like this:

```fsharp
namespace FSharp.Data.Sql.IntrinsicFunctions

module SqlServer =
  let left str count = ...
  let right str count = ...
  let substring str start count = ...
```

Calling them intrinsics, and placing them inside database specific modules I think keeps the line between .NET and SQL in focus. The blurring tends to happen when existing .NET functions are automatically translated behind the scenes, which I dislike as well. If you saw the following code, you'd be able to tell that the code is a SQL function:

```fsharp
select
  { Field1 = SqlServer.left item.Column 5;
    Field2 = "";
  }
```

I think type safety is still possible too, the signature would look like:

```fsharp
val left : string -> int -> string
```

Unless you meant something else?

I agree that parsing string like this is bad practice, but you don't always have control over the database you're working with :smile: Which is what lead me to ask this question in the first place!

**Comment by josselinauguste** [comment]
Can't agree more with Adam. We all know that for historical reasons basic string manipulation functions are not standard in SQL, but sadly these are extremely useful, particularly when handling legacy databases.

In addition, as developers we already have to handle the complexity of using different SQL dialects, so translating that complexity to SQLProvider does not seem that strange to me. At last this complexity may be contained in specific modules, which is still cleaner than the way SQL handles it. And a good documentation + the awesomeness of intellisense will also ease the understanding for the developers.

**Comment by Thorium** [comment]
On a side-note, `select` should do SQL select-clause first and then you should be able to do .NET operations, e.g. `select item.Id.Substring(2,0)` does select the whole Id and the substring-part is done on .NET-side. This is how SQLProvider works now and this is also how e.g. EntityFramework works.

The case with `where` clause is different, there the condition `where (item.Id.Substring(2,0) = "aa")` can't be evaluated on .NET-side and should have to be converted to part of SQL-clause (which is not done right now).

**Comment by adam-becker** [comment]
@Thorium I think this should have a consistent API regardless of what portion of the query body you're writing in. Having to remember that a `select` runs locally, while a `where` doesn't is kind of odd. As far as intuition goes, anything between the braces of the `query { ... }` expression could (and IMO, should) run on the server, the cat might be out of the bag on that issue however.

Is it not possible to just write "stub" functions that the query translator can look for and replace with the equivalent SQL code for the given provider? That's how I would expect something like this to work, but I am out of my league here :smile:

**Comment by Thorium** [comment]
We have started to go with LINQ so for consistency reasons it may be good to stick with that. The problem with stub-functions are that people don't know them, don't find them, and cannot expect how they work. They are hard to test as they can't be run standalone here. 

Currently `where` clause is a) first optimized away a bit (e.g. if there are `if(true)then a else b` we know that b is never used, and b) then transformed to SQL. The transformation is done in `parseWhere` function in `SqlRuntime.Linq.fs`, and it basically uses multi-layer-active-patterns to identify patterns from the LINQ-expression-tree. That we parse before executing the query.

But the `select` is working differently. It's done in `SqlRuntime.QueryExpression.fs`. It goes through the .NET-expression-tree in select-clause and finds the "holes" in expression, which are the SQL-parameters, and then it says that ok, let's fill the holes with the columns returned from the SQL result. The other parts of expression is still run as .NET expression. 

This technique is not unique to SQLProvider, other ORM-like-tools use the same, to give user the best possible usability. For more information, this was a good blog-series:
"LINQ: Building an IQueryable Provider" https://blogs.msdn.microsoft.com/mattwar/page/3/

**Comment by pezipink** [comment]
+1

At the moment it is not easily possible to compile expressions from the projection into the server side SQL code.  It is doable, but we would need to do an extra analysis step on the projection tree and "promote" some expressions into the query compiler layer - the actual projection transformer would then need to be aware of this so it could transform the end projection to match up with what the server returns.  

Not a 5 minute job! :)  a fun one though! (right?!)

Also on the original issue - I am on the fence with it.  Linq already has the problem of people not knowing what is supported and what isn't so adding string projection functions probably wouldn't be the end of the world, although it is just compounding the issue and making it worse. Of course its terrible bb design but you don't get to choose the dbs you work with....

**Comment by pezipink** [comment]
@adam-becker 

>  As far as intuition goes, anything between the braces of the query { ... } expression could (and IMO, should) run on the server

In principle I agree, however running the projection client side is entirely normal.  The reason is simple - you would be massively restricted to what you could put in the projection if we said it had to run server side. Only functions we directly supported would work, and you wouldn't be able to do other stuff like create tuples, records, etc etc.  At the moment pretty much any expression will work in that slot which is a huge win.

**Comment by Thorium** [comment]
I'm not doing substring now as I don't need it, I'm very happy with SQLProvider currently. But if you want to try, I can give some help to get started, though I have to warn you that SQLProvider is quite scary code base.

First you write some test, let's say...
```fsharp
[<Test>]
let ``simple select with substring in where``() =
    let dc = sql.GetDataContext()
    let qry = 
        query {
            for cust in dc.Main.Customers do
			// "London"
            where (cust.City.Substring(1,2) = "on")
            select cust.City
        } |> Seq.toList
    Assert.IsNotNull(qry)
    Assert.AreEqual("on", (qry |> Seq.head).Substring(1,2))
```

There are two overrides for substring and the corresponding SQL-functionality should be possible.
You probably first need a new active-pattern. That can be done in many ways, but something like this should do:

```fsharp
let (|SubstringFunction|_|) = function
    | MethodCall(Some(SqlColumnGet(ti,key,_)), MethodWithName "Substring", [e]) -> 
        match e with
        | :? ConstantExpression as ce -> 
            let ok,v1 = Int32.TryParse (ce.Value.ToString())
            if ok then Some (ti, key, v1, None) else None
        | _ -> None
    | MethodCall(Some(SqlColumnGet(ti,key,_)), MethodWithName "Substring", [e1;e2]) -> 
        match e1, e2 with
        | (:? ConstantExpression as ce1), (:? ConstantExpression as ce2) -> 
            let ok1,v1 = Int32.TryParse (ce1.Value.ToString())
            let ok2,v2 = Int32.TryParse (ce2.Value.ToString())
            if ok1 && ok2 then Some (ti, key, v1, Some(v2))
            else None
        | _ -> None
    | _ -> None
```

Then you need some more active patterns to use this pattern. How to combine that with nice places to the existing active-pattern-layers...is kind of question that where do we want to support this. Currently the data goes as ConditionOperator datatype and boxed object to provider-implementations, but you have free hands here.

Then when parsing the query in each provider:

### .NET

The two overrides:

```fsharp
col.Substring(startpos)
col.Substring(startpos, lenval)
```

### MS-Access

```fsharp
match lenval with
| None -> (sprintf "MID([%s].[%s], %i)") alias col startpos
| Some x -> (sprintf "MID([%s].[%s], %i, %i)") alias col startpos x
```

### MS-SQLServer

```fsharp
match lenval with
| None -> (sprintf "SUBSTRING([%s].[%s], %i)") alias col startpos
| Some x -> (sprintf "SUBSTRING([%s].[%s], %i, %i)") alias col startpos x
```

### MySQL

```fsharp
match lenval with
| None -> (sprintf "MID(`%s`.`%s`, %i)") alias col startpos
| Some x -> (sprintf "MID(`%s`.`%s`, %i, %i)") alias col startpos x
```

### Odbc

```fsharp
match lenval with
| None -> (sprintf "SUBSTRING(%c%s%s%s%c, %i)") cOpen alias separator col cClose startpos
| Some x -> (sprintf "SUBSTRING(%c%s%s%s%c, %i, %i)") cOpen alias separator col cClose startpos x
```

### Oracle

```fsharp
match lenval with
| None -> (sprintf "SUBSTR(%s.%s, %i)") alias col startpos
| Some x -> (sprintf "SUBSTR(%s.%s, %i, %i)") alias col startpos x
```

### Postgres

```fsharp
match lenval with
| None -> (sprintf "SUBSTRING(\"%s\".\"%s\" from %i)") alias col startpos
| Some x -> (sprintf "SUBSTRING(\"%s\".\"%s\" from %i for %i)") alias col startpos x
```

### SQLite

```fsharp
match lenval with
| None -> (sprintf "SUBSTR([%s].[%s], %i)") alias col startpos
| Some x -> (sprintf "SUBSTR([%s].[%s], %i, %i)") alias col startpos x
```

**Comment by Thorium** [comment]
If we could modify the select-lambda easily, it would be nice to transfer if-else or pattern-match of columns to quite standard SQL-case-clauses, e.g. `select (if column1 = 2 then column2 else column3 )` to 

```sql
SELECT
    CASE column1
    WHEN 2 THEN column2
    ELSE column3
    END
FROM ...
```
...as some corss-join-cases SQL-engines are able to optimize the case-queries quite well.
But again, I don't have need for this now.

**Comment by pezipink** [comment]
it's just as easy / hard as anything else with this stuff..

>  I have to warn you that SQLProvider is quite scary code base.

You love it!  :)

**Comment by Thorium** [comment]
It was just a random thought that maybe we should create a guide for people to get started without spending initial 2 hours by restarting the visual studio without any positive achievements.

**Comment by pezipink** [comment]
I approve of this idea 100% !

**Comment by adam-becker** [comment]
@Thorium Thanks for the explanation of the technical details! As always, my idealism doesn't match up with reality :laughing: I support the idea of adding case clauses to the select output, perhaps I'll take a look at the code and start fiddling with it.

@pezipink Thank you also for the rationale as well, I personally don't have any problems with being restricted in what is allowed inside the `query { ... }` expression. My ideal world would be doing something like this if I needed to project results:

```fsharp
let serverQuery = query {
  for book in ctx.Dbo.Books do
  where book.ISBN.IsSome
  select // server side projection here
    { name = book.Name;
      firstWordOfName = SqlServer.left( SqlServer.charIndex( ' ' ) )
      author = book.Author;
    }
}
in
  serverQuery
  |> Seq.filter (fun book -> (* client side filtering here *))
  |> Seq.map (fun book -> (* client side projection here *))
  |> Seq.toList
```

It may look cumbersome, but there's a clear separation between what is running on the server, and what is running on the client.

That said, I really enjoy writing code using SQL Provider, I'll look into making a PR this weekend!

**Comment by Thorium** [comment]
Ok, here is some tech documentation:
http://fsprojects.github.io/SQLProvider/core/techdetails.html
[(markdown)](https://github.com/fsprojects/SQLProvider/blob/master/docs/content/core/techdetails.fsx)

I know it will get expired, but it's still better than nothing.

@pezipink if you have some key-points, please add, I remember you even had some presentation of SQLProvider.

**Comment by josselinauguste** [comment]
Thanks everyone for all the pointers, I'll try to add the `substring` support to the `where` clause as soon as I can! (but certainly not before a week or so, because next week I'll be on vacation)

**Comment by Thorium** [comment]
I was thinking about this when I needed a `where (myDateTime.Date.AddDays(1.) > DateTime.UtcNow.Date)`

So `|SqlColumnGet|` things should gather instead of `(String.Empty,key,meth.ReturnType)` a new type of

```fsharp
type ColumnTypes =
| NormalColumn(String.Empty,key,meth.ReturnType)
| CanonicalOperation(String.Empty,key,meth.ReturnType, operation, params)
```

What canonical operations could be supported?
Well, Devart has managed to support these for their entity framework driver:
https://www.devart.com/dotconnect/db2/docs/CanonicalFunctions.html

But I say we should start from commonly used ones, 
and document those to a list of supported ones.:

- For strings: 
   - Substring, 
   - Concat,
   - toUpper, toLower
   - Trim
   - StartsWith and EndsWith, but I think they already are covered by LIKE.
- For numerics: 
   - Abs, 
   - Basic arithmetics (add,substract,multiply,divide)
   - Somekind of rounding for decimals 
- For dates: 
   - Day,Month,Year, 
   - And adding them. 
   - Removing time-component

**Comment by Thorium** [comment]
I tried this quickly yesterday and it seems that it's needing some major refactoring:
We currently transfer item `alias, columnName` and then providers transfer those to their custom `sprintf "[%s].[%s]" alias columnName` or `sprintf "\"%s\".\"%s\"" alias columnName` or whatever. The canocical operation `[alias].[ABS(columnName)]` would be wrong, the correct should be `ABS([alias].[columnName])`. So we would need actually a new data structure (recursive as `SUBSTRING(TRIM(...))` is valid) to transfer the logic structures. So it might be a good idea tor replace those provider specific sprint-clauses with formatter-functions, just one per provider.

So I think this would need a new branch and a lot of testing. The good thing with this is that current group-by having-aggregates could actually be combined with the new data structure.

**Comment by Thorium** [comment]
Substring support for where-clauses, joins, sortbys implemented in latest master and NuGet 1.0.55. But related to the original question, selection does still use the whole projection lambda. So while it works, the parsing is done in the .NET-side and not in the SQL-server.

But I think it could be transferred partially to SQL-server side. 

The functionality interesting for select is somewhat different than e.g. for where. Useful could be to limit the result-set: if-then-else (SQL Case-when) if you want to return just a few columns, and limiting some large column content with substring/replace/indexof. But e.g. date-functions and numerical math is not so useful as they can be done on .NET side.

**Comment by Thorium** [comment]
The problem to support the `case` in select is:

Currently we either select some columns or the whole entity. That is pretty forward to know which columns are already selected so we don't have to duplicate those in the select clause. 
But how to know what is efficient SQL-clause if we could allow select cases. 

An example, let's assume COL3 is a long text that is slow to transfer over a wire from database to the business logics server.

```fsharp
query {
   for rows in table
   select
      rows.Col1, rows.Col2, rows.Col3
      (if rows.Col2 > 5 then rows.Col3 else rows.Col4), rows.Col5
}
```

Currently does:

```sql
SELECT COL1, COL2, COL3, COL4, COL5 FROM TABLE
```

But could do:

```sql
SELECT COL1, COL2, COL3, (CASE WHEN COL2 > 5 THEN COL3 ELSE COL4), COL5 FROM TABLE
```

The later is efficient only if COL2 is less than 6 and COL4 is also a long text content. 
Otherwise it's just duplicating the select COL3 in the projection, which make it perform worse than the previous case.

So how do we know from the selection projection that will all the needed columns be already in the selection lambda, so should we try a select-case or not? The case might not be the last column of a projection, and there can be multiple cases.

**Comment by adam-becker** [comment]
I tend to prefer a `WYSIWYG` style of mapping. I'm perfectly happy to accept less performance on a piece of code that is doing more things, I think that's a valid assumption to make.

There's no way you can figure out that a certain column will be slower in a general manner, I think optimizations like these are best left to the consumer. I also don't think this scenario invalidates allowing `case` statements in a select.

**Comment by Thorium** [comment]
Another one, we fetch a dictionary of name*obj representing the column name and column value. But what is a name of a canonical function?

```fsharp
query {
   for rows in table
   select
      (if rows.Col1 > 5 then rows.Col2 else rows.Col3),
      (if rows.Col1 > 5 then rows.Col2 else rows.Col3),
      (if rows.Col1 > 5 then rows.Col2+1 else rows.Col3)
}
```
would be
```sql
SELECT
   (CASE WHEN COL1 > 5 THEN COL2 ELSE COL3) AS SOMETHING,
   (CASE WHEN COL1 > 5 THEN COL2+1 ELSE COL3) AS SOMETHING2,
FROM TABLE
```
...so maybe a hash-code over a function so that something would be a canonical_col2943534 so that it wouldn't be messed with original columns.

**Comment by Thorium** [comment]
Having a look for this a bit further, the current Condition-pattern shouldn’t be inside where-filter-clause as case-clause will need it also. The current canonical operations should be modified to transfer parameters also. Then the current projectionMap of strings (column names) should be a discriminated union of either columns or a canonical-operation-tree.

**Comment by Thorium** [comment]
Done, you can control this with: http://fsprojects.github.io/SQLProvider/core/querying.html#SelectOperations-DatabaseSide

**Comment by adam-becker** [comment]
@Thorium this looks very nice, good work! One of the things that jumped out at me (and this may need to be a separate issue) is `Start position may vary (0 or 1 based.)`

Is there a way that the library could provide some insulation against this? `fromZeroBased/fromOneBased` or something similar? Or is this something the consumer of SQLProvider will just have to work around?

**Comment by Thorium** [comment]
Either way, zero or -1, won't make everyone happy. I think the average SQLProvider user might have already some learning curve with Linq syntax, and know his/her SQL database quite well, so the best way to handle this could be avoiding magic and having some documentation.

**Comment by adam-becker** [comment]
I was thinking just make the public API work with all zero-based indices and let the library translate to one-based where appropriate.

I guess the use case of "we switched the backend to a completely different SQL flavor but we want the same exact application code" probably doesn't occur all that often.
