### ISSUE TITLE
Can't join a DB table with a result of another query

### ISSUE THREAD

**Issue by ArtemyB** [fsprojects/SQLProvider#396]
### Description

Can't join oa DB table with an `IQueryable` produced by another query. As a result of this I get `System.Exception: Unexpected join destination entity expression`.

**P.S.**: Seems like a problem exists even while joining only query results (not only query result + DB-table).

### Repro steps

Just a very simple example:
```
let q1 =
    query {
        for x in ctx.Dbo.TblXs do
        select x
    }
let q2 =
    query {
        for sample in ctx.Dbo.TblSamples do
        join x in q1 on (sample.Id = x.SampleId)
        select sample
    }
```

### Expected behavior

A normal query output(`IQueryable`) as it is for one big query directly to the DB-tables (not to another queries' resulting `IQueryable`s).

### Actual behavior

```
System.Exception: Unexpected join destination entity expression (FSharp.Data.Sql.Common.SqlExp+FilterClause).
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.clo@1730-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at <StartupCode$FSI_0023>.$FSI_0023.main@()
Stopped due to error
```
### Known workarounds

Don't split the query on multiple smaller queries to compose them later (what is not always convenient).

### Related information 

* Microsoft SQL Server 2014
* Windows 10 Home, 64-bit
* .NET 4.5.2, F# 4.1

**Comment by Thorium** [comment]
Currently not supported, as we support only one select-lambda... How complex is your real use-case?

**Comment by Thorium** [comment]
However you can do Sysrem.Linq .Contains-operation to another IQueryable, resulting to a nested query.

**Comment by ArtemyB** [comment]
@Thorium -

> How complex is your real use-case?

Not very. But an ability to have queries-to-queries is a helpful feature. I use it quite a lot im my case. Plus I also use  `groupBy`-expression, which is now also an issue for SQLProvider as I discovered. However as I'm working with SQL Server I can use FSharp.Data.Typeproviders, which solves my problem for now.

Thanks for the answer! 🙂

**Comment by Thorium** [comment]
Yes, if you have complex SQL-clauses, it's probably good to have manual control over them anyways.

**Comment by octaviordz** [comment]
Is there any document describing current limitations of "query expression" being used against MSSQL, 
Thanks.

**Comment by Thorium** [comment]
http://fsprojects.github.io/SQLProvider/core/querying.html#Supported-Query-Expression-Keywords

**Comment by Thorium** [comment]
I think this is expired, I think you can do this now.
