### ISSUE TITLE
InvalidOperationException evaluating expression using where (true) after join in query expresion

### ISSUE THREAD

**Issue by bennylynch** [fsprojects/SQLProvider#406]
### Description

A query such as 

    let failingQry = 
        query {
            for tbl1 in ctx.Dbo.Table1 do
            join tbl2 in ctx.Dbo.Table2 on (tbl1.Tbl1Id = tbl2.Tbl1Id)
            where (true)
            select tbl1
        }

throws an exception
```
    > System.InvalidOperationException: Sequence contains no elements
       at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
       at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
       at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
       at Microsoft.FSharp.Linq.QueryModule.clo@1730-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr1 )
       at <StartupCode$FSI_0002>.$FSI_0002.main@() in F:\code_root\vs2017\F\SampleTracker\scratch.fsx:line 125
```
### Repro steps
1. Step A
Create 2 tables, one with a FK to the other:
```
    CREATE TABLE [dbo].[table1](
	    [Tbl1ID] [int] IDENTITY(1,1) NOT NULL,
	    [TblData] [varchar](50) NOT NULL,
     CONSTRAINT [PK_table1] PRIMARY KEY CLUSTERED ([Tbl1ID] ASC)
    ) ON [PRIMARY]

    GO
    CREATE TABLE [dbo].[table2](
	    [Tbl2Id] [int] IDENTITY(1,1) NOT NULL,
	    [Tbl1Id] [int] NOT NULL,
	    [Tbl2Data] [varchar](50) NOT NULL,
     CONSTRAINT [PK_table2] PRIMARY KEY CLUSTERED ([Tbl2Id] ASC)
    ) ON [PRIMARY]

    GO
    SET ANSI_PADDING OFF
    GO
    ALTER TABLE [dbo].[table2]  WITH CHECK ADD  CONSTRAINT [FK_table2_table1] FOREIGN KEY([Tbl1Id])
    REFERENCES [dbo].[table1] ([Tbl1ID])
    GO
    ALTER TABLE [dbo].[table2] CHECK CONSTRAINT [FK_table2_table1]
    GO
```

2. Step B
Run the following, in FSI (connection string edited appropriately, obvs ..)
```
    type Db = SqlDataProvider<ConnectionString="Data Source =.;Initial catalog='test';Integrated Security=SSPI",DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER>
    let ctx = Db.GetDataContext()
    let failingQry = 
        query {
            for tbl1 in ctx.Dbo.Table1 do
            join tbl2 in ctx.Dbo.Table2 on (tbl1.Tbl1Id = tbl2.Tbl1Id)
            where (true)
            select tbl1
        }
```

### Expected behavior

Expression evaluated correctly, SQL generated & exectued, all joined rows retuned in returned result.

### Actual behavior

See above for exception.

### Known workarounds

Work around would be to leave out the where (true) condition; in my particular use case though, the 'where' was a spliced in quotation, based on conditions at runtime, either
`<@ fun (l:Tbl1Entity) -> true @>`
or
` <@ fun (l:Tbl1Entity) -> l.Tbl1Id= v @>`

### Related information 

* Used database
SQL server 11.0.6020.0
* Operating system
win10
* Branch
master
* .NET Runtime, CoreCLR or Mono Version
.net 4.5.2 f# 4.1
* Performance information, links to performance testing scripts

**Comment by bennylynch** [comment]
While having a look around to see if I could see where the problem might be, I noticed in SqlRuntime.Linq.fs, at line 416
```
                        | current ->
                            if isHaving then HavingClause(filter,current)
                            else

                            // the following case can happen with multiple where clauses when only a single entity is selected
                            if paramNames.First() = "" || source.TupleIndex.Count = 0 then FilterClause(filter,current)
                            else FilterClause(filter,current)
```
which seemed to me to be redundant. Commenting out the redundant if branch fixed this issue, although I've no idea why/how. And I see now that it has already been corrected in 'master',

[(https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/SqlRuntime.Linq.fs#L413)]

**Comment by Thorium** [comment]
Yes, I noticed the same few days ago, I don't know what that was, so I removed it.
That has been fixed at the latest NuGet package also.
