### ISSUE TITLE
Allow casts to IComparable in Lambdas passed to sortBy or sortByDescending.

### ISSUE THREAD

**Issue by nikonthethird** [fsprojects/SQLProvider#407]
Currently, the following query fails with an [unrecognized method call exception](https://github.com/fsprojects/SQLProvider/blob/3ebcceb2a4a15915c30178e762ae9ec451a8fc73/src/SQLProvider/SqlRuntime.Linq.fs#L753),
because the cast to `IComparable` inserts a `Convert` node into the expression which is not matched:

```fsharp
query {
    for item in db.Main.Items do
    sortBy ((fun (i : Db.dataContext.``main.ItemsEntity``) -> m.Id :> IComparable) item)
    select item
}
```

I propose to change [this line handling `sortBy` and `sortByDescending`](https://github.com/fsprojects/SQLProvider/blob/3ebcceb2a4a15915c30178e762ae9ec451a8fc73/src/SQLProvider/SqlRuntime.Linq.fs#L480) from

```fsharp
| MethodCall(None, (MethodWithName "OrderBy" | MethodWithName "OrderByDescending" as meth), [SourceWithQueryData source; OptionalQuote (Lambda([ParamName param], SqlColumnGet(entity,key,_))) ]) ->
```

this to

```fsharp
| MethodCall(None, (MethodWithName "OrderBy" | MethodWithName "OrderByDescending" as meth), [SourceWithQueryData source; OptionalQuote (Lambda([ParamName param], OptionalConvertOrTypeAs (SqlColumnGet(entity,key,_)))) ]) ->
```

this. The only change is the insertion of the `OptionalConvertOrTypeAs` recognizer before the `SqlColumnGet` recognizer, which allows the query above to pass.
The same change should also be made to [the line handling `thenBy` and `thenByDescending`](https://github.com/fsprojects/SQLProvider/blob/3ebcceb2a4a15915c30178e762ae9ec451a8fc73/src/SQLProvider/SqlRuntime.Linq.fs#L495):

```fsharp
| MethodCall(None, (MethodWithName "ThenBy" | MethodWithName "ThenByDescending" as meth), [SourceWithQueryData source; OptionalQuote (Lambda([ParamName param], OptionalConvertOrTypeAs (SqlColumnGet(entity,key,_)))) ]) ->
```

**I should mention that the `Convert` node is only inserted for value types that have to be boxed!
Casting a `string` to `IComparable` does not affect the resulting expression.**

## Reason why this would be helpful:

Currently, it is not possible to splice in a lambda for `sortBy` or `sortByDescending` into a query:

```fsharp
// The cast to IComparable is necessary for type checking
// (Expr<Db.dataContext.``main.ItemsEntity`` -> IComparable).
let sortBy =
    match sortArg with
    | "name" -> <@ fun (x : Db.dataContext.``main.ItemsEntity``) -> m.Name :> IComparable @>
    | "id" -> <@ fun (x : Db.dataContext.``main.ItemsEntity``) -> m.Id :> IComparable @>
    | _ -> failwith "invalid arg to sort by"

let quotedQuery = <@ query {
    for item in db.Main.Items do
    sortBy ((%sortBy) item)
    select item
} @>
```

Would this be an acceptable enhancement and should I open a pull request for it?

**Comment by Thorium** [comment]
Yes of course, thanks!
