### ISSUE TITLE
String Length in Oracle Query does not work

### ISSUE THREAD

**Issue by hoetz** [fsprojects/SQLProvider#408]
### Description

```
let employeeQuery= 
            query {
                for emp in ctx.db.Peopletable do
                    where (emp.AdsLogin.Length>0)
                    select emp
            }
```

This results in an exception. I am using the latest Oracle.ManagedDataAccess package from nuget.
Details:
System.Exception occurred
  HResult=0x80131500
  Message=Unsupported expression. Ensure all server-side objects won't have any .NET-operators/methods that can't be converted to SQL. The In and Not In operators only support the inline array syntax. (emp.GetColumn("ADS_LOGIN").Length > 0)
  Source=FSharp.Core
  StackTrace:
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
   at Microsoft.FSharp.Linq.QueryModule.clo@1730-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at Program.main(String[] argv)

**Comment by Thorium** [comment]
Hello, this support came in SQLProvider's latest version, (Nuget 1.0.55). Are you using that?

**Comment by hoetz** [comment]
Ah, I was on 1.0.54 :)
Works!

**Comment by hoetz** [comment]
Have to re-open this. Now I get

-		$exception	{"ORA-00904: \"CHAR_LENGTH\": invalid identifier"}	Oracle.ManagedDataAccess.Client.OracleException

For Oracle it should convert to the LENGTH function

**Comment by Thorium** [comment]
Ok, good, I'll fix. This is very new functionality. If you have Oracle available and can do a database from script `src/DatabaseScripts/Oracle/oracle_provider_test_db.sql`
can you also run test SQLProvider.Tests.sln OracleTests.fsx line 72: canonicalTest ? :-)

**Comment by colinbull** [comment]
I have fixed this already, just about to send a PR. `TRIM` was also failing.

**Comment by Thorium** [comment]
Oh, sorry I was faster. :-) Need the Trim though.

**Comment by colinbull** [comment]
I'll pull your fix and test again..

**Comment by colinbull** [comment]
Lol, actually scratch that gotta go to a meeting now.. but I'll have time again tomorrow.

**Comment by hoetz** [comment]
I am up in the air at the moment but I will definitely test those fixes on my DB later.

**Comment by hoetz** [comment]
Confirmed working on 1.0.56

**Comment by Thorium** [comment]
Good. But update to 1.0.57 as the fix introduced some regression of duplicate alias resolving, and I don't want to get bugs of that. ;-) 1.0.57 is working perfectly, I already have it in production.
