### ISSUE TITLE
Document quotation usage in composable queries

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/SQLProvider#418]
While playing with FSharp.Composable.Linq I've found [a bug](https://github.com/fsprojects/FSharp.Linq.ComposableQuery/issues/15). In the comments section, @jamescheney mentioned that SQLProvider already supports some of the features I need. It was a surprise, because the relevant documentation on [Composable Queries](https://fsprojects.github.io/SQLProvider/core/composable.html) doesn't mention the quotation usage at all.

I think that use of quotations in composable queries is a major feature, and we should update the documentation with quotation samples. Here's a sample draft:

```fsharp
// create table dbo.Users(Id Int primary key, Name NVarChar(max), Role NVarChar(max))
// insert into dbo.Users(Id, Name, Role) values (1, N'Peter', N'Admin')
// insert into dbo.Users(Id, Name, Role) values (2, N'Peter', N'User')
// insert into dbo.Users(Id, Name, Role) values (3, N'Igor', N'Admin')

open FSharp.Data.Sql
type Database = SqlDataProvider<ConnectionString = "Data Source=.\SQLEXPRESS;Initial Catalog=FSharpLinqTest;Integrated Security=True">
type User = Database.dataContext.``dbo.UsersEntity``

let printUser (u : User) = printfn "- %s: %s" u.Name u.Role

[<EntryPoint>]
let main argv = 
    let context = Database.GetDataContext()    
    let users = context.Dbo.Users

    let peter = <@ fun (u : User) -> u.Name = "Peter" @>
    let admin = <@ fun (u : User) -> u.Role = "Admin" @>

    printfn "All users:"
    query { for u in users do yield u }
    |> Seq.iter printUser // Peter, Peter, Igor

    printfn "\nUsers of role Admin named Peter:"
    query { for u in users do if (%admin) u && (%peter) u then yield u }
    |> Seq.iter printUser // Peter

    0
```

**Comment by jamescheney** [comment]
> It was a surprise, because the relevant documentation on Composable Queries doesn't mention the quotation usage at all.

Just to be clear, I was speculating here because the ComposableQueries documentation page says it is not necessary to `open FSharpComposableQuery` because `SQLProvider` already provides the same/similar features.

I believe some particular instances of query composition would work in plain F# LINQ (perhaps including the above); but I don't know which ones.  The point of FSharpComposableQuery was to provide an algorithm that comes with a guarantee about when query composition will work (namely, it should work for plain "conjunctive queries" or unions of them; things like aggregation/grouping may also work but are not covered by the theory).

It would be good to know what capabilities of FSharpComposableQuery are supported in SQLProvider, and if any are missing I would be happy to help explain / adapt the code (if SQLProvider is the right place for this, as opposed to `Microsoft.FSharp.Linq`).

**Comment by Thorium** [comment]
There are two expression types in F#: `Expression<>` (System.Linq.Expressions) and F#-expressions `Expr<>`. Now what you are trying to do is to mix these together. But SQLProvider doesn't support `Expr<>`.

So before using your expression, you have to convert it to LINQ-expression, e.g. like [this](http://www.fssnip.net/ts/title/F-lambda-to-C-LINQ-Expression). I'm not familiar with FSharp.Linq.ComposableQuery, shouldn't it flatten out those nested expressions?

We would gladly accept PRs to improve our documentation, however it seems not many people use `FSharp.Linq.ComposableQuery` and I don't know how actively it's maintained.

I had kind of similar problem, I needed "a generic complex group-by-query". I ended up doing a view to SQL-server and then I'm just querying the view with where-filters from SQLProvider. I hope the caching is also working better this way.

**Comment by ForNeVeR** [comment]
@Thorium please note that here I'm not talking about `ComposableQuery` at all. I'm aware that I'm using F# `Expr<>`, and it works well with `SqlProvider` (without any additional libraries)!

So I'm now confused. Isn't it supposed to work?

**Comment by Thorium** [comment]
Oh, ok, good, I didin't know. :-)
Let's add that to the docs then. Do you want to do a PR?

**Comment by ForNeVeR** [comment]
If nobody else is planning to add this to the documentation, I'll be happy to do it eventually (probably this week).

**Comment by pezipink** [comment]
@Thorium this also works as expected with the normal builder syntax (since it ends up the same) eg

```fsharp
query { for x in dc.Security.User do 
        where ((%admin) x )
        select x } |> Seq.toList
```
