### ISSUE TITLE
PostgreSQL test database?

### ISSUE THREAD

**Issue by piaste** [fsprojects/SQLProvider#419]
I'm preparing a pull request that will add support for PostgreSQL array columns ([branch here](https://github.com/fsprojects/SQLProvider/compare/master...piaste:master_new), not quite finished yet).

I'm trying to run the included test suite before submitting, but I'm not sure which database I'm supposed to use with the included Postgres test script.

When I use sample Northwind database schemas I find on the web (eg first google result https://github.com/pthom/northwind_psql), the test script errors out due to different casing conventions.

Is there a schema dump I can use somewhere? Should I import the SQLite .db file in /tests/SqlProvider.Tests/db/ ? Or should I just fix the casing mismatch in the Northwind schema I linked?

Thank you

**Comment by Thorium** [comment]
`/src/DatabaseScripts/PostgreSQL`

**Comment by piaste** [comment]
Thanks!
