### ISSUE TITLE
dotnetcore support?

### ISSUE THREAD

**Issue by hveiras** [fsprojects/SQLProvider#426]
Hi,

Sorry to file this as an issue I didn't find an email or other way to communicate.

Can this provider be used with net core?

I'm getting this error when adding the package

error: Package SQLProvider 1.1.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package SQLProvider 1.1.3 supports: net (.NETFramework,Version=v0.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.1.

**Comment by ForNeVeR** [comment]
Hello. See https://github.com/fsprojects/SQLProvider/issues/303

I don't think that .NET Core supports type providers currently. They will be supported after .NET Core 2.0 release.

**Comment by Thorium** [comment]
This is erasing typeprovider so in theory it could be done already with 1.6 by excluding providedtypes.fs and sqldesigntime.fs from the source code project. However this relies heavily on reflection and System.Data and other things that are missing some APIs in .NET Core. So that could be done with quite a lot of work. But if .NET Core 2.0 will support referencing old .NET libraries, and it will be released this summer, what is the point of now converting anything to .NET core?

**Comment by wklm** [comment]
Can I simply compile it to a dll and include into my netocre project?

**Comment by Thorium** [comment]
I think so, but I also think there is a lot of things to modify, and intellisense and tooling for FSharp .NET Standard is not yet good enough.
I made initial branch, you can try this:
https://github.com/fsprojects/SQLProvider/tree/netstandard
and `\src\SQLProvider.Standard\`

**Comment by dsyme** [comment]
You should first adjust the type provider to be a [cross-targeting type provider](https://github.com/fsprojects/FSharp.TypeProviders.StarterPack#the-providedtypes-api---cross-targeting-type-providers)

Then see https://github.com/Microsoft/visualfsharp/issues/3303

**Comment by charlesroddie** [comment]
Can we reopen this thread please? I dont believe that .Net Standard or Core support is ready. As shown by this comment:

> @Thorium https://github.com/fsprojects/SQLProvider/issues/547#issuecomment-387323900 To use type provider with .NET Standard you have to use compatible fsharp compiler and do the compilation with .Net451 version of SQLProvider.dll. On runtime you can use the .NET Standard dll.

@jsauer @monkieboy

**Comment by dsyme** [comment]
@Thorium I'd like to help you get the .NET Core 2.0 tooling type provider completed.  Has there been an attempt to do this here so far based on recent updates to the TPSDK and .NET Core F# compiler?

**Comment by Thorium** [comment]
We are using the latest TPSDK (ProvidedTypes.fs). 

However I haven't followed the recent .NET Core development, so I don't know if e.g. FscToolPath is still needed and do you still need a .NET framework version of typeprovider dll to compile .NET Core. 

The help documents reflect the situation about half year ago. People seem in general be able to use SQLProvider with .NET Core 2.0 even though the experience is not as out-of-the-box as .NET tends to be.
