### ISSUE TITLE
ConnectionStringName is not read when running application from a folder different from application folder

### ISSUE THREAD

**Issue by jbezak** [fsprojects/SQLProvider#428]
### Description

When running application from a different folder from application folder, typeProvider will try to look for app.config in current folder but not in the application folder resulting in TypeInitializationException.

### Repro steps

1. Define type provider with Connection string name in app.config
```
    let [<Literal>] dbVendor = Common.DatabaseProviderTypes.MSSQLSERVER
    let [<Literal>] connStringName = "DbConnection"

    type Sql = SqlDataProvider<dbVendor, ConnectionStringName = connStringName>
```

```
  <connectionStrings>
    <add name="DbConnection" connectionString="Server=locahost\local;Database=myDb;Integrated Security=SSPI" />
  </connectionStrings>

```
2. Run the application from a different folder with relative or absolute path to your application

### Known workarounds

Hardcode connection string

**Comment by Thorium** [comment]
Should work now (NuGet 1.1.4)
