### ISSUE TITLE
Real working examples for aggregate functions

### ISSUE THREAD

**Issue by fradav** [fsprojects/SQLProvider#429]
I can't figure how to use non trivial group/having with sqlprovider (sqlite) because there is no examples of it and the ones from Microsoft are not working (incompatible syntax).

For example, how to translate something as simple than "group by ts having count(ts) = 1 order by ts".

Regards,

**Comment by Thorium** [comment]
In general SQLProvider group by is quite limited, and it's quite hard to track will your generated queries hit the index, so if you have more complex scenarios, it's recommended to use a view and query that from SQLProvider.

That being said, the syntax is e.g. this:

```fsharp
open System.Linq
let cityFreights =
    query { 
        for order in ctx.Main.Orders do
        groupBy order.ShipCity into ts
        where (ts.Count() > 0)
        select (ts.Key, ts.Sum(fun o -> o.Freight))
    } |> Seq.toArray
```

Those doesn't have to be LINQ functions as long as they will generate corresponding expression-tree, but `open System.Linq` will just make your life easier.

**Comment by Thorium** [comment]
Also sortBy should work now (NuGet 1.1.4)

**Comment by fradav** [comment]
Thanks you very much, that's exactly what I wanted. I didn't understand the use of the IEnumerable extension inside the query, like the `ts.Sum(fun o -> o.Freight)`. 

Please consider to better document/exemplify  this in the main documentation.
