### ISSUE TITLE
Using "skip" clause with 0 value causes incorrect statement generation (MS SQL)

### ISSUE THREAD

**Issue by object** [fsprojects/SQLProvider#432]
### Description

We switched from FSharp.Data SQL Provider to SQLProvider and some queries that include "skip" count cause the following error:

**"Incorrect syntax near 'DESCOFFSET'.\r\nInvalid usage of the option NEXT in the FETCH statement."**

### Repro steps

Given the following F# query where skipCount is set to "0":

```
            query {
                for row in db.Dbo.EventJournal do
                where (row.PersistenceId = (sprintf "%s:%s" eventType eventId))
                groupBy row.PersistenceId into g
                sortBy g.Key
                skip skipCount
                take takeCount
                select g.Key
            }

```
The execution fails with the following error message:

**"Incorrect syntax near 'DESCOFFSET'.\r\nInvalid usage of the option NEXT in the FETCH statement."**

Workaround:
Removing "skip" and "take" clasues fixes the problem (perhaps just removing skip should be sufficient).

### Related information 

Microsoft SQL Server 2014
Any modern Windows OS

**Comment by Thorium** [comment]
sortBy+skip+take will generate as DESCOFFSET.  Actually I think this is a System.Data.dll problem and not SQLProvider. We are trying to support all SQLServer versions, but their paging features vary. 

One workaround could be that you just remove the skip and then do the skip after executing SQL, which will of course make a paging slow when you want to fetch a large page number.

**Comment by object** [comment]
Yes it looks like different flavours of SQL server expect different syntax. But I wonder if we can target at least recent versions. And moving skip/take out of the query is not an option for scenarios with large data sets.

Here is a discussion about possible workarounds.
https://github.com/jinzhu/gorm/issues/1205

I can investigate more what can be done to improve this. I know that F# Data SQL type provider generates such queries correctly, so it should be possible to find a workaround.

**Comment by Thorium** [comment]
Latest version e.g. of Azure SQL Database is not compatible with SQL Server 2014 syntax. :-(
Do we need yet-another-static-parameter?

**Comment by pezipink** [comment]
are we able to detect it using something like we do here?

https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.MsSqlServer.fs#L96

**Comment by object** [comment]
That's a possibility...

**Comment by Thorium** [comment]
Haha... the problem was not actually anything else but when order by desc there was not space after DESC and before OFFSET so the clause was "DESCOFFSET" and should have been "DESC OFFSET". I'll create a new Nuget package today.
