### ISSUE TITLE
How to insert two dependent rows in the same transaction?

### ISSUE THREAD

**Issue by nikonthethird** [fsprojects/SQLProvider#434]
How do I insert one row, get its `Id`, and use that `Id` to insert another row in a different table? All of that in the same transaction?

This is what I tried, and it throws an "The database is not open" exception.
**This code is just a demo of the problem.**

```fsharp
use transaction = new TransactionScope (TransactionScopeAsyncFlowOption.Enabled) // (*)

let user = db.Main.Users.Create ()
do user.Name = "Me"
do! db.SubmitUpdatesAsync () // <== Exception occurs here.

let userIsAdminRole = db.Main.UserRoles.Create ()
do userIsAdminRole.UserId <- user.Id // This is only available after SubmitUpdatesAsync.
do userIsAdminRole.RoleId <- 1 // Admin Role Id.
do! db.SubmitUpdatesAsync ()

do transaction.Complete () // (*)
```

But, if I remove the lines marked (*), it works. What am I doing wrong here?

If the second insert fails, the first one should also not happen. I could not find any info on this in the documentation.

I am using the latest version of the SQLProvider and SQLite as the backend.

**Comment by Thorium** [comment]
I think you need to create a new "db" (dbContext) per transaction.

**Comment by nikonthethird** [comment]
Do you mean create the context inside the transaction scope? Because I only have the one transaction.

**Comment by Thorium** [comment]
Yes:
```fsharp
use transaction = new TransactionScope (TransactionScopeAsyncFlowOption.Enabled) // (*)
let db = YourSqlProvider.GetDataContext cstr

let user = db.Main.Users.Create ()
```

**Comment by nikonthethird** [comment]
I just found [this site](http://www.pinksquirrellabs.com/post/2014/05/18/CRUD-Operations-and-Experimental-ODBC-support-in-the-SQLProvider.aspx), which states:

> The SQL Provider does not currently have any support for transactionally creating heirarchies of data - that is, where you are able to create foreign-key related entities within the same transaction.  This feature may be added at a later date.

That would also explain it :)
Is that information still accurate?

I will try your suggestion right away, thank you.

**Comment by nikonthethird** [comment]
The same thing happens if I create the `DataContext` inside the transaction.
But that's OK, I think like that article says this is simply not supported.

Thank you for the suggestion, though!
