### ISSUE TITLE
Cannot Insert Values to Oracle

### ISSUE THREAD

**Issue by Pranav180495** [fsprojects/SQLProvider#435]
### Description

I am unable to insert a new record into an Oracle database using F# and SQLDataProvider. More importantly, the SQLDataProvider is unable to read the fields of time (DateTime or time values) and I am unable to set this from my application.
### Repro steps

The code is given below: 
type sql =SqlDataProvider<ConnectionString = @"User Id=********; Password=******;Data Source=(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (Host = *****) (Port = ****)) (CONNECT_DATA = (SERVICE_NAME = ********) (SERVER = DEDICATED)))",
                                 ResolutionPath = @"C:\Users\abcd\Documents\Visual Studio 2015\Projects\ConsoleApplication3\ConsoleApplication3\include",
                                 DatabaseVendor = Common.DatabaseProviderTypes.ORACLE> 

let dc=sql.GetDataContext()
let k=dc.TableName.Create()
k.HostId<-1
k.Hostname<-"Some string"

dc.SubmitUpdates()

### Expected behavior
I expect the new row to be inserted from the application and also to add in values of type DateTime.

### Actual behavior

The code runs perfectly without any errors, however there is no new column inserted. More importantly, the host_id is iterable when declared in oracle and does not need to be specified during insert. Whenever I try to insert a new host (with a new ID) , I get an Oracle Exception and the code does nothing when I provide an existing ID. None of the columns are updated.

When trying to insert a field of type Time(DateTime in .Net), I do not get this as an option in Intellisense and assigning a value manually results in a field not declared error even though the field is declared in the table.

### Related information 

* Oracle 11g
* Windows
* .NET 4.5

**Comment by pezipink** [comment]
ping @colinbull

**Comment by Thorium** [comment]
- Does others than datetime values work?
- Does other overrides for Create() work?
- Does `k.SetColumn("HostId", 1)` work?

**Comment by Pranav180495** [comment]
1) Date works fine, Timestamp doesn't work though we need to store the timestamp.
2) No. I get an error "The member or object constructor 'Create' does not take 3 arguments. An overload was found taking 0 arguments.
3) Nope. I get an Oracle Exception regardless and my table has no constraints at all.

**Comment by colinbull** [comment]
Time stamps are a complete PITA. Can you share an anonymised table structure so I can test?

**Comment by Pranav180495** [comment]
Thanks. 

Here is an anonymized schema:

CREATE TABLE "Test"."Names" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"TIMESTAMP1" TIMESTAMP,
	"Name" NVARCHAR2(64), 
	 CONSTRAINT "UniqueName" UNIQUE ("Name"))


The problem arises when trying to insert a new value without the ID (since this is automatically generated by Oracle). I either get an OracleException or KeyNotFound exception. The insert works fine when using the Oracle developer interface or when using a different library which accepts the command as a string. Is this error caused due to the absence of a primary key?
