### ISSUE TITLE
how to retrieve the sql of a query?

### ISSUE THREAD

**Issue by giuliohome** [fsprojects/SQLProvider#438]
### Description

How can I check the sql of a query with SQL Provider? I need to understand why an item is missing... Thanks

### Repro steps

Let's say I have a query

```
let qry = 
    query { for row in mgrs do select row } // mapping ...

qry |> Seq.toArray
```

### Expected behavior

I'm looking for something like `ctx.LastQuery` to see the auto generated sql of the query

### Actual behavior

Can't find anything about the actual sql submitted to db

### Known workarounds

I need to add logging at row iteration level, plus counting totals and similar.

### Related information 

I'm still on F# 4.0

**Comment by Thorium** [comment]
Just curious: This is important question, so where did you search the information first? Because this has been asked so many times, so obviously we could try to find even more clear place for documenting that.

**Comment by Thorium** [comment]
Currently it's at the top of querying-page: http://fsprojects.github.io/SQLProvider/core/querying.html

**Comment by giuliohome** [comment]
Thanks, I overlooked that succinct line, but I still have a couple of issues.
The first is how can I remove the event handler after I've logged the specific query I need?
My second question is if you can help me with the usage, I'm unable to make it work.
This is what I tried:

`FSharp.Data.Sql.Common.QueryEvents.SqlQueryEvent |> Event.add (fun x -> log.InfoFormat( "Executing SQL: %s", x))`

where `log` is an `ILog` from [log4net](https://www.nuget.org/packages/log4net/).
Thank you very much.

**Comment by Thorium** [comment]
If your SQLProvider version is not very old, your `x` is of type:

```fsharp
   type SqlEventData = {
       Command: string
       Parameters: (string*obj) seq
   }
```
And if you need both as string, just use x.ToSting() or "%O" when saving that.
Easiest way to filter events is probably chain before `|> Event.add` something like 
`|> Event.filter(fun x -> (* your filtering condition here *))`

**Comment by giuliohome** [comment]
I'm not using the latest version and I'm afraid there was a different
behavior (or a bug was fixed only in the next release), so I'm stuck...
Well, I've managed this through a different workaround for the moment.

Anyway the filter you describe is not as flexible as a specific property
showing the sql at the query level.
You may want to consider a low priority enhancement for the future.

I'd love to contribute. Also because - if I can add a different topic here
- it would be great to enhance the MapTo utility, giving the opportunity to
change the name of a field and to get type mismatches  at compile time. I'm
testing  the SQL Provider with Sqlite and I've noticed that the type
mapping itself should be customized, if possible.

Thanks again.

Il 26 Lug 2017 5:58 PM, "Tuomas Hietanen" <notifications@github.com> ha
scritto:

**Comment by Thorium** [comment]
We do accept contributions.
Also I recommend to update to the latest version, the functionality is much more what it should be now compared to year ago. :-)
