### ISSUE TITLE
Insert without values result to syntax error with TSQL

### ISSUE THREAD

**Issue by Risord** [fsprojects/SQLProvider#440]
### Description

Row insert won't work if there is no data to provide.

### Repro steps

1. Create table with only auto increment id column

2. Try insert row
```
    let ctx = sql.GetDataContext()
    let row = ctx.Dbo.TableName.Create()
    ctx.SubmitUpdates()
```

### Expected behavior

Row will be inserted by some working sql expression like:
```
INSERT INTO [dbo].[TableName] OUTPUT inserted.Id DEFAULT VALUES;
```

### Actual behavior

Sql syntax exception will be raised since DB will be queried with invalid expression:
```
INSERT INTO [dbo].[TableName] () OUTPUT inserted.Id VALUES ();
```

### Known workarounds

Create dummy column?

### Related information 

* Used database: SQL Server 2016
* Operating system: Windows 10
* Branch: 1.1.7
* .NET Runtime, CoreCLR or Mono Version: .NET 4.6
* Performance information, links to performance testing scripts: -

**Comment by Thorium** [comment]
Seems a fare request. Just have to figure out this `DEFAULT VALUES` syntax for different databases.

**Comment by Risord** [comment]
I have already done workaround this by using another library so no panic. Honestly I think this is more T-SQL design issue than SqlProvider issue...
