### ISSUE TITLE
Need access to CommandTimeout

### ISSUE THREAD

**Issue by Rickasaurus** [fsprojects/SQLProvider#446]
### Description

We are using SQLProvider for some scripts to move around database stuff, it worked great for the first client but then we went to a bigger one and it timed out. We poked around and realized there is no way to access the CommandTimeout property on the DataContext so we're kinda stuck.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Doesn't seem to be one.

### Related information 

* Used database
This was with SQL Server 2016.

* Operating system
Windows Server 2012

* Branch
1.0.37 but we checked latest (1.1.8) and there's no support.

* .NET Runtime, CoreCLR or Mono Version
Plain old .NET 4.5.2

* Performance information, links to performance testing scripts

**Comment by Thorium** [comment]
For CRUD operations also, or just for selects? What was the default timeout? Over a minute? Are you missing a database index? ;-) CRUDs are using DTC transactions that are configured to machine.config.

**Comment by pezipink** [comment]
The DTC timeout is independent of the Command timeout, is it not?

**Comment by Rickasaurus** [comment]
We're pulling out millions of rows from databases and putting them into files for processing.

**Comment by Thorium** [comment]
Great, let's add the timeout :-)

**Comment by Thorium** [comment]
The PR is adding optional timeout parameter to `.GetDataContext()`. It just sets the timeout for (non-design-time) commands inside that datacontext. I didn't test will it actually work as I didn't have anything long-running.

**Comment by Rickasaurus** [comment]
Awesome, thanks!
