### ISSUE TITLE
Navigation property naming is ambiguous

### ISSUE THREAD

**Issue by Risord** [fsprojects/SQLProvider#449]
### Description

Navigation properties are generated by target table and column name instead of source column name. Using target table-column combination is ambiguous way to identify relations because it doesn't really identify relationship.

### Repro steps

1. Create structure like this:

Customer

| Column name  | Type / Constraint |
| --- | --- |
| ID | int |
| OwnedCarID | int / ref to Car id |
| LoanedCarID | int / ref to Car id |
| ... | ... |

Car

| Column name  | Type / Constraint |
| --- | --- |
| ID | int |
| ... | ... |

### Expected behavior

Navigation properties should be named something like (possibly with "Car by " or what ever prefix):
``schema.OwnedCarID``
``schema.LoanedCarID``

### Actual behavior

Customer are named ambiguously and not descriptively:
``schema.Car by ID``
``schema.Car by ID_1``

Only way to detect what these things actually are is to test them. But since these names (aka relation identifiers) collide there are not even quarantees that this is sustainable state!
At first my "Car by ID" meant "by OwnedCarID" and "Car by ID_1" meant "by LoanedCarID" but after 
some unrelated db schema modifications and SqlProvider update these swapped!
So "Car by ID" meant "by LoanedCarID" and "Car by ID_1" meant "by OwnedCarID" => mushroom cloud.

### Related information 

* Used database: Sql Server 2016
* Operating system: Windows 10
* Branch: 1.1.8

**Comment by pezipink** [comment]
yes, this can be a problem. I believe if you look at the XML doc on the property that is generated for the relationship, it tells you exactly what fields it is using doesn't it?

**Comment by Risord** [comment]
If you mean constraint name which is indeed often named quite oddly by default I kind of understand this. If you mean actual source column name I really cannot see how that is horrible to use since it's pretty much equal to EntityFramework naming and so far I know nobody has been complained about that aspect.

But I think you can take this note just as general feedback this point. We probably opt out from SqlProvider for now. Btw my personal opinion about dream way of working with "SQL without SQL" is that queries would be mapped as normal data structure instead of code. This way creating queries would be at least close to elegance of Linq based queries but without all the leakiness of using code as data where only tiny fraction is actually supported.

**Comment by Thorium** [comment]
Thanks for feedback, I agree: navigation properties never was part of @colinbull 's naming refactoring.
And I actually rather write the join clauses explicitly, the source code is more clear that way.
The only operation you need navigation properties is left join, which is not very common.

**Comment by Risord** [comment]
Btw I noticed that navigation properties didn't actually swapped but I had instead two near identical methods with different navigation properties =/

**Comment by Thorium** [comment]
It seems that this works correctly, and the Xml comments are also there, so I'll close this.
