### ISSUE TITLE
Mono Sqlite TypeProvider complains about System.Sqlite.Interop.dll

### ISSUE THREAD

**Issue by o1lo01ol1o** [fsprojects/SQLProvider#454]
### Description

Using latest SQLProvider on mono 5.0.1.1 with sqlite fails to connect to the database at design time.  

building the project throws:

  sqlitetest.fs(15, 16): [FS3033] The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: SQLite.Interop.dll, Path: /hardcoded/path/to/src/packages/System.Data.SQLite.Core.1.0.105.2/lib/net46

### Repro steps

New project -> .net 4.6.2 -> add the following :

SQLProvider (1.1.10)
System.Data.SQLite (1.0.105.2)

(if added via paket, adjust the `resString` path)

```fsharp

[<Literal>]
let connectionString = 
    "Data Source=" + @"file:/hardcoded/path/to/src/db;Version=3;foreign keys=true" 


[<Literal>]
let resString = 
    @"/hardcoded/path/to/src/packages/System.Data.SQLite.Core.1.0.105.2/lib/net46"
   
    

type sql = SqlDataProvider< 
                            ConnectionString=connectionString,
                            DatabaseVendor=Common.DatabaseProviderTypes.SQLITE, 
                            SQLiteLibrary=Common.SQLiteLibrary.SystemDataSQLite,
                            ResolutionPath = resString
                            >

```

build from command line: `msbuild project.sln`

### Expected behavior

I expect the type provider to provide types and compile.

### Actual behavior

Type provider does not provide types and does not compile.

### Known workarounds

I have also tried copying the `System.Sqlite.Interop.dll` from the [.../]build/x64 / [.../]build/x84 folders to various paths in the resolution director as per the documentation but no joy.

paket fails with the same issue.

### Related information 

* Sierra
* mono 5.0.1.1

**Comment by Thorium** [comment]
There are some discussion about x64 vs x86 version of that dll in the internet. 
https://stackoverflow.com/questions/13028069/unable-to-load-dll-sqlite-interop-dll

Try to copy manually the correct file to your reference path... Or bin.

**Comment by o1lo01ol1o** [comment]
Copying the files to bin and reference path did not work for me.

**Comment by Thorium** [comment]
Try to include the correct [SQLite](http://fsprojects.github.io/SQLProvider/core/sqlite.html) interop library to operation system PATH variable.

**Comment by o1lo01ol1o** [comment]
I punted and went to a different language.  :\
