### ISSUE TITLE
SqlProvider.Core.Tests/MySql not working in macos

### ISSUE THREAD

**Issue by zaaack** [fsprojects/SQLProvider#461]
### Description

SqlProvider.Core.Tests/MySql not working in macos

### Repro steps

```sh
git clone --depth 1 https://github.com/fsprojects/SQLProvider.git
cd SQLProvider
./build.sh // This would cause some errors (1), but `Core.Tests/MySql` only need some dlls in packages, so I ignored.
cd tests/SqlProvider.Core.Tests/MySql
dotnet restore 
dotnet run

```
(1): https://github.com/fsprojects/SQLProvider/issues/460#issuecomment-337215435

### Expected behavior

Working
### Actual behavior

Got an error:

```sh
z at ZsMBP in ~/Projects/Fable/SQLProvider/tests/SqlProvider.Core.Tests/MySql (master) 
$ dotnet run --verbose        
error FS3053 : The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error : The type provider constructor has thrown an exception: The method or operation is not implemented. [/Users/z/Projects/Fable/SQLProvider/tests/SqlProvider.Core.Tests/MySql/SqlProvider.Core.Tests.fsproj]
FSC : warning FS3005: Referenced assembly '/Users/z/.nuget/packages/sqlprovider/1.1.12/lib/netstandard2.0/FSharp.Data.SqlProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [/Users/z/Projects/Fable/SQLProvider/tests/SqlProvider.Core.Tests/MySql/SqlProvider.Core.Tests.fsproj]

The build failed. Please fix the build errors and run again.

```

### Known workarounds

None

### Related information 

* Used database: mariadb:10.3.2
* Operating system: macOS
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: dotnetcore2.0, mono 5.2.0.224
* Performance information, links to performance testing scripts

**Comment by Thorium** [comment]
@zaaack `MySql.Data.dll` has dependencies to `System.Security.Principal.Windows.dll` and `System.Text.Encoding.CodePages.dll` which have to be in the same folder where you have the MySql.Data.dll. Try to restore packages first, e.g. ~/SQLProvider$ directory:
```
mono .paket/paket.bootstrapper.exe 
mono .paket/paket.exe restore
cd tests/SqlProvider.Core.Tests/MySql/
mkdir temp
dotnet restore
dotnet build
dotnet run
```

I don't know why MySql.Data.dll has these dependencies, "Windows" sounds quite strange anyways.

**Comment by zaaack** [comment]
@Thorium I'm pretty sure these dlls are already restored into temp/ folder, and still got this error in macos/linux

**Comment by zaaack** [comment]
And the error are thrown from type provider, so I'm guessing this is not MySQL.Data's problem, but a Type Provider issue?

**Comment by Thorium** [comment]
No, this just means that the compiler was unable to load the typeprovider, which is usually due to type-provider not being able to load types with reflection. So the error message is kind of misleading.

There is a huge amount of dependencies to dotnet standard 1.3: https://www.nuget.org/packages/MySql.Data/6.10.3-rc
But these two were enough that "it works in my machine" with dotnet standard 2.0
(after I fixed this https://bugs.mysql.com/bug.php?id=88016 to the dll attached).

**Comment by zaaack** [comment]
I have to say you did a Great Work! BTW, what machine are you using? Can't believe MySql.Data isn't an OSS 😱. 

There might be other missing dependencies in my machine, but would it be hard/possible to changing to another already-work & open-source mysql client like https://github.com/mysql-net/MySqlConnector/ ?

**Comment by zaaack** [comment]
I have to say you did a Great Work! BTW, what machine are you using?Can't believe MySql.Data isn't an OSS 😱. 

There might be other missing dependencies in my machine, but would it be hard/possible to changing to another already-work & open-source mysql client like https://github.com/mysql-net/MySqlConnector/ ?

**Comment by Thorium** [comment]
Yes we could. It seems that MySqlConnector is pretty alpha still? We don't need the full System.Data.Common interface abstraction, but a few things would be nice:

- Datatypes: MySqlConnection, MySqlCommand MySqlDbType MySqlParameter (at least the parameter is missing)
- GetSchema() method or some other manual way to get info about .NET-to-DB DataTypes mapping.

**Comment by zaaack** [comment]
@Thorium I think it's stable enough since it's already be used by Dapper and a mysql provider for EFCore (you can find more ORM built on it in the readme). I'm new to dotnetcore/F#,  so I'm sorry that I cannot provide more suggestions about implementation details.

**Comment by Thorium** [comment]
MySqlConnector pages states: "For common scenarios, this package should be a drop-in replacement"

I created https://github.com/mysql-net/MySqlConnector/issues/361

Let's see if they need any help and do they accept PRs or should I just write overrides to the SQLProvider directly (which is easier because SQLProvider is F#, and C# is a painful language).

**Comment by bgrainger** [comment]
Hi, I'm the primary maintainer of MySqlConnector.  I do accept PRs (see https://github.com/mysql-net/MySqlConnector/graphs/contributors).

I'm not familiar with `DbConnection.GetSchema` but I think it's going to be a lot of work (in MySqlConnector) due to the need to verify that the new implementation is backwards compatible with MySql.Data (except where that implementation has obvious bugs that should be fixed).

FWIW, the library does support `DbDataReader.GetColumnSchema` (a new .NET Standard API) if that helps: mysql-net/MySqlConnector#182. (It does require that a query be executed first, so I understand if it's not relevant to your use case.)

**Comment by Thorium** [comment]
Ok, I added PR. If that is accepted and released to NuGet, we will support using MySqlConnector.

Initial test on my machine, F# interactive with `#time`, executing a SQL-clause with SQLProvider (canoncicalOpTest from our scripts):
```
MySql.Data.Dll:   Real: 00:00:00.583, CPU: 00:00:00.484, GC gen0: 1, gen1: 0, gen2: 0
MySqlConnect.dll: Real: 00:00:00.173, CPU: 00:00:00.093, GC gen0: 1, gen1: 0, gen2: 0
```

and executing few hundred simple SQL-clauses in parallel, multiple threads, separate connections (Thread test from our scripts):
```
MySQL.Data.dll    Real: 00:00:01.425, CPU: 00:00:02.078, GC gen0: 16, gen1: 1, gen2: 0
MySqlConnect.dll: Real: 00:00:01.091, CPU: 00:00:02.000, GC gen0: 14, gen1: 1, gen2: 0
```

Not bad.

**Comment by zaaack** [comment]
I tried postgres demo today, and still got the same error:
```sh
z at ZsMBP in ~/Projects/Fable/SQLProvider/tests/SqlProvider.Core.Tests/Postgres (master●) 
$ dotnet run
error FS3053 : The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error : The type provider constructor has thrown an exception: The method or operation is not implemented. [/Users/z/Projects/Fable/SQLProvider/tests/SqlProvider.Core.Tests/Postgres/SqlProvider.Core.Tests.fsproj]
FSC : warning FS3005: Referenced assembly '/Users/z/.nuget/packages/sqlprovider/1.1.12/lib/netstandard2.0/FSharp.Data.SqlProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [/Users/z/Projects/Fable/SQLProvider/tests/SqlProvider.Core.Tests/Postgres/SqlProvider.Core.Tests.fsproj]

The build failed. Please fix the build errors and run again.

```

**Comment by Thorium** [comment]
Well, technically Mono is working (the .Net Framework), but non-Windows .NET Core is not.
I got the same error, but not sure how to debug .NET Core, so I opened a question [here](https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/151).

**Comment by zaaack** [comment]
The fsharpi should from mono, but in my knowledge we cannot run a dotnet core app in mono, so should this be the problem?

**Comment by zaaack** [comment]
Just got an build pass! I build ./src/SQLProvider by mono and copied the output dlls to `/Users/z/.nuget/packages/sqlprovider/1.1.12/lib/netstandard2.0`(where my project referenced).

I have been watching the progress of TP support in dotnet core for a while, the workaround is by using mono's fsharpc to compile TP but build the app and the provided types from TP by dotnet core, and I saw someone says we cannot run dlls built by dotnet core in mono (maybe not in .net framework) in a issue(cannot find it now), so the TP project worked for dotnet core should still be compiled by mono.

**Comment by zaaack** [comment]
Add these lines to my .fsproj file and remove SQLProvider in paket reference file worked for me.

```sh
  <ItemGroup>
    <Reference Include="FSharp.Data.SqlProvider">
      <HintPath>../../packages/local/SQLProvider/lib/net451/FSharp.Data.SqlProvider.dll</HintPath>
      <Paket>True</Paket>
    </Reference>
  </ItemGroup>

```

**Comment by Thorium** [comment]
Great! 
But wait a minute... Are you targeting your software to Mono or .NET Core?
And how do you know that what is the environment that you are running, Mono or Core?

**Comment by zaaack** [comment]
My project is targeting netcoreapp2.0 only, and I think it's pretty easy to tell what the build environment in *nix, if I built by dotnet cli(dotnet run, dotnet build), than it's built by dotnet core, because I didn't hack the dotnet cli after installing followed by the tutorial.

And we can using `which` command to get the absolute path of command:
![image](https://user-images.githubusercontent.com/5233940/31848082-97fce09c-b5ef-11e7-8c48-699a3e561486.png)
You can see if we build by msbuild/fsharpi/fsharpc, we actually are building projects by mono.

**Comment by Thorium** [comment]
Thanks, I'll update the core sample projects and documentation.

**Comment by Thorium** [comment]
MySqlConnector 0.29 was released today, and SQLProvider 1.1.15 supports it.
That does work on Mac on Net Core (I tested it). The example is updated:
https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Core.Tests/MySql

The only limitation is that execution of stored SQLProvider calling procedures is not supported on MySqlConnector. Probably problem with the return type parameters.

**Comment by bgrainger** [comment]
> The only limitation is that execution of stored SQLProvider calling procedures is not supported on MySqlConnector. 

Can you provide more details on this? It should be possible to execute both `PROCEDURE`s and `FUNCTION`s.

**Comment by Thorium** [comment]
@bgrainger I haven't debug the problem, but I expect it to be the type-mapping back to "somekind of .NET result set" is not identical with these two dlls. If I will have extra time, I'll search more and may send some PR but right now that is not urgent problem as a) MySQL is not most commonly used database with SQLProvider, b) Procedures are not most commonly used features in MySQL, and c) you can still easily use the two drivers together.

And there has been things like data-types (e.g. information-schema max-length long), with MySql.Data.dll you can read basically any column type with reader.GetString() where MySqlConnector actually expects the correct type, and I think that is a good thing. So the problem might be also SQLProvider side and not MySqlConnector.

**Comment by Thorium** [comment]
As expected, the problem with stored procedures was not related to MySqlConnector and is now working.
