### ISSUE TITLE
Duplicate FSharp.Core in project when upgrading to 1.1.15

### ISSUE THREAD

**Issue by davidtme** [fsprojects/SQLProvider#465]
Currently I'm running on 1.1.11 which works great but when I upgrade to 1.1.15 I get an extra reference to `packages\SQLProvider\lib\net451\FSharp.Core.dll` which results in `FSharp.Core` being pulled in twice

![image](https://user-images.githubusercontent.com/1804141/32003054-e8522c60-b995-11e7-88e1-9d0b57ac26bc.png)

Via paket my project ends up looking like this:
```XML
  <Import Project="..\..\.paket\paket.targets" />
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.1'">
      <ItemGroup>
        <Reference Include="FSharp.Core">
          <HintPath>..\..\packages\FSharp.Core\lib\net45\FSharp.Core.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.1'">
      <ItemGroup>
        <Reference Include="FSharp.Core">
          <HintPath>..\..\packages\SQLProvider\lib\net451\FSharp.Core.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="FSharp.Data.SqlProvider">
          <HintPath>..\..\packages\SQLProvider\lib\net451\FSharp.Data.SqlProvider.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

**Comment by Thorium** [comment]
@davidtme, I assume you are using Mono?

**Comment by davidtme** [comment]
@Thorium sorry, should have put my computer details.

* Windows 10
* .NET Framework 4.6.1

**Comment by Thorium** [comment]
Should be fixed now.

**Comment by davidtme** [comment]
@Thorium that works.  Thank you so much for the fast fix

**Comment by davidtme** [comment]
sorry, bit premature on the "that works"!
```
The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: GetMethodImpl. not support overloads
```

**Comment by Thorium** [comment]
Hmm, this comes from the new ProvidedTypes.fs. I'll try to update it...

**Comment by Thorium** [comment]
@davidtme what database are you using?

**Comment by davidtme** [comment]
@Thorium I'm using an MSSQL database so my connection string is along the lines of `Data Source=(localdb)\MSSQLLocalDB; Integrated Security=True; Initial Catalog=Test123;`

I'll try and put a gist together with the error.

**Comment by davidtme** [comment]
@Thorium This is very odd, it's [FSharp.Data.SqlClient](http://fsprojects.github.io/FSharp.Data.SqlClient/) 1.8.2 that is throwing the `GetMethodImpl` error but only when SQLProvider is upgraded passed 1.1.11

**Comment by Thorium** [comment]
Versions after 1.1.11 is using the new cross-targeting type provider API. I noticed that stored procedures don't work with that, I'm trying to find a fix.

**Comment by Thorium** [comment]
I think "GetMethodImpl. not support overloads" is another feature of FSharp.TypeProviders.SDK.
The case happens when compiler happens to generate two types with the same name.

**Comment by Thorium** [comment]
Try 1.1.17. It may or might not help. There the procedure results are loaded to the root of namespace FSharp.Data.Sql which might be bad if you have a huge load of procedures. Have to find some other solution later but at least this seems to work.

**Comment by Thorium** [comment]
I took the old FSharp.TypeProviders.SDK API back (from SQLProvider 1.1.14), should be ok in 1.1.18.
