### ISSUE TITLE
exactlyOneOrDefault does not have 'null' as a proper value  (1.1.16)

### ISSUE THREAD

**Issue by SCullman** [fsprojects/SQLProvider#468]
http://fsprojects.github.io/SQLProvider/core/crud.html 
Section:  update a single row assuming Id is unique
```
if not (isNull foundEmployee) then
```
=>
The type 'SqlDataProvider<...>.dataContext.dbo....Entity' does not have 'null' as a proper value	

No error in 1.1.14

**Comment by Thorium** [comment]
Hmm.  
What is the column type definition in the database, allow nulls or not? 
Do you have static constructor parameters useOptionTypes on or off?

**Comment by SCullman** [comment]
- All columns are set to "NOT NULL"
- useOptTypes is not used (and therefore "off"?)

**Comment by Thorium** [comment]
Yes, this is a bug, clearly it returns Null if the query returns no hits, so FSharp intellinsense should know that.

**Comment by Thorium** [comment]
I took the old FSharp.TypeProviders.SDK API back (from SQLProvider 1.1.14), should be ok in 1.1.18.

**Comment by Thorium** [comment]
Hmm, this is also F# thing: https://github.com/Microsoft/visualfsharp/issues/3845
