### ISSUE TITLE
Duplicate sproc names ("GetMethodImpl not support overloads")

### ISSUE THREAD

**Issue by piaste** [fsprojects/SQLProvider#470]
See https://github.com/fsprojects/SQLProvider/issues/465#issuecomment-339382409 and followup comments

I noticed the same 'not support overloads' issue with PostgreSQL when accessing the `Functions` property.

The problem in that case was that while the provider makes sure not to fetch sprocs with the same name, the design time then applies `nicePascalName` and it may result in a conflict if two sprocs only differ by non-alphanumeric characters.

Now if the functions are user-created you could just name them more sensibly, but in my case they came from a Postgres extension so I couldn't do anything about it. 

I have [a fix for the issue](https://github.com/fsprojects/SQLProvider/compare/master...piaste:fix_pg_extension_functions) as it relates to Postgres and I guess it's technically submittable, but I realized it's a super hacky one because it just groups by `nicePascalName` upstream in `GetSprocs` (and only in the Postgres provider).

The proper fix would be to handle pascal-duplicated names in SqlDesignTime, during the [tree-walking](https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/SqlDesignTime.fs#L345). I'll get to work on this, just wanted to check if my reasoning was sound.

(Also, ideally we would not simply hide overloaded (or pseudo-overloaded) procedures, we ought instead to give them proper F# names, by adding ```` or something. Not a big deal, though, as it's easy enough to add a wrapper procedure with a different name if necessary.)

**Comment by Thorium** [comment]
Maybe a concurrent dictionary just after and before pascal-naming to check duplicates, and a tooltip to display original name?

**Comment by Thorium** [comment]
Sorry to change SqlDesignTime.fs so often...

**Comment by piaste** [comment]
's ok, I needed some practice with rebase anyway 🙌 

With the current master the sprocs don't crash outright, so it's much less of an issue, but it's still kinda buggy - only one shows up, and the XML comments are all merged. Submitted a PR.

**Comment by Thorium** [comment]
Thanks, PR merged to version 1.1.19
