### ISSUE TITLE
Cannot check exactlyOneOrDefault because a not nullable type has been generated 

### ISSUE THREAD

**Issue by giuliohome** [fsprojects/SQLProvider#472]
### Description

when I do
```fhsarp
let markers = ctx.Dbo.PriceMarker
let foundRecord = query {
    for m in markers do
    where (m.MyDate = s.Date.Date && m.Code = some.Code)
    exactlyOneOrDefault
}
if not (isNull foundRecord) then // <== error here```
```
### Repro steps

Please provide the steps required to reproduce the problem

1. create table on Sql Server DB

2. run above code

### Expected behavior

It should work like in the [doc](fsprojects.github.io/SQLProvider/core/crud.html)
where they do
```fhsarp
let updateEmployee (employee: Employee2) =
    let foundEmployee = query {
        for p in ctx.Public.Employee2 do
        where (p.Id = employee.Id)
        exactlyOneOrDefault
    }
    if not (isNull foundEmployee) then
        foundEmployee.FirstName <- employee.FirstName
        foundEmployee.LastName <- employee.LastName
    ctx.SubmitUpdates()
```
### Actual behavior

I get the error

```fhsarp
The type 'SqlDataProvider<...>.dataContext.dbo.mytableEntity' does not have 'null' as a proper value
```

### Known workarounds

I have to box the value
```fhsarp
if (box >> isNull >> not) foundRecord then
```
### Related information 

* Used database: MS Sql Server 2016 
* Operating system MS Server 2016
* .NET Runtime Version  4.6

**Comment by giuliohome** [comment]
I've tried also with SQLite and I get the same problem as with SQL Server

**Comment by Thorium** [comment]
Should be ok in 1.1.18.

**Comment by giuliohome** [comment]
Thank you very much for your support

**Comment by Thorium** [comment]
Related also to: https://github.com/Microsoft/visualfsharp/issues/3845
