### ISSUE TITLE
Unexpected error "Insufficient parameters supplied to the command" when updating to SQLite

### ISSUE THREAD

**Issue by giuliohome** [fsprojects/SQLProvider#475]
### Description

Whe I run the following code

```fsharp
let foundWS = 
    query {
        for m in platts do
        where (m.AreaFrom = Some spotPrice.Code && m.RefDate = Some spotPrice.Date)
        exactlyOneOrDefault
    } 

if not (isNull foundWS)
then    
    foundWS.WsValue <- Some spotPrice.Price // <= it runs this code as expected
    foundWS.AreaTo <- Some "Test ..."
else
    let newWS = platts.Create()
    newWS.AreaFrom <- Some spotPrice.Code
    newWS.RefDate <- Some spotPrice.Date.Date
    newWS.WsValue <- Some spotPrice.Price
    newWS.AreaTo <- Some "Test ..."

appCtx.SubmitUpdates() // <-- exception 

```

### Repro steps

Steps to reproduce the problem

1. Step A
Create a table like the following 

```sql
CREATE TABLE [test_table] (
[ref_date] DATE  NULL,
[provider] VARCHAR(20)  NULL,
[type] VARCHAR(20)  NULL,
[area_from] VARCHAR(20)  NULL,
[area_to] VARCHAR(20)  NULL,
[size_key] VARCHAR(20)  NULL,
[WsValue] FLOAT  NULL,
[ignore] BOOLEAN  NULL,
PRIMARY KEY ([ref_date],[provider],[type],[area_from],[area_to],[size_key])
)
```

2. Step B
Insert the selected record so that it finds it

3. Step C
Run the above F# code

### Expected behavior

The record should be updated without error

### Actual behavior

I'm getting the following error

```fsharp
Insufficient parameters supplied to the command
   in System.Data.SQLite.SQLiteStatement.BindParameter(Int32 index, SQLiteParame
ter param)
   in System.Data.SQLite.SQLiteStatement.BindParameters()
   in System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   in System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   in System.Data.SQLite.SQLiteDataReader.NextResult()
   in System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavi
or behave)
   in System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   in System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)

   in System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   in <StartupCode$FSharp-Data-SqlProvider>.$Providers.SQLite.FSharp-Data-Sql-Co
mmon-ISqlProvider-ProcessUpdates@794-7.Invoke(SqlEntity e)
   in Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEn
umerable`1 source)
   in FSharp.Data.Sql.Providers.SQLiteProvider.FSharp-Data-Sql-Common-ISqlProvid
er-ProcessUpdates(IDbConnection con, ConcurrentDictionary`2 entities, Transactio
nOptions transactionOptions, FSharpOption`1 timeout)
   in <StartupCode$FSharp-Data-SqlProvider>.$SqlRuntime.DataContext.f@1-56(SqlDa
taContext __, IDbConnection con, Unit unitVar0)
   in FSharp.Data.Sql.Runtime.SqlDataContext.FSharp-Data-Sql-Common-ISqlDataCont
ext-SubmitPendingChanges()
```

### Known workarounds

No one at the moment.

### Related information 

* Used database SQLite Version 3
* Operating system Windows 7
* Branch latest version of nuget SQLProvider (from PM of VisualStudio2015) v1.1.18
* .NET Runtime: 4.6.1

**Comment by giuliohome** [comment]
As far as I understand, the whole key is expected even if it is not needed (since the `exactlyOneOrDefault` is working in the query)

**Comment by Thorium** [comment]
Yes. I would recommend considering creating a separate Id-field to the database table,

**Comment by Thorium** [comment]
Need of the exact table key is actually just to protect developers.
Because otherwise the user could end-up in a situation where 
the generated update clause would cause "1100 row(s) affected"
even if the developer thought that this should hit only one item.

**Comment by giuliohome** [comment]
I cannot really create a separate id-field to the sqlite table since it is already used in another app and it makes sense to have a _multiple-fields_ key. but I actually can complete the key with the other (somehow fixed) fields in the query, so... yes, the issue is solved. Thanks

**Comment by giuliohome** [comment]
Yes I understand the protection even though the exactlyOneOrDefault already guaranteed it... Anyway, fair enough, ok.

**Comment by Thorium** [comment]
...which leads to the next question that how do you expect exactly one when you don't use your primary key items in your where-clause. Anyways, that's none of my business. :-)

**Comment by giuliohome** [comment]
Yes, you're right, that's a very good question. The full code needs a complex join with other tables. I was trying to do an intermediate test of a drafted version. Anyway, should you look at the complete requirement and the full join (which I am striving to write now) it wouldn't be obvious that there is a unique value either :-) Just imagine there is a table with consecutive ranges and that one has to find the range which a certain value belongs to

**Comment by giuliohome** [comment]
Indeed the join 

```fsharp
  let foundWS = 
      query {
          for p in platts do
          join a in vesselAlias on ((p.AreaFrom, p.AreaTo,p.Provider,p.SizeKey, p.Type) = (a.AreaFrom, a.AreaTo, "TEST", "MR", a.WsType))   
          where (a.Alias = spotPrice.Code && p.RefDate =  spotPrice.Date)
          select p
          exactlyOneOrDefault
      } 
```

gives me an error

```fsharp
The lists had different lengths.
Nome parametro: xs2
   in Microsoft.FSharp.Linq.QueryModule.CallGenericStaticMethod@333.Invoke(Tuple`2 tupledArg)
   in Microsoft.FSharp.Linq.QueryModule.clo@1735-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
```

What does it mean exactly? Thanks again

**Comment by Thorium** [comment]
We don't currently support joining to a static fields like "TEST" and "MR", so please use where-filter for those.

**Comment by giuliohome** [comment]
Thank you very much for your support

**Comment by giuliohome** [comment]
Why can't I test if a tuple is null?

```fsharp
 let foundWSTuple = 
     query {
         for p in prices do
         join a in Alias on ((p.AreaFrom, p.AreaTo,p.Type) = (a.AreaFrom, a.AreaTo, a.WsType))   
         where (a.Alias = spotPrice.Code && p.RefDate =  spotPrice.Date && p.Provider = "TEST" && p.SizeKey = "MR" )
         select (p,a)
         exactlyOneOrDefault
     }
     
 if not (isNull foundWSTuple) then  
```
the above code doesn't compile because

```fsharp
The type '(SqlDataProvider<...>.dataContext.main.mytable_valueEntity * SqlDataProvider<...>.dataContext.main.prices_aliasEntity)' does not have 'null' as a proper value
```
but it cab be null (therefore crashing) at runtime. Am I supposed to box it or is it the same bug as for a single entity?

**Comment by Thorium** [comment]
Do you have SQLProvider 1.1.18 where this is fixed?

One thing to consider is using UseOptionTypes in the static constructor parameters of your SQLDataProvider.

**Comment by giuliohome** [comment]
Yes, I have 1.1.18 and I've aslo set UseOptionTypes now...

**Comment by Thorium** [comment]
Hmm, in that case it should return `Option<...>` and you should be able to 
```fsharp
match foundWSTuple  with
| Some x -> ... 
| None -> () //was null

Now I actually found a problem that exactlyOneOrDefault doesn't limit the selected SQL items to 2 as it should.
How about `headOrDefault`?

**Comment by giuliohome** [comment]
I've tried also `headOrDefault` now but I can't match Some/None like you do above

**Comment by Thorium** [comment]
I cannot manage to create an unit test that would fail with exactlyOneOrDefault.
Seems to work perfectly...

**Comment by giuliohome** [comment]
Do you have a `select (p,a)` after a join? And then you can do `if not (isNull foundWSTuple) then`?
My code above does compile only when I box the tuple... screenshot [here](https://snag.gy/78mETl.jpg)

**Comment by Thorium** [comment]
No I don't use isNull. If you have UseOptionTypes then you should be able to say 
e.g. `if foundWSTuple.IsSome then`. Could your problem be related to VS2015 caching...? :-)

**Comment by giuliohome** [comment]
closed solution and VS2015, reopened and rebuild as per your suggestion but still
`error FS0039: The field, constructor or member 'IsSome' is not defined`

**Comment by Thorium** [comment]
Can you clone this repository and open `SQLProvider.Tests.sln`. It has a file QueryTests.fs which is using SQLite as database, and has a lot of tests. Can you try to write a test with exactlyOneOrDefault which would fail, and send either a PR or just copy&paste the test here?

**Comment by giuliohome** [comment]
I see only one line with
```fsharp
            select cust.CustomerId
            exactlyOneOrDefault
```

I guess (but I've not yet cloned and tried) that 
```fsharp
            select (cust.CustomerId,cust.CustomerId)
            exactlyOneOrDefault
```
should be enough to see that `isNull(qry)` doesn't compile:
 if you already have the proj cloned, then you could quickly check it

**Comment by giuliohome** [comment]
I've not yet cloned but the idea is to build a test like the following

```fsharp
    let dc = sql.GetDataContext()
    let qry = 
        query {
            for cust in dc.Main.Customers do
	    join order in dc.Main.Orders on (cust.CustomerId = order.CustomerId)
            where (cust.CustomerId = "ZZZZ" && order.OrderId = 999)
            select (cust,order)
            exactlyOneOrDefault
        }
    Assert.IsTrue(isNull(qry))
    Assert.AreEqual(null, qry) 
```

to check if `isNull(qry)` does compile

**Comment by Thorium** [comment]
I didn't have any problems with select (cust.CustomerId,cust.CustomerId) in a query. 
Yes, it produced null at runtime, as it should. 

I didn't use isNull as it's not an operator of SQLProvider, it comes from FSharp core operators, and it's implementation is depending the version of F# you use, which can vary. But you can use e.g.  `x <> null`. Or as a work-around `isNull(box(x))` should also work.

So from SQLProvider's side:
- If exactlyOneOrDefault with not-found-items and UseOptionTypes=false (default) it should result a null.
- If exactlyOneOrDefault with not-found-items and UseOptionTypes=true it should result a None.

**Comment by Thorium** [comment]
The problem with your later code is that qry result type is a tuple, which is a struct, not a class, and for a struct, you cannot have null as a default value. So there is no "default value", I don't know what exactlyOneOrDefault should be then. But again I think this is a problem of F# language and not SQLProvider. :-)

**Comment by giuliohome** [comment]
Ok thank you very much for helping me! Much appreciated. I'm forced to materialize the second table in an array in-memory and I reduce the join to a single select to preceed in the meantime. Thanks again, let me know.
