### ISSUE TITLE
Question: where is Test.Console project?

### ISSUE THREAD

**Issue by giuliohome** [fsprojects/SQLProvider#485]
It looks like there is a console exe to debug the main provider SqlProvider.fsproj:

```xml
<StartProgram>D:\Appdev\SqlProvider\tests\SqlProvider.Tests\Test.Console\bin\Debug\Test.Console.exe</StartProgram>
 <StartArguments>
</StartArguments>
```

but I can't find neither the source nor the exe,

So I'm forced to debug from SqlProvider.Tests on VS2015 + NUnit 2 Test Adapter but it doesn't stop at any break point set in the main project... I'm stuck, I can't contribute (more than just writing a PR with the new test cases) without knowing the correct procedure to setup a dev env

**Comment by Thorium** [comment]
I don't know what is that.

How I debug this is that I send the significant lines from a test-file to FSharp Interactive, and then attach debugger to that, and send the query to Interactive while debugging it.

**Comment by giuliohome** [comment]
Maybe someone from the contributors created a little test exe, I guess what it is, same thing I also do to debug my libs...

**Comment by giuliohome** [comment]
Related question on [SO](https://stackoverflow.com/questions/47116323/cannot-debug-a-f-library-project)
