### ISSUE TITLE
No Intellisense in Ionide with TypeProvider in dotnet core

### ISSUE THREAD

**Issue by rfrerebe** [fsprojects/SQLProvider#486]
### Description

No Intellisense in Ionide with TypeProvider in dotnet core.
I would like to know if you have Intellisense or not.

### Repro steps

Using PostgreSql test dotnet core type provider in this repo, I am able to build and perform a select in database, but I don't have Intellisense in Ionide.

### Expected behavior

I expect to have Intellisense in Ionide.

### Actual behavior

![2017-11-04](https://user-images.githubusercontent.com/12632865/32409099-7d55dde0-c1a5-11e7-8f11-c5b9865820b2.png)

![2017-11-04 2](https://user-images.githubusercontent.com/12632865/32409100-83561eda-c1a5-11e7-976d-703f2c40d35e.png)

### Related information 

* PostgreSql
* Win10
* master
* NET Core 2.0.2

**Comment by Thorium** [comment]
I'm not sure if this is SQLProvider problem or if the tooling is just not mature enough...

**Comment by rfrerebe** [comment]
It's not really an issue on SQLProvider, but my question is more:
- Does it work for you ?
- If yes, do you have a workaround ? 
If not that's fine, I agree the tooling is not mature enough.

**Comment by Thorium** [comment]
Is this issue of the new fsproj file style? Does it work on fsx scripts? One solution could be to have a parallel non-net-core project having linked the same source files (like we have in SQLProvider project currently).

**Comment by Thorium** [comment]
Is there the dll in your resolutionPath?
How about:
#if INTERACTIVE
#I "/resPath"
#r "/resPath/System.Threading.Tasks.Extensions.dll"
#endif

**Comment by rfrerebe** [comment]
Hello,

To answer your question in order :
Yes, the issue is with the new fsproj file style.
It works with fsx scripts
I will try to have a non net core project.
I will also try to add reference in the fsproj directly or with Paket.

The dll is in my resolution path.
It works fine in interactive.

![2017-11-05](https://user-images.githubusercontent.com/12632865/32415043-fdab7030-c232-11e7-98ae-70413c889a20.png)
I have got auto completion in interactive (fsi) after referencing dlls, but it's red in Vs Code with Ionide

Thanks

**Comment by Thorium** [comment]
Maybe Ionide can't figure out fsharp compiler path from the project file or something... Have you opened a corresponding issue to Ionide?

**Comment by rfrerebe** [comment]
Nope, but if it's ok on your side it's probably an issue with my setup.
