### ISSUE TITLE
I can't insert a row in a sqlserver table. I get a "Enlisting in Ambiant transactions is not supported yet"

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/SQLProvider#495]
### Description
I can't insert a row in a sql table on ASP.NetCore 2.0

### Repro steps

1. Get a data context
2. Opening a TransactionScope
3. Submit changes

Like this:

let saveReportdefinitiion (report:Reportdefinition) = 
    try
        let dc = sql.GetDataContext()
        use ts = new TransactionScope()
        let newReport = dc.Dbo.Berichtsdefinitionen.Create ()
        newReport.BerichtsId <- report.Berichtsid
        newReport.Berichtsname <- Some report.Berichtsname
        ...

        dc.SubmitUpdates()
        ts.Dispose()
    finally
        GC.Collect()
    report

### Expected behavior

I expect the framework to insert a row in the database.

### Actual behavior

I get this error:

An unhandled exception has occurred while executing the request.                             System.NotSupportedException: Enlisting in Ambient transactions is not supported.
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at FSharp.Data.Sql.Providers.MSSqlServerProvider.FSharp-Data-Sql-Common-ISqlProvider-GetColumns(IDbConnection con, Table table)                                                                       at FSharp.Data.Sql.Runtime.SqlDataContext.FSharp-Data-Sql-Common-ISqlDataContext-CreateEntity(String tableName)                                                                                       at EnergyDashboard.BackEnd.Common.Crudsql.createReport(Reportdefinition report, Object dc)

### Related information 

* Used database: sql server 2008 rs2
* Operating system: Windows 10
* SQL Provider 1.1.23
* ASP.NetCore 2.0 using Giraffe

**Comment by Thorium** [comment]
Ok, sounds like a missing feature of .NET Core.
Luckily SQLProvider lets you control the transacitons:
```fsharp
let ctx = 
    db.GetDataContext(
         { Timeout = TimeSpan.MaxValue;
            IsolationLevel = Transactions.IsolationLevel.DontCreateTransaction
         })
```

**Comment by tforkmann** [comment]
I tried that before. 
I get that error message:
![image](https://user-images.githubusercontent.com/4168951/33432734-73d932d8-d5d9-11e7-9a06-2b396d7b5679.png)

**Comment by Thorium** [comment]
open FSharp.Data.Sql.Transactions

**Comment by tforkmann** [comment]
Ok, that works.

Last question how do i parse in the runtimeconnection string then?

If I do:
let getCDB  =
    SqlInsert.GetDataContext(
         { Timeout = TimeSpan.MaxValue;
           IsolationLevel = IsolationLevel.DontCreateTransaction
         })

and then
let getCrudDB = SqlInsert.GetDataContext runtimeconnectionString

I will basically open an second datacontext and run into the same error

**Comment by Thorium** [comment]
There is an override with 2 params:
```fsharp
let ctx = 
    db.GetDataContext(
         runtimeconnectionString,
         { Timeout = TimeSpan.MaxValue;
            IsolationLevel = Transactions.IsolationLevel.DontCreateTransaction
         })
```

**Comment by tforkmann** [comment]
Awesome. Thank you!

I could add that to the docs if you want?

**Comment by Thorium** [comment]
That would be nice.
