### ISSUE TITLE
Step-by-step guide to run NET Core app accessing Postgres on Linux

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/SQLProvider#498]
I would like to run netcoreapp2.0 on Linux that access Postgres via SQLProvider.
This guide https://fsprojects.github.io/SQLProvider/core/postgresql.html
doesn't work because dependencies managed differently on NET Core. 

I looked at test project https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/Postgres/SqlProvider.Core.Tests.fsproj
but I still could not figure it out.

Please put together step-by-step instructions similar to  
https://medium.com/@dsincl12/f-with-net-core-2-0-4-and-sqlprovider-d8f071119da9

Thanks

**Comment by Thorium** [comment]
This is good idea. I think the right place would be adding a Readme.MD file under each database in https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Core.Tests and that readme should contain a chapter for each operating system (Win/Mac/Ubuntu)

**Comment by Thorium** [comment]
Ok, now there is something to start with. We can improve those.

**Comment by dmitry-a-morozov** [comment]
@Thorium Great ! Thank you. Feel free to close the issue.
