### ISSUE TITLE
netcoreapp2.0 with Sql Server access fails to compile on Linux

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/SQLProvider#499]
I have netcoreapp2.0  that uses SQLProvider to access Sql Server
It compiles and runs on Windows perfectly.
On Linux build fails with
```
error FS3053 : The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error : The type provider constructor has thrown an exception: The method or operation is not implemented. [/mnt/c/Users/dmorozov/source/repos/TrySQLProviderWithSqlServer/TrySQLProviderWithSqlServer.fsproj]
FSC : warning FS3005: Referenced assembly '/home/dmorozov/.nuget/packages/sqlprovider/1.1.23/lib/netstandard2.0/FSharp.Data.SqlProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [/mnt/c/Users/dmorozov/source/repos/TrySQLProviderWithSqlServer/TrySQLProviderWithSqlServer.fsproj]
```
F# compiler tooling redirection applied 
```
  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOSX)' == 'true'  AND Exists('/Library/Frameworks/Mono.framework/Versions/Current/Commands/fsharpc')">
    <FscToolPath>/Library/Frameworks/Mono.framework/Versions/Current/Commands</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)' == 'true' AND Exists('/usr/bin/fsharpc')">
    <FscToolPath>/usr/bin</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
```

**Comment by Thorium** [comment]
If you clone this repo and run the example in tests core, does it work?

**Comment by dmitry-a-morozov** [comment]
I didn't run the example project but I would argue this is not going to be good test.
The example has direct reference
https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/Postgres/SqlProvider.Core.Tests.fsproj#L55

Which is not how real project with PackageReference will look like.

**Comment by Thorium** [comment]
No, that wont be your compilation result. 

That is just compilation time reference. 

On Linux you compile the project with Mono, which still produces .Net coreapp dll at runtime.

**Comment by Thorium** [comment]
And yes, that is a hack (not the first one in Linux, thoigh) but I don't know the alternative until Mono will support .Net Standard libraries.

Runtime should work on Linux/Win/Mac no matter what you used for the compilation.

I did run the examples in my Ubuntu and the only hard one is SQLite compilation.

**Comment by dmitry-a-morozov** [comment]
You lost me a little bit. 
Let me re-phrase my question.
If I'll do what is described here
https://medium.com/@dsincl12/f-with-net-core-2-0-4-and-sqlprovider-d8f071119da9
Will this project compile on Linux without additional effort?

**Comment by dmitry-a-morozov** [comment]
Assuming of course that I'll have ```FscToolPath``` for Linux too

**Comment by Thorium** [comment]
No. Currently TypeProviders won't compile on Net Core. They compile on net4xx and Mono but do produce .Net core assemblies if that is your target. So at runtime you need .Net Standard version of SQLProvider but at compilation time you need net4xx version. For Windows this is not an issue because Net4xx is Net Standard compatible.

It's a bit confusing. But start with the example at https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/Postgres/

**Comment by Thorium** [comment]
Note that toolpath fsc is actually Mono fsharp.

**Comment by nojaf** [comment]
I'm trying the same thing but with MySql.
So I have a docker container with both aspnetcore and mono installed.
My project contains the workaround as described [here](https://github.com/Microsoft/visualfsharp/issues/3303).

But when building I get 

```
     1>error FS3053 : The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error : The type provider constructor has thrown an exception: The method or operation is not implemented. [/usr/src/app/src/Teams/Teams.fsproj]
         
     1>FSC : warning FS3005: Referenced assembly '/root/.nuget/packages/sqlprovider/1.1.23/lib/netstandard2.0/FSharp.Data.SqlProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
[/usr/src/app/src/Teams/Teams.fsproj]
         The command exited with code 1.
```

I also added 
```
  <ItemGroup><!-- Mono fix -->
    <Reference Condition="'$(IsWindows)' != 'true'" Include="FSharp.Data.SqlProvider">
      <HintPath>../../packages/SQLProvider/lib/net451/FSharp.Data.SqlProvider.dll</HintPath>
    </Reference>
  </ItemGroup>
```
but I'm guessing my project still uses the netcore dll of SqlProvider.

**Comment by nojaf** [comment]
I've added framework net451 to my `paket.dependencies` and my problem got resolved.
```nuget SQLProvider 1.1.23 framework: net451```

**Comment by Thorium** [comment]
@dmitry-a-morozov do you still have the original problem listed in this issue?

**Comment by dmitry-a-morozov** [comment]
@Thorium The issue haven't resolved for me. 
Am I suppose to add 
```
  <ItemGroup><!-- Mono fix -->
    <Reference Condition="'$(IsWindows)' != 'true'" Include="FSharp.Data.SqlProvider">
      <HintPath>../../packages/SQLProvider/lib/net451/FSharp.Data.SqlProvider.dll</HintPath>
    </Reference>
  </ItemGroup>
```
to a project that consume the type provider?

**Comment by Thorium** [comment]
Yes. 

When I'll have more time, I'll make the instructions. But shortly:
On Linux you compile with dotnet.exe but it calls external (FscToolPath) fsharp which executes on Mono, and for that reason you need /net451/FSharp.Data.SqlProvider.dll on compilation time.

But on runtime you use dotnet.exe without external compiler, but run directly on .NET Core. So at runtime you need /netstandard2.0/FSharp.Data.SqlProvider.dll

They are both in the NuGet package.

**Comment by dmitry-a-morozov** [comment]
I don't use paket in my project.
How I do get path to net451 version of FSharp.Data.SqlProvider.dll ?
I thought it's located somewhere in global nuget cache.

Also, how about  https://github.com/fsprojects/SQLProvider/issues/499#issuecomment-355398410
How do I add dependency on net451 without paket?

**Comment by Thorium** [comment]
I think it's at ~/.nuget/packages/SQLProvider/

**Comment by dmitry-a-morozov** [comment]
That worked ! Thanks
Except MsBuild doesn't know to resolve ```~``` so I had to hard code path to my home. Which is not great.
Let me know if you can come up more generic solution that not tided to particular user. 

You can close this issue in favor #498 .
