### ISSUE TITLE
How do I switch between Mysql databases?

### ISSUE THREAD

**Issue by AlfranKeith** [fsprojects/SQLProvider#500]
Hi, trying to pass in a connection string to .GetDataContext() results in an error. DB I intend to switch to has the same schema.

**Comment by Thorium** [comment]
Should work. I use it to build in test db and change to release db after build. If you use multiple databases in parallel, it's probably a better idea to use multiple SQLProviders.

**Comment by AlfranKeith** [comment]
Thanks, just messed up something with the config files.
