### ISSUE TITLE
Postgresql Can't resolve reference to Tasks.Extensions in editor/designer

### ISSUE THREAD

**Issue by vanceism7** [fsprojects/SQLProvider#502]
### Description
This is related to issue #373. When setting up a SqlDataProvider to work with postgres database, compiler complains that it cant resolve the reference as follows:

> Error	FS3033	The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
> Details: 
> Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.	

Following the steps outlined in #373, I copied the task extensions dll to the npgsql packages folder, upon which, the project now does successfully build, however, the editor still highlights the line of code setting up the data provider as if the error still exists. It seems that in design time, the reference can't be resolved and so intellisense fails from that point forward. 

### Repro steps

Please provide the steps required to reproduce the problem

1. Create new f# .net core class library project
2. Nuget install SQLProvider 1.1.23 and Npgsql 3.2.6
3. Specify npgsql respath: @"<UserFolder>\.nuget\packages\npgsql\3.2.6"
4. Copy System.Threading.Tasks.Extensions.dll (any target) to npgsql 3.2.6 folder used above
5. Build project

### Expected behavior
Designer error should have went away, allowing me to use the sql connection I had created

### Actual behavior
Editor underlines the code and continues to list "Unable to resolve assembly reference" as an error. 
```
type sql = 
        SqlDataProvider<
            dbVendor,
            connString,
            "",         //ConnectionNameString can be left empty 
            resPath,
            indivAmount,
            useOptTypes>
```
But the compiler builds with no issues

### Known workarounds
None that I've seen so far. I tried different versions of task extensions. Tried npgsql 3.2.5 and 3.1.0. Also tried install task extensions into my project itself

It seems that merely by setting the dbvendor like so
`let [<Literal>] dbVendor = Common.DatabaseProviderTypes.POSTGRESQL`
causes the error to come up. 

### Related information 
* Postgresql 9.6
* Windows 10 x64
* Visual Studio 2017 v15.5.2
* .NET Core 2.0
* FSharp.Core 4.2.3

**Comment by Thorium** [comment]
Interesting... VS2017 is running under net47x I suppose. Is this a VS issue? What version of Tasks.Extensions.dll you are using?

**Comment by vanceism7** [comment]
I tried it with 4.3.0 and 4.4.0. Didnt really think about it but it could just be a vs issue. I'll see if I can give it a try with vscode and check if that one has any issues

**Comment by Thorium** [comment]
Also define which fsc.exe (fsharp compiler) to use in a project file. See: https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/Postgres/SqlProvider.Core.Tests.fsproj

**Comment by vanceism7** [comment]
Ok well this definitely turned out to just be an issue with visual studio. The compiler was working, and when I got vscode loaded up, everything also worked fine and there were no errors reported. Then after playing with visual studio a bit more, all of the fuss randomly stopped and everything is working great now. Thanks for your help with the issue!
