### ISSUE TITLE
Union of parametrized queries does not work (MSSQL)

### ISSUE THREAD

**Issue by ScRyX** [fsprojects/SQLProvider#505]
### Description

When doing a .Union of two queries that each accept a parameter, only one of the two needed parameters is supplied and SqlException is thrown, with the message: "Must declare the scalar variable "@paramnested1""

### Repro steps
Let's have a function that filters a query based on a string parameter:
```
let filterQuery (arg:string) (q:IQueryable<SqlEntity>) =
    query {
        for x in q do
        where ((x.GetColumn<string> "Id").Equals arg)
        select x
    }
```

We have a simple select query:
```
let q = query {
    for req in ctx.Dbo.MyEntity do
    select req
}
```
And we want to to filter this query using our function `filterQuery` with two different arguments, then get a union of these results:
```
let q1 = q |> filterQuery "arg1"
let q2 = q |> filterQuery "arg1"
q2.Union q1 // crashes here with the aforementioned exception
```
When I display the generated query, it is indeed a union of two selects, and there are two arguments, the argument of one of the queries is called @param1 and its value is sent to the server. The other param, however, is named @paramnested1 and its value is not sent, that's what the exception is about.

### Expected behavior

A union of two parametrized queries is generated with the correct parameters supplied

### Actual behavior

SqlException is thrown, with the message: "Must declare the scalar variable "@paramnested1""
Full message:
```
"An unhandled exception occured: System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable \"@paramnested1\".\r\n   at Microsoft.FSharp.Linq.QueryModule.CallGenericStaticMethod@330.Invoke(Tuple`2 tupledArg)\r\n   at Microsoft.FSharp.Linq.QueryModule.clo@1730-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )\r\n   at
```

### Known workarounds

N/A

### Related information 

* Used database: MSSQL
* Operating system: Windows
* .NET Runtime, CoreCLR or Mono Version: .NET Core 2

**Comment by Thorium** [comment]
Thanks, good finding. I'll fix...

**Comment by Thorium** [comment]
Fixed in version 1.1.27.

**Comment by Thorium** [comment]
Hmm. We might still have an issue if you are planning to do not just one but multiple unions all having parameters, then paramnested1 ... paramnestedN is not enough, we should rename the deeper unions to have different names like param-nestend-nestend-...-nested-N or something.

**Comment by Thorium** [comment]
That should do (in 1.1.28).
