### ISSUE TITLE
MySQL unsigned dataType parameter contains F#  symbols

### ISSUE THREAD

**Issue by nojaf** [fsprojects/SQLProvider#506]
### Description

I have a MySql table with Unsigned integer and a tinyint column.
The F# code maps this correctly to `UInt` and `Byte` but when using these columns in a where clause the F# notation is present in the parameter value

### Repro steps

Please provide the steps required to reproduce the problem

```fsharp
query {
                for afi in myCtx.MyDb.AppFeedItems do
                where (afi.TeamId = tId &&
                 afi.ProjectId = projectId && 
                 afi.Deleted = (0uy) &&
                 afi.File.IsSome &&
                 afi.ImageresizerioId.IsSome)
                sortByDescending (afi.DateCreated)
                select ({ 
                    Id = (int)afi.Id; 
                    File = afi.File.Value; 
                    Description = afi.Description; 
                    ImageResizerData =  afi.ImageresizerioId.Value
                    Lat = afi.Latitude
                    Lng = afi.Longitude
                    Created = (int)afi.DateCreated
                })
            } |> Seq.executeQueryAsync
```

`Deleted` is a tinyint, `TeamId` is an unsigned.

I can see the following in the logs:

```
Executing SQL: SELECT `afi`.`id` as `id`,`afi`.`file` as `file`,`afi`.`description` as `description`,`afi`.`imageresizerio_id` as `imageresizerio_id`,`afi`.`latitude` as `latitude`,`afi`.`longitude` as `longitude`,`afi`.`date_created` as `date_created` FROM rds2016.app_feed_items as `afi` WHERE ((`afi`.`imageresizerio_id` IS NOT NULL AND (`afi`.`file` IS NO
T NULL AND (`afi`.`deleted` = @param3 AND (`afi`.`team_id` = @param4 AND `afi`.`project_id` = @param5)))))ORDER BY `afi`.`date_created` DESC  - params @param3 - 0uy; @param4 - 11730u; @param5 - 71u;
```

### Expected behavior

`@param3 - 0uy;`,`@param4 - 11730u;`,`@param5 - 71u;` all should not have the *uy* or *u*. Remove that and the query returns the expected result.

### Actual behavior

Query does not return any rows.

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Used database `MySQL`
* Operating system `Win 10`
* .NET Runtime, CoreCLR or Mono Version `netcoreapp2.0`

```
nuget MySqlConnector 0.33.1
nuget SQLProvider 1.1.23 framework: net451
```

**Comment by Thorium** [comment]
I think the actual query executed is actually working, the 'u' is printed for the event ToString only, as for some reason the query parameters are printed with .NET formatting '%A'.

If the query is not producing expected result, it is worth of noting that `afi.Deleted = (0uy)` will filter the columns where `afi.Deleted = null` but if you take out the condition, then all the fields are included.

**Comment by nojaf** [comment]
Thanks, I'll try it this evening. But how do I filter on `IsDeleted = false` then?

**Comment by Thorium** [comment]
if you have parameter `UseOptionTypes=true`, use `afi.Deleted.IsNone || afi.Deleted.Value = 0uy` and if you don't, then it should work by saying `afi.Deleted = null || afi.Deleted <> 1uy`, and if that doesn't compile try `box(afi.Deleted) = null || afi.Deleted = 0uy` or there can be more simpler ways also, but these were the first I thought of.
