### ISSUE TITLE
Query with nested exists results in "Ensure all server-side objects..." exception

### ISSUE THREAD

**Issue by HeinzmeierDornbuschFeldhausen** [fsprojects/SQLProvider#522]
### Description

Hello. I'm trying to do a query with a nested "exists" on two tables with columns that are non-nullable int. Actually I'm trying to do a "not exists" kind of query but even the plain exists version gives me an exception.

The exists subquery works fine when I'm executing it on its own.

### Repro steps
        query {
		for table1 in ctx.Dbo.Table1 do
		where (query {
                    for table2 in ctx.Dbo.Table2 do
                    exists (table1.Table1Id = table2.Table2Id)
                })
                select (table1.Table1Id)
        } |> Seq.toList

### Expected behavior

All records from Table1 that exist in Table2 as well.

### Actual behavior

Exception: "Ensure all server-side objects won't have any .NET-operators/methods that can't be converted to SQL. The In and Not In operators only support the inline array syntax"

### Known workarounds

I guess you could execute the subquery later in the select. But in this case I'd rather not because there are a lot of rows.

Maybe a left outer join would work as well but I'm not sure if this is supported yet.
 
### Related information 

mssql 
win7-64 bit
net451
SQLProvider 1.1.36

**Comment by Thorium** [comment]
Thanks for reporting this.
As a workaround you can do either
```fsharp
query {
    for table1 in ctx.Dbo.Table1 do
    join table2 in ctx.Dbo.Table2
        on (table1.Table1Id = table2.Table2Id)
    select (table1.Table1Id)
} |> Seq.toList
```
or

```fsharp
open System.Linq
let nested = query {
    query {
        for table2 in ctx.Dbo.Table2 do
        select table2.Table2Id
    }
query {
    for table1 in ctx.Dbo.Table1 do
    where nested.Contains(table1.TableId)
} |> Seq.toList
```

**Comment by Thorium** [comment]
Left join is supported via operator (!!) http://fsprojects.github.io/SQLProvider/#Example
and more about supported syntax
http://fsprojects.github.io/SQLProvider/core/querying.html#Supported-Query-Expression-Keywords
although we should add mention that this kind of return-a-constant-value keywords cannot be used
in sub-query where-results as conditions, at least not right now.

**Comment by HeinzmeierDornbuschFeldhausen** [comment]
Thanks for the quick reply. This worked for me:
> not(x.Contains(y))

Sadly, I can not create relationships to use with (!!) for these tables.

**Comment by Thorium** [comment]
With 1.1.58 the `(!!)` can be used without relationships.

**Comment by HeinzmeierDornbuschFeldhausen** [comment]
Cool! I'll give it a try soon.

**Comment by Thorium** [comment]
Also the original Exists query is now supported.
