### ISSUE TITLE
MapTo causes crashes when used with Option types.

### ISSUE THREAD

**Issue by matthewblott** [fsprojects/SQLProvider#525]
Consider the following. I have a really simple ```Users``` table with three fields: ```Id```, ```FirstName``` and ```LastName```. ```FirstName``` is required but ```LastName``` isn't and accepts a ```null``` value such as that in the following insert query.

```
insert into Users (FirstName, LastName) values ('Joe', null)
```

I create a simple function to extract a single record based on its ```Id``` value like so.

```
let getById id =
  query {
          for user in users do
          where (user.Id = id)
          select user
          exactlyOne
  }

```

I wish to check the value of the ```LastName``` field for a record and do so with the following.

```
let user = getById 1

user.LastName
```

This returns the following as expected.

```
val it : Option<string> = None
```

Now I want to make things a bit more organised and introduce a record type.

```
type User = { 
  Id : int ;
  FirstName : string ;
  LastName : Option<string> ;
}
```

So I adjust my ```getById``` function accordingly.

```
let getById id =
  query {
          for user in users do
          where (user.Id = id)
          select (user.MapTo<User>())
          exactlyOne
  }

```

I then execute the code from earlier to extract the ```LastName``` value and it works as before. However, if I update the field and provide a value other than ```null``` the code crashes. I have to adjust my record type and make the ```LastName``` field of type ```string``` and not ```Option<string>```. This lets my code run but it means I'm getting the default value for whatever the data type maps to the corresponding SQL type (```0``` for ```int```, ```01/01/0001 00:00:00``` for ```DateTime``` etc). Is there any way round this so I can use the ```Option``` type and still have the option of returning ```None``` for values that don't exist in the database?

* Used database
SQL Server 2017 (on Linux)
* Operating system
macOS
* Branch
Mono 5.8.0.127

### Update after sometime messing around with this!

Unfortunately it seems to work differently to how I thought and the returned field type is based on the data for that row and not the schema itself. For example, a nullable field of type ```datetime``` will return a ```None``` value for the field type ```Option<DateTime>```. So to make this match the record type must have a corresponding field of ```Option<DateTime>```. However, if this is set and another row has a positive ```datetime``` value there is a runtime error saying ```DateTime``` cannot be matched with ```Option<DateTime>```. This is quite confusing and difficult to work around.

**Comment by matthewblott** [comment]
# Update

Unfortunately it seems to work differently to how I thought and the returned field type is based on the data for that row and not the schema itself. For example, a nullable field of type ```datetime``` will return a ```None``` value for the field type ```Option<DateTime>```. So to make this match the record type must have a corresponding field of ```Option<DateTime>```. However, if this is set and another row has a positive ```datetime``` value there is a runtime error saying ```DateTime``` cannot be matched with ```Option<DateTime>```. This is quite confusing and difficult to work around.

**Comment by Thorium** [comment]
As a workaround you can write your creation of the item directly to the select clause and not use MapTo.

**Comment by matthewblott** [comment]
Yeah that seems to be the way to go. I created the following record type.

```
type User = { 
  Id : int ;
  FirstName : string ;
  LastName : Option<string> ;
  Active : Option<bool>
  CreatedOn : Option<DateTime>
}

```

And adjusted my ```getById``` function accordingly.

```
let getById id =
  let user =
    query {
            for user in users do
            where (user.Id = id)
            select user
            exactlyOne
    }
  { 
    Id = user.Id ;
    FirstName = user.FirstName ;
    LastName = user.LastName ;
    Email = user.Email ;
    Active = user.Active ;
    CreatedOn = user.CreatedOn
  }

List.map (fun x -> (getById x)) [1..5]

```

And tested it with the following.

```
List.map (fun x -> (getById x)) [1..5]
```

... using the following records.

![s 2018-03-04 at 10 43 01](https://user-images.githubusercontent.com/1231417/36944647-df6e4016-1f98-11e8-93da-de93f9efab0d.jpg)

No crashes. It's a bit strange as I'm not doing any explicit checking but if I substitute the field assignment for a simple ```MapTo``` it crashes. It would be nice to just use ```MapTo``` and avoid all the boilerplate of field assignment but at least it works.

**Comment by Thorium** [comment]
I have not used MapTo as I use just entities as is, and transfer them as described in the bottom of the page:
http://fsprojects.github.io/SQLProvider/core/mappers.html

But yes there is valid cases to use MapTo sometimes.

**Comment by Thorium** [comment]
You can provide optional type mapping parameter for MapTo-method.
