### ISSUE TITLE
``Create(...)`` method with primary key parameter

### ISSUE THREAD

**Issue by kerams** [fsprojects/SQLProvider#532]
### Repro steps

Create a table:
```sql
CREATE TABLE [dbo].[Teams](
	[Id] [nvarchar](100) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Teams] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
```

### Expected behavior

I expected ctx.Dbo.Teams.Create(Id, Name) to be generated, since `Id` is not an identity and I need to provide my own value for it.

### Actual behavior

Only ctx.Dbo.Teams.Create(Name) is generated.

### Known workarounds

It's of course possible to assign the value once the row is created using the other method.

**Comment by Thorium** [comment]
May I ask which database you are using?

**Comment by kerams** [comment]
Sorry, the SQL DB on Azure.

**Comment by kerams** [comment]
`COLUMNPROPERTY(object_id(pk.TABLE_SCHEMA+'.'+pk.TABLE_NAME), pk.COLUMN_NAME, 'IsIdentity') AS IsIdentity` could be added to https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.MsSqlServer.fs#L515 to check for identity. Then it should be just a matter of editing the condition in https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/SqlDesignTime.fs#L413. I could start a PR for this if you like, but it would only be the SQL server part.

**Comment by Thorium** [comment]
The basic idea is that auto-generated and nullable columns are not in ``Create(...)```. But there are no standard SQL-way of detecting what is auto-generated and what not. For that reason I don't want to create more overrides for Create-methods but this has to be dealt independently on each database (=only MSSQL). 

I don't mind breaking changes as long as the code works. 

https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.MsSqlServer.fs#L514 
The reason for gathering primary keys is not related to Create-method: We need to populate pkLookup dictionary for crud-operations, mainly to generate update-clause. So it's absolutely clear that when you update entity x, it will not hit multiple items.

The current special cases are:
1) Primary key is formed from multiple columns. This should work.
2) There is no primary key at all. You can still insert records, but not update those.

**Comment by Thorium** [comment]
With the latest changes, there seems to be a problem still.
I have columns which are primary keys, but they are type of uniqueidentifier, not int.
 
These Ids are not security related and I want SQL server to generate them in ascending order, to maintain the datatable performance. So they cannot be generated on .NET side, but with SQL default value, `(newsequentialid())`.

These are not working anymore after the latest.

**Comment by Thorium** [comment]
Better check than IsIdentity would be: does it has `COLUMN_DEFAULT`
But that would probably break a lot of existing code...
So should we go with something like `(IsIndentity || (IsPrimaryKey && HasDefault))` ?

**Comment by kerams** [comment]
Shouldn't `COLUMN_DEFAULT` be treated a bit like `IsNullable`? Only columns satisfying `(not c.IsNullable) && (not c.IsIdentity) && (not c.HasDefault)` would get a parameter in the Create method.

**Comment by kerams** [comment]
Or alternatively omit only `IsIdentity` columns. Those that are nullable or have defaults would take option types.

**Comment by Thorium** [comment]
Good point

**Comment by Thorium** [comment]
I hope this is enough now as in 1.1.41

**Comment by kerams** [comment]
Thanks 👍

**Comment by kerams** [comment]
It would be nice to mark the "overload" that uses `backwardCompatibilityOnly` as deprecated though. Runtime exceptions are thrown in certain scenarios after all.

**Comment by Thorium** [comment]
Hmm, deprecated is a warning attribute and due to many using treat-warnings-as-errors it's not very useful. So now there is a mention in a tooltip.

**Comment by charlesroddie** [comment]
Say we have a table with a GUID field and a string Email field. We can see:

Create(Email:string): This builds but xaml docs say `This will be obsolete soon. Migrate away from this!`
Create(Email:string, Id:Guid): intellisense is happy but building gives error: `The member or object constructor 'Create' does not take 2 argument(s). An overload was found taking 0 arguments.`

The same goes for the equivalent methods with \``` \``` names.
