### ISSUE TITLE
InvokeAsync on a sproc throws at runtime

### ISSUE THREAD

**Issue by kerams** [fsprojects/SQLProvider#535]
### Repro steps

1. Run the script:
```sql
CREATE TABLE [dbo].[Teams](
	[Id] [nvarchar](100) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[IsBotMember] [bit] NOT NULL,
 CONSTRAINT [PK_Teams] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE PROCEDURE AddBotToTeam
(
    @teamId nvarchar(100),
    @teamName nvarchar(100)
)
AS
BEGIN
    SET NOCOUNT ON

    UPDATE dbo.Teams SET IsBotMember = 1 WHERE Id = @teamId

	IF @@ROWCOUNT = 0
		INSERT INTO dbo.Teams (Id, Name, IsBotMember) VALUES (@teamId, @teamName, 1)
END
GO
```

2. Run the code:
```fsharp
let ctx = Db.GetDataContext ()
ctx.Procedures.AddBotToTeam.InvokeAsync ("", "") |> Async.RunSynchronously
```

### Expected behavior

The stored procedure is called without errors.

### Actual behavior

The stored procedure does not get called and an exception is thrown:
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.FSharp.Control.FSharpAsync`1[FSharp.Data.Sql.Common.SqlEntity]' to type 'Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.Unit]'.
   at <StartupCode$FSI_0009>.$FSI_0009.main@()
```

### Known workarounds

Call the synchronous variant of the method.

### Related information 

* Used database - Azure SQL DB
* SQLProvider version 1.1.39

**Comment by Thorium** [comment]
Fixed in Nuget version 1.1.40.

**Comment by kerams** [comment]
Sweet, it works. Many thanks.

**Comment by kerams** [comment]
Hi, @Thorium, I am seeing a problem that is possibly caused by the fix of this issue. Unit-returning InvokeAsync now silently ignores a failure in the stored procedure even though I would expect it to throw like the synchronous version.
