### ISSUE TITLE
Unable to load one or more of the requested types 

### ISSUE THREAD

**Issue by esow** [fsprojects/SQLProvider#543]
### Description

When trying to build my project (.net core 2.0) i get the following error:

error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.Details: Could not load file or assembly 'System.Configuration.Install, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system can
not find the file specified. [OMITTED\GiraffeSample\src\GiraffeSample\GiraffeSample.fsproj]
OMITTED\GiraffeSample\src\GiraffeSample\Database.fs(14,12): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.Details: Could not load file or assembly 'System.Configuration.Install, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system can
not find the file specified. [OMITTED\GiraffeSample\src\GiraffeSample\GiraffeSample.fsproj]

### Related information 
* MySQL
* Windows 10
* .NET Core 2.0

**Comment by Thorium** [comment]
Possible duplicate of #542

**Comment by esow** [comment]
@Thorium That seems to be a different .dll file missing

**Comment by Thorium** [comment]
Yes, but the root cause is the same: You have to copy the dll to the ResolutionPath folder.

**Comment by esow** [comment]
I tried downloading and moving "System.Configuration.Install.dll" to my ResPath.. Still same results

**Comment by Thorium** [comment]
Can you try the MySqlConnector driver? It's kind of more stable than MySql.Data for .NET Core at this point.

**Comment by esow** [comment]
I can try!

Is it this one: https://dev.mysql.com/downloads/connector/net/ ?

**Comment by esow** [comment]
Ok i figured it out! It seems to be working with MySQLConnector. Thanks!

**Comment by Thorium** [comment]
The documentation here: fsprojects.github.io/SQLProvider/core/mysql.html#Suppport-for-MySqlConnector
