### ISSUE TITLE
.NET Standard - issues referencing library that uses SQLProvider

### ISSUE THREAD

**Issue by MaciekTheFinalForm** [fsprojects/SQLProvider#547]
### Description

I have a project that successfully talks to DB, but the same function fails when referenced from another project.

### Repro steps

1. Clone https://github.com/MaciekTheFinalForm/sqlIssueMinimalExample
2. `dotnet run` on DataAccessApp project
2. `dotnet run` on ActualApp project

### Alternative repro steps

1. Create a function that some retrieves data from Db
2. Call that function in the project
3. Call that function in another project

### Expected behavior

Both executions succeed

### Actual behavior

Only first execution succeeeds. The second fails with 

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Data.SqlProvider, Version=1.1.42.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### Related information 

* Postgres
* Operating system: Windows 10
* Branch: v1.1.42
* `dotnet --version` is 2.1.4

**Comment by MaciekTheFinalForm** [comment]
It is working on runtime, just not when called from another assembly. How can I fix it?

**Comment by MaciekTheFinalForm** [comment]
That did help, thanks a lot! 

Just to be sure: when you said 

> On runtime you can use the .NET Standard dll

you actually meant 

> On runtime you **need to** use the .NET Standard dll

?

**Comment by Thorium** [comment]
It depends on .NET Standard backward compatibility, but I think the current short answer is yes. :-)
