### ISSUE TITLE
The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: The ConnectionString property has not been initialized.

### ISSUE THREAD

**Issue by adam-becker** [fsprojects/SQLProvider#549]
### Description

The following code (or similar) compiles and works just fine, but when hovering my mouse over a table column, I see the message in the title instead of the type information you'd normally expect.

```f#
type SomeDbNameHere =
  SqlDataProvider<
    DatabaseProviderTypes.MSSQLSERVER,
    ConnectionStringName = "SomeDbNameHere",
    UseOptionTypes = true
  >


let ctx = SomeDbNameHere.GetDataContext()


type UserModel =
  { firstName : string;
    lastName : string;
  }


let users =
  query {
    for user in ctx.Dbo.Users do
    where (user.IsActive)
    select
      { firstName = user.First;
        lastName = user.Last;
      }
  }
  |> Seq.toArray
```

For example, if I hover over `First` in `user.First;` I won't see any type information, just the error message. The code does compile and run just fine, but thought this was odd.

### Expected behavior

I'd expect to see type information in the tool-tip.

### Actual behavior

I see an error in the tool-tip.

### Related information 

* Microsoft SQL Server
* Windows 7
* .Net 4.6.1

**Comment by Thorium** [comment]
Can this be a network error, i.e. if you restart VS will it help?

**Comment by adam-becker** [comment]
I restarted VS several times and still saw the error, if I move the code to just create the `ctx` variable into a separate module then things appear to work as expected..

**Comment by piaste** [comment]
What happens if you change the connection string (eg. by adding a semantically-insignificant space), forcing a connection refresh?
