### ISSUE TITLE
[Question] Generic function with table and where as arguments

### ISSUE THREAD

**Issue by MNie** [fsprojects/SQLProvider#554]
### Description

I have separate functions which simply do the same: query some table with some `where` statement to get the number of results.

I thought it would be a good idea to have some generic function which would accept a table and where statement as arguments.

### Repro steps

I write a function like this:

```fsharp
type db = SqlDataProvider<
                    ConnectionString = "connection",
                    DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER,
                    UseOptionTypes = true
                >
let ctx = db.GetDataContext()

let func tbl whereStatement = query {
        from r in tbl do
        where (whereStatement r)
        select 1
    }
```

and want to invoke it like this:

```fsharp
func ctx.Dbo.Table (fun x -> x.SomeColumn = None)
```

### Expected behavior

It would be great if code like this would work :)

### Actual behavior

Exception:
![image](https://user-images.githubusercontent.com/7689103/41196034-729a242c-6c38-11e8-8e3a-67687793fcca.png)

### Known workarounds

When the function is defined without where statement everything seems to works fine:

```fsharp
let func tbl = query {
        from r in tbl do
        select 1
    }

func ctx.Dbo.Table
```

Right now to omit this problem I simply wrote separate functions, but maybe there is some possibility to do what I want?

### Related information 

* Used database: MS Sql 2017
* Operating system: Windows 10 PRO
* Branch: 1.1.42
* .NET Runtime, CoreCLR or Mono Version: .net core 2.0

**Comment by piaste** [comment]
This can work, but you need to pass a quotation, not a simple function.

```
// Expr<dataContext.(..).ThingsEntity -> bool> -> seq<dataContext
.(..).ThingsEntity>
let getThings filter = query {
  for thing in ctx.Things do
  where ((%filter) thing) // quotation resolution syntax
  select thing
}

let things =
  getThings  <@ fun thing ->
    thing.SomeProperty = "foo"
  @>
```

**Comment by piaste** [comment]
This can work, but you need to pass a quotation, not a simple function.

```fsharp
// Expr<dataContext.(..).ThingsEntity -> bool> -> seq<dataContext
.(..).ThingsEntity>
let getThings filter = query {
  for thing in ctx.Things do
  where ((%filter) thing) // quotation resolution syntax
  select thing
}

let things =
  getThings  <@ fun thing ->
    thing.SomeProperty = "foo"
  @>
```

**Comment by MNie** [comment]
@piaste neat! Thanks!

**Comment by Thorium** [comment]
There are multiple ways to generate "common code" and I'm all in for having the options in our documentation.
Would [this](http://fsprojects.github.io/SQLProvider/core/composable.html) be a good place?
These ways can be combined to have arbitrary complex source code. :-P

### 1. A common database view. 
This is somewhat preferable as view can be queried from SQLProvider, and this way you have good maintainability: To check if database indexing works and you probably have more people maintaining SQL-queries than F# code. 

### 2. Using non-strongly-typed __.GetColumn "name"
...for example:

```fsharp
let qry = 
    query {
        for x in myContext.Main.Customers do
        where ((x.GetColumn<string> "CustomerId") = "ALFKI")
        select (x.GetColumn<string> "CustomerId")
    } |> Seq.head
```

### 3. Calling System.Linq methods explicitly 
...by defining functions types explicitly.

```fsharp
let myContext = myContext.GetDataContext()
let myFilter : IQueryable<myContext.dataContext.``main.CustomersEntity``> -> IQueryable<myContext.dataContext.``main.CustomersEntity``> = 
    fun x -> x.Where(fun i -> i.CustomerId = "ALFKI")

let qry = 
    query {
        for x in myFilter(myContext.Main.Customers) do
        select x.CustomerId
    } |> Seq.head

```

### 4. Using quotations 
...as @piaste's example above.

**Comment by MNie** [comment]
@Thorium I couldn't find that in a documentation, thanks! It helps me a lot I used a proposition number 4 cause it looks the best for me :)
