### ISSUE TITLE
Count of group translated to SQL incorrectly

### ISSUE THREAD

**Issue by red-swan** [fsprojects/SQLProvider#563]
### Description

`grp.Count()` gets translated to SQL as `COUNT(1)`

### Repro steps

1. Write a query expression to look for rows that, when grouped, have a count above an amount. E.g.
```
query {
            for aic in aix.Dbo.AnalystIndexCategory do
            where (categories.Contains aic.IndexCategoryCode)
            groupBy aic.AnalystIndexId into idx
            where (idx.Count() >= n)
            select idx.Key }
```

### Expected behavior

I would expect the SQL to bring back groups that have more than n items.

### Actual behavior

Nothing is brough back. The above expression is translated to:
```
SELECT [aic].[AnalystIndexID]
FROM [dbo].[AnalystIndexCategory] AS [aic]
WHERE ( ([aic].[IndexCategoryCode] IN (@param1, @param2)))
GROUP BY [aic].[AnalystIndexID]
HAVING ( (COUNT (1) > @param3)) 
-- params @param1 - "ERP"; @param2 - "GIG"; @param3 - 2;
```
The `COUNT` function is the offender here -it's not counting the group key.

### Known workarounds

`N/A`

### Related information 

* Microsoft SQL Server 2012 (SP3-GDR) (KB4057115) - 11.0.6260.1 (X64) 
	Jan  9 2018 21:31:12 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
* Windows 7 Enterprise
* SQLProvider.1.1.45
* .NET 4.7.1

**Comment by Thorium** [comment]
Are you sure that it's incorrect?
Group by index should give always only one result, so it shouldn't ever exceed 2 or am I missing something here?

Is the 
```sql
SELECT [aic].[AnalystIndexID]
FROM [dbo].[AnalystIndexCategory] AS [aic]
WHERE ( ([aic].[IndexCategoryCode] IN (@param1, @param2)))
GROUP BY [aic].[AnalystIndexID]
HAVING ( (COUNT (1) > @param3)) 
```
giving the same result as 
```sql
SELECT [aic].[AnalystIndexID]
FROM [dbo].[AnalystIndexCategory] AS [aic]
WHERE ( ([aic].[IndexCategoryCode] IN (@param1, @param2)))
GROUP BY [aic].[AnalystIndexID]
HAVING ( (COUNT ([aic].[AnalystIndexID]) > @param3)) 
```
as counting the items is basically counting the items, no matter over what columns, isn't it? 
I think the only exception would be `COUNT(DISTINCT something)` but that is probably not what you are after anyway.

**Comment by red-swan** [comment]
You're correct. I'm just bad at query expressions.
(‘-’*)
