### ISSUE TITLE
Issue with SaveContextSchema and stored procedures

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/SQLProvider#571]
I have a stored procedure call:

```f#
ctx.Procedures.MyStoredProcedure.Invoke ()
```

It works fine if I don't use `SaveContextSchema` and `ContextSchemaPath`. But once I add those, I get the following error:

`error FS0039: The field, constructor or member 'Procedures' is not defined.`

![image](https://user-images.githubusercontent.com/7766733/44585184-c28bfb00-a7ab-11e8-83fa-74d405213eb0.png)

As soon as I remove `ContextSchemaPath`, everything works again. Note that it only happens with the `Procedures` property; tables seem to work fine with `ContextSchemaPath` and `SaveContextSchema`.

### Related information 

* Database: MSSQL
* Operating system: Windows 10
* Branch: NuGet 1.1.48

**Comment by piaste** [comment]
@Thorium should have fixed this in 1.1.49. See https://github.com/fsprojects/SQLProvider/pull/566

**Comment by Thorium** [comment]
Yes, but I had updated my computer so the NuGet-key wasn't in the place, so the 1.1.49 package never ended up to NuGet. Sorry, I'll try to fix it.

**Comment by Thorium** [comment]
When you update SQLProvider from 1.1.48 to 1.1.49, remove first the 1.1.48 ContextSchemaPath file.
