### ISSUE TITLE
Should GetDataContext be called once for the whole app, or once per operation?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/SQLProvider#572]
Should I call `GetDataContext` once and always re-use it, or should I call `GetDataContext` once per operation to the DB? I tried looking in the docs but couldn't find any clear guidance.

Does the answer change depending on whether I'm doing async or sync? (I'm creating an ASP.NET Core app, if it matters.)

**Comment by Thorium** [comment]
Per transaction/operation/unit of work.

So it depends your use case. E.g. if you have a script for yourself feel free to share it, but if you have a  web-server, I won't recommend sharing the context.

**Comment by piaste** [comment]
I think the preference is to use fresh new contexts as much as possible. Besides opening new database connections, each context keeps a cache of pending changes (for `.SubmitUpdates()`), so you'll have better control over your DB operations with separate context, especially when transactions enter the picture.

FWIW, my approach is to define a `unit -> MyDatabase.dataContext` context generator lambda at startup, then pass that to whichever parts of the program needs to access the db - this way they can generate fresh contexts without needing to know all the specific arguments used for `.GetDataContext()`.

**Comment by mauriciomagni** [comment]
Adding to the question asked by cmeeren, I am wondering if the GetDataContext uses a pooling mechanism for improving speed when creating DB connections. It is my understanding that Ms Sql connection are costly operations and that could lead to different approaches based on actual needs.
