### ISSUE TITLE
Visual Studio 2017 hangs on installation with a .NET Core app

### ISSUE THREAD

**Issue by WreckedAvent** [fsprojects/SQLProvider#574]
### Description

See title. 

### Repro steps

1. Open Visual Studio 2017

2. Create a new F# .NET Core Console Project

3. Install the package via nuget

### Expected behavior

The package installs successfully 

### Actual behavior

Visual Studio hangs and eventually, windows says the program is not responsive. 

---

Works fine with any non-Core projects. If you let it sit for long enough then your project is borked and you can't open it at all without Visual Studio ramping up CPU use and eventually getting the 'not responsive' prompt again. In case it's relevant, my .NET core version is 2.1 and the visual studio version is 15.8.2.

**Comment by Thorium** [comment]
Not in my machine.

I tried with VS 15.8.1 and dotnet 2.1.400 and it didn't hang the VS, packages restored and compiled ok.
Maybe this is a VS issue, did you try to report [here](https://developercommunity.visualstudio.com/topics/Known+Issue+in%3A+Visual+Studio+2017+Version+15.8.html)? 

So it shouldn't hang, however to actually use SQLProvider I do expect you need a bit more config than that.

**Comment by dsyme** [comment]
Yes, I couldn't repro this VS 15.8.3 just now, I think we should close this as it's not a SQLProvider issue

**Comment by gajo357** [comment]
I have the same issue in VS 15.9.9 and in 2019 preview.
There is only one empty project targeting .Net Standard.
It looks normal until I add SqlProvider NuGet package. Then in freezes and crashes.

**Comment by Thorium** [comment]
See #606 and https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/292

**Comment by Thorium** [comment]
Should be working in 1.1.61.
