### ISSUE TITLE
F# Language Service crashes with SQLProvider

### ISSUE THREAD

**Issue by bratfizyk** [fsprojects/SQLProvider#579]
### Description

I use VS Code with Ionide plugin. When I add SQLProvider, the addin dies as it says it was unable to parse my file.

### Repro steps

* Create a "fake" template (https://fake.build/fake-gettingstarted.html, dotnet new fake).
* Create a console project under src folder (dotnet new console -lang=F#).
* Build the project (./fake.sh build). 
* Open VS Code with Ionide installed.
* Make sure the "Program.fs" file works ok, and the Ionide plugin provides syntax completion, type hovers, etc.
* Add "SQLProvider" to the project.

### Expected behavior

I'd expect the SQLProvider not to break anything.

### Actual behavior

* The plugin throws an error:

[16:21:20 ERROR] Cannot execute parse, The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: One or more errors seen during provided type setup) 

### Known workarounds

???

### Related information 

* Operating system: Kubuntu 18.04
* dotnet version 2.1.402

**Comment by Thorium** [comment]
Is this SQLProvider error or Ionide error?

**Comment by bratfizyk** [comment]
Well... I think it's coming from Ionide, but I hoped for some hints here ;).
Feel free to close this issue as unrelated if you find it so. But in that case - would you mind redirecting me somewhere else ? I found the Ionide's github quite unresponsive.

**Comment by Thorium** [comment]
Should be working in 1.1.61.
