### ISSUE TITLE
Cannot connect to mySQL database on Ubuntu

### ISSUE THREAD

**Issue by adrianczuczka** [fsprojects/SQLProvider#582]
### Description

Hi, I'm trying to use SQLProvider to connect to a local mySQL database but I keep getting reflection errors. Specifically, I'm getting the error "Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies." I'm on Ubuntu and using JetBrains Rider. Also, my resolution path points to MySQLConnector 0.47.1. Here is a picture of the problem. I'm new to F# development, so please let me know if I'm missing something obvious.

![screenshot from 2018-11-10 15-36-57](https://user-images.githubusercontent.com/23706497/48303138-7d4fad80-e4fe-11e8-8722-0f7c2f14e9d2.png)

### Related information 

* Local mySQL database
* Ubuntu 18.04
* Target framework is .NET 4.6.1

**Comment by Thorium** [comment]
That version of MySQLConnector has a dependency to System.Memory.dll so that dll has to be also in the resolution path.
