### ISSUE TITLE
SQLite connections do not give access to VIEWs

### ISSUE THREAD

**Issue by ThomasRizzo** [fsprojects/SQLProvider#591]
https://github.com/fsprojects/SQLProvider/blob/dd36be45491fa377184bc408248a3b9cd49a3597/src/SQLProvider/Providers.SQLite.fs#L76

I'm not able to access sqlite views. Can they be added by simply appending ```OR type ='view'``` to the query in customGetSchema? (I'm new to both F# and SQLProvider). Thanks

**Comment by Thorium** [comment]
Good finding, I didn't even know SQLite supports views...

Are you using .NET Core (or Standard), or are you using Mono or .NET Framework full?

**Comment by ThomasRizzo** [comment]
I'm mostly using .NET Framework

**Comment by Thorium** [comment]
Ok, this seems important issue let me fix it right away...

**Comment by Thorium** [comment]
Fixed in Nuget package 1.1.56. It'll take a minute from NuGet to update its servers.

**Comment by ThomasRizzo** [comment]
Works great, thanks!
