### ISSUE TITLE
IndexOutOfRangeException when invoking a scalar function

### ISSUE THREAD

**Issue by TheJayMann** [fsprojects/SQLProvider#598]
### Description

When attempting to invoke a scalar function, before the database call can be made, an IndexOutOfRangeException occurs.

### Related information 

Version 1.1.45 works without issue.  Version 1.1.47 and later all appear to throw the exception.

**Comment by Thorium** [comment]
After 1.1.45 there were some work fixing SQL Server output parameters, I expect the bug is side effect of those changes.

**Comment by Thorium** [comment]
Fixed in 1.1.58.

**Comment by TheJayMann** [comment]
I can confirm this update fixed the issue.
