### ISSUE TITLE
The type initializer f threw an exception..InnerMessage: Could not load type 'System.Web.Hosting.HostingEnvironment' from assembly

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/SQLProvider#605]
### Description

I'm trying to use an app.config file to get the DataContext on runtime.

But getting following error message:

Can't get DataContext.
Message: The type initializer for '<StartupCode$..>.$Config' threw an exception..
 InnerMessage: Could not load type 'System.Web.Hosting.HostingEnvironment' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### Repro steps

Please provide the steps required to reproduce the problem

1. Adding CompileTime ConnectionString
`let [<Literal>] CompileTimeConnectionString = "Data Source=...."`

2. Get SqlType: 
`type Sql = SqlDataProvider<Common.DatabaseProviderTypes.MSSQLSERVER, ConnectionString=CompileTimeConnectionString,UseOptionTypes=true, ContextSchemaPath = ContextSchemaPath>`

3. Add RunTime ConnectionString to App.Config file:
```
 <connectionStrings>
    <add name="Db"  providerName = "System.Data.ProviderName" connectionString="Server=..."/>
 </connectionStrings>
```

4. Use FSharp.Configuration to receive ConnectionString from the App.Config
```
type Settings = AppSettings<"app.config">
open System.Configuration
let connectionString = Settings.ConnectionStrings.Db
```

5. Try to get DataContext with RunTimeConnection String
`let getDb () = SqlDme.GetDataContext connectionString `

### Expected behavior

Get GetDataContext without issues

### Actual behavior

Assembly File Missing Error

### Known workarounds

None

### Related information 

* MS SQL
* Win 10
* netCoreapp2.2

**Comment by Thorium** [comment]
I don't think this is an issue with SQLProvider.

If you do ```Sql.GetDataContext connectionString`` where the connectionString is a string it should work?

So you are just missing an assembly reference to e.g. System.Web or System.Web.Hosting when using something in there in your project. SQLProvider doesn't use System.Web at all, but maybe the configuration typeprovider does.

**Comment by tforkmann** [comment]
Yes, if the connection String is a string. The typeprovider works like a charm!

Ok, I guess this is related to the configuration typeprovider.

**Comment by tforkmann** [comment]
Ok, I got rid of the configuration typeprovider and used the standard System.Configuration module and it just works.
