### ISSUE TITLE
.NET Core app get Could not load file or assembly System.Configuration.Install

### ISSUE THREAD

**Issue by HotHat** [fsprojects/SQLProvider#608]
In .NET Core app get Could not load file or assembly System.Configuration.Install
But In .NET Framework app can add Reference in Reference Manage

How can i add System.Configuration.Install?

**Comment by Thorium** [comment]
What database?
MySQL? #543 

...or where is that dependency needed anyway? I think it's not directly SQLProvider dependency.

**Comment by HotHat** [comment]
@Thorium Thanks
