### ISSUE TITLE
Having trouble referencing .NET Standard class library using SQLProvider from .NET Core project

### ISSUE THREAD

**Issue by Arrow7000** [fsprojects/SQLProvider#617]
Reproduction of problem here: https://github.com/Arrow7000/SqlProviderTest

<hr/>

I'm fairly new to the .NET world so am having trouble wrapping my head around exactly what the problem is.

I've tried to use the SQL type provider directly in an F# .NET Core project, but had a bunch of problems getting it to work. From what I can tell that's due to incompatibilities between .net core and type providers.

So what I am trying instead is to have the SQL type provider code encapsulated in a .NET Standard project that I can reference from my main Core project.

I've managed to reproduce the problem in a minimal GitHub repo located here which demonstrates both that

- the type provider is working in Visual Studio 2019 with IntelliSense, but
- despite this I still get a build error when I try to start the Main project

The build error is:

```
Unable to find the file 'C:\projects\SqlProviderTest\SQLStuff\bin\Debug\netstandard2.0\SQLStuff.dll' in any of
 C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.2.0\ref\netcoreapp2.2
 C:\projects\SqlProviderTest\Main
 C:\Users\Aron\.nuget\packages\fsharp.core\4.6.2\lib\netstandard1.6
```

Why isn't the project reference simply working as expected? I've tried adding `<Private>True</Private>` to the project reference but that didn't make any difference

I know there are a bunch of similar issues in this repo but none of the solutions have worked for me. 

I originally [posted this on StackOverflow ](https://stackoverflow.com/questions/56102001/having-trouble-referencing-net-standard-class-library-using-sqlprovider-from-n) but someone there told me this repo might be a better place to ask the question.

<hr/>

P.S. in case it matters, I'm developing on Windows but the app gets deployed on a Docker container.

**Comment by Thorium** [comment]
I would expect you need not only MySqlConnector.dll but also its dependencies:
System.Buffers.dll, 
System.Threading.Tasks.Extensions.dll, 
System.Runtime.InteropServices.RuntimeInformation.dll, 
System.Data.Common.dll

See the example:
https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Core.Tests/MySql

**Comment by Arrow7000** [comment]
@Thorium I've now added those packages both as project dependencies and also directly as DLLs in this branch https://github.com/Arrow7000/SqlProviderTest/tree/add-deps. It still fails with the same error.

I have cloned the repo and it doesn't work. When I try to run `dotnet build` it fails with this error 

![image](https://user-images.githubusercontent.com/13225609/57717001-232cd200-7672-11e9-9dd2-43f98b109515.png)

When I try to run it in Visual Studio 2019 it fails because it can't find F# in the path - I think I have a newer F# version installed. But either way I don't want to hardcode my local F# path because that won't work when I deploy and build the code in a Docker container.

**Comment by Thorium** [comment]
For this project to build, you have to first restore packages by e.g.
running build.cmd

**Comment by Thorium** [comment]
I tried to clone your repo. You need to have the ResolutionPath to pointing a folder where these dlls are.

**Comment by Arrow7000** [comment]
I just tried adding the resolution path. See this commit https://github.com/Arrow7000/SqlProviderTest/commit/441e62a00dcc767a1434db01028f984b45f7f996

It's still giving the exact same error though 😕

However the SQLStuff.dll not being found is not the cause, but the effect of some other error preventing the dll from being built in the first place. How do I find out what this original error is?

![image](https://user-images.githubusercontent.com/13225609/57738151-35286800-76a6-11e9-94ee-b5685da7c25b.png)

**Comment by drk-mtr** [comment]
I don't know whether it's the same issue, but I hit similar problems. To see what,s going on, try building the class library from the command line. While in the folder run `dotnet build -v d`. The fix for me was this:

https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/244#issuecomment-485762600

**Comment by Thorium** [comment]
Should be fixed already
