### ISSUE TITLE
SQLProvider failed to build on Ubuntu

### ISSUE THREAD

**Issue by pmd3d** [fsprojects/SQLProvider#622]
### Description

Sorry, I'm a noob so I may be missing something. I git cloned the SQLProvider repo and ran build.sh in Ubuntu 16.04.6 LTS x64 and it failed.

### Repro steps

1. git clone https://github.com/fsprojects/SQLProvider.git

2. ./build.sh

### Expected behavior

build succeeded

### Actual behavior

Checking Paket version (downloading latest stable)...
Hash file of version 5.210.1 found in cache.
Copying version 5.210.1 from cache.
Done in 2.15 second(s).
Paket version 5.210.1
Extracted Paket.Restore.targets to: /tmp/SQLProvider/.paket/Paket.Restore.targets
Starting full restore process.
Downloading Thorium/Linq.Expression.Optimizer:c9c558f4b7774930d5103adebddd673f8271363d src/Code/ExpressionOptimizer.fs to /tmp/SQLProvider/paket-files/sourcefiles/Thorium/Linq.Expression.Optimizer/src/Code/ExpressionOptimizer.fs
Downloading fsprojects/FSharp.TypeProviders.SDK:18459e8b23b44b389dc8f2b8fe444fedf2b47a8c src/ProvidedTypes.fs to /tmp/SQLProvider/paket-files/sourcefiles/fsprojects/FSharp.TypeProviders.SDK/src/ProvidedTypes.fs
Downloading fsprojects/FSharp.TypeProviders.SDK:18459e8b23b44b389dc8f2b8fe444fedf2b47a8c src/ProvidedTypes.fsi to /tmp/SQLProvider/paket-files/sourcefiles/fsprojects/FSharp.TypeProviders.SDK/src/ProvidedTypes.fsi
Downloading fsharp/FAKE:502d1a20a31bd47ad93643ef618d647e0b1510c6 modules/Octokit/Octokit.fsx to /tmp/SQLProvider/paket-files/standard/fsharp/FAKE/modules/Octokit/Octokit.fsx
Performance:
 - Disk IO: 18 seconds
 - Average Download Time: 311 milliseconds
 - Number of downloads: 4
 - Runtime: 24 seconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
   <== CleanDocs
      <== RunTests
         <== BuildCore
            <== Build
               <== AssemblyInfo
                  <== Clean

The running order is:
  - Clean
  - AssemblyInfo
  - Build
  - BuildCore
  - RunTests
  - CleanDocs
  - All
Running build with 1 worker
Starting Target: Clean 
/tmp/SQLProvider/bin does not exist.
/tmp/SQLProvider/temp does not exist.
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "src/SQLProvider/AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: /tmp/SQLProvider/SQLProvider.sln
  /usr/bin/msbuild  /tmp/SQLProvider/SQLProvider.sln /t:Rebuild    /p:RestorePackages="False" /p:Configuration="Release" /p:DefineConstants="LOCALBUILD" /logger:Fake.MsBuildLogger+ErrorLogger,"/tmp/SQLProvider/packages/FAKE/tools/FakeLib.dll"
﻿Microsoft (R) Build Engine version 16.0.0.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/23/2019 6:00:36 PM.
Project "/tmp/SQLProvider/SQLProvider.sln" on node 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "/tmp/SQLProvider/SQLProvider.sln" (1) is building "/tmp/SQLProvider/src/SQLProvider/SqlProvider.fsproj" (2) on node 1 (Rebuild target(s)).
/tmp/SQLProvider/src/SQLProvider/SqlProvider.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.
Done Building Project "/tmp/SQLProvider/src/SQLProvider/SqlProvider.fsproj" (Rebuild target(s)) -- FAILED.
Done Building Project "/tmp/SQLProvider/SQLProvider.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

"/tmp/SQLProvider/SQLProvider.sln" (Rebuild target) (1) ->
"/tmp/SQLProvider/src/SQLProvider/SqlProvider.fsproj" (Rebuild target) (2) ->
  /tmp/SQLProvider/src/SQLProvider/SqlProvider.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.74
Running build failed.
Error:
Building /tmp/SQLProvider/SQLProvider.sln failed with exitcode 1.

### Known workarounds

Unknown

### Related information 

Ubuntu 16.04.6 LTS

Linux FSharp 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:09:21 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by Thorium** [comment]
Weird, as CI-build works on Ubuntu Mono. But the Mono is not the latest version there.

**Comment by pmd3d** [comment]
Hi. Do you want me to use the Mono from the default Ubuntu repo? I am just starting to learn so I can change my mono or make a new vm without much consequence.

**Comment by Thorium** [comment]
CI (Travis) is using Mono 5.0.1.

But the message `"error MSB4057: The target "Rebuild" does not exist in the project."` is usually a sign of some environment variable missing in the development environment, like MSBuildToolsPath, so what happens is a .target -file in the .fsproj-project is not found & loaded.

**Comment by pmd3d** [comment]
Maybe I missed installing something related to dotnet core then. I thought the mono devel package was enough. I see this link below. I will spin up a new vms and install the sdk then mono devel then git clone and build. 

https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current

**Comment by pmd3d** [comment]
Wanted to note issue #623 got a similar error in Windows in one of the posts from today (not the initial error). The error message was buried in a txt file link so I copy pasted here for clarity. 

2>C:\Users\mac2cyg\dev\temp\SQLProvider\src\SQLProvider\SqlProvider.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.

**Comment by Thorium** [comment]
I installed the VS2019 and found the issue.
Details here: https://github.com/fsprojects/Paket/issues/2264#issuecomment-506368815
It's now fixed in the master.
