### ISSUE TITLE
[Question] offline lookup for SqlDataProvider [info]

### ISSUE THREAD

**Issue by giuliohome** [fsprojects/SQLProvider#629]
Maybe this feature is already implemented, but let's say I have
```
type Sql = SqlDataProvider<
            Common.DatabaseProviderTypes.MSSQLSERVER, 
            @"Data Source=...;Initial Catalog=...;User ID=...;Password=...">
```
Now I compile my solution and I can double check all my type safe fields at compile time.
So far, so good.
Assume that I want to work offline for a period and I know that the DB is not changed and I want to code a different part of the solution, that is not DB related.
At the moment I'm not able to compile **offline**, but again maybe there is an option for the `SqlDataProvider` to cache/store the type info for this use case, is it possible?

**Comment by giuliohome** [comment]
I think I will solve this problem by moving the sql part into a separate lib that won't be compiled when I work on the rest of the project. I hope it should suffice.


Anyway, I'll keep this issue open for a while, just to receive any possible feedback from the others.

**Comment by Thorium** [comment]
Yes this is done, via the ContextSchemaPath parameter: https://fsprojects.github.io/SQLProvider/core/parameters.html#ContextSchemaPath

**Comment by giuliohome** [comment]
Awesome!!! Thank you very much for the link to the explanation. I tried to find it but I missed it. It looks perfect, at first glance, and I will study this parameter usage when back from holiday. Thank you again, sqlprovider is a great project.

**Comment by giuliohome** [comment]
This is what I've tried 
```fsharp
[<Literal>]
let contextSchemaPath =
    __SOURCE_DIRECTORY__ + @".\sqlserver.schema"
type Sql = SqlDataProvider<
            Common.DatabaseProviderTypes.MSSQLSERVER,
            @"my conn string...",
            ContextSchemaPath = contextSchemaPath >
```
Compiled under a woriking connection and then reopened offline...
**without** luck ... what I'm **still** missing? Thanks again

**Comment by giuliohome** [comment]
Understood! after fixing the misspelt ` __SOURCE_DIRECTORY__ + @".\blabla`  in the documentation (!) with a more likely ` __SOURCE_DIRECTORY__ + @"\.blabla`... I've also realized that `ContextSchemaPath` must be the path to a file to be created, not to a folder.
All's working as expected.
Thank you again!)
