### ISSUE TITLE
Can I use MapTo on a record with a child collection?

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/SQLProvider#640]
### Question

Is it possible to use `MapTo<Order>()` if I have a record type with a one-to-many relationship?
So far it looks like I would have to manually instantiate the record.

Ex:
```
type Order = {
  Id: int  
  OrderItems: OrderItem array
}
and OrderItem = {
  Id: int
  Desc: string
}
```

**Comment by Thorium** [comment]
I would like to see some examples how people use MapTo in real life, as there are no unit tests and I don't use it.

**Comment by Thorium** [comment]
MapTo is dealing with propertyname-to-obj maps, so it would be quite simple to add a small recursion to [this](https://github.com/fsprojects/SQLProvider/blob/f5bc62ddbe1d5171b97dcacf146c372cba5d4248/src/SQLProvider/SqlRuntime.Common.fs#L303).

**Comment by Thorium** [comment]
Update, yes you can, if you provide the mapping parameter function to MapTo-method. See #666
