### ISSUE TITLE
ColumnValues are sorted alphabetically

### ISSUE THREAD

**Issue by giuliohome** [fsprojects/SQLProvider#641]
### Description

Can I get - from `ColumnValues ` - the columns in the **original** order as they are defined in the table?

### Repro
Simply refer to the example in the [Documentation for Querying](http://fsprojects.github.io/SQLProvider/core/querying.html#Don-t-select-all-the-fields-if-you-don-t-need-them)

```fsharp
let someQuery =
    query {
        for customer in ctx.Main.Customers do
        //where(...)
        select customer
    } |> Seq.toArray

someQuery |> Array.map(fun c -> c.ColumnValues |> Map.ofSeq)
```
### Expected result
The columns listed as they are defined in the `Customers` table: in case one needs to sort them, no problem adding an `Array.sortBy`, but I don't see how I can retrieve the original sequence otherwise.

Thank you.

**Comment by giuliohome** [comment]
Btw, notice also that it would be awesome if the values in `ColumnValues` where a _union type_ instead of an `obj`. Is there anything preventing from it being considered/done? Because the `obj` might produce some issues in the following `RPC` serialization, see @Tarmil comment on [W# gitter](https://gitter.im/intellifactory/websharper?at=5d95adfdfcf7602cc5227165).

**Comment by Thorium** [comment]
Hmm, I don't know straight away the column order, then again, relational database shouldn't trust to any particular column or row order in general, if not explicitely sorted.

obj...nice idea, but breaking backward compatibility and we would have to know all the supported meta-types by different databases.

**Comment by giuliohome** [comment]
Just to clarify, of course I trust - e.g. for MS SQL - the `column_id` of the `sys.columns` table. 
And you also trust such table since you are reading the column descriptions from it in the [Providers.MsSqlServer.fs](https://github.com/fsprojects/SQLProvider/blob/master/src/SQLProvider/Providers.MsSqlServer.fs#L484): I guess you should simply sort by `column_id` in a similar query there, in the point where you get the list of the columns from a table...

**Comment by giuliohome** [comment]
The `type Column` in the `SqlSchema.fs` should have an `ordinal: int` to keep track of the `ORDINAL_POSITION`.
Maybe it can be tagged as a nice to have and closed for now.
