### ISSUE TITLE
Switch to `Microsoft.Data.SqlClient`

### ISSUE THREAD

**Issue by daniellittledev** [fsprojects/SQLProvider#670]
### Description

As `Microsoft.Data.SqlClient` is [due to supersede/replace](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/) `System.Data.SqlClient` SQLProvider should consider switching to `Microsoft.Data.SqlClient`.

**Comment by daniellittledev** [comment]
Related https://github.com/fsprojects/SQLProvider/issues/645#issuecomment-589509133

**Comment by Thorium** [comment]
Done. There is now possibility to use whatever-version of Microsoft SQL driver by copying that to resolution path folder, giving that as a static parameter to SQLProvider, and using `DatabaseProviderTypes.MSSQLSERVER_DYNAMIC` instead of the classic `DatabaseProviderTypes.MSSQLSERVER`
