### ISSUE TITLE
Compilation issue with .net core 3.1

### ISSUE THREAD

**Issue by vparadis** [fsprojects/SQLProvider#688]
**Describe the bug**
When trying to get the type of the DB using `type Db = SqlDataProvider<...>`, VS throws

`Error	FS3033	The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`.

I've been looking around for a fix to this issue and despite trying all the solutions I found (mostly adding references or dlls to the resPath), I can't get it to work. Tried following the tutorial [here](https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Core.Tests/Postgres) as well, but I get the exact same error.

There seem to be a mismatch between the dlls referenced by the package and the ones that were downloaded with it. See screenshot below.

**To Reproduce**
This [tutorial](https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Core.Tests/Postgres) does it for me.

**Expected behavior**
Compiles without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/35237470/90945629-0003dd00-e3f4-11ea-8f85-7a119f58b899.png)

![image](https://user-images.githubusercontent.com/35237470/90945640-0e51f900-e3f4-11ea-8626-14d5542931f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual studio 2019 (also doesn't work in CLI or VS Code)

**Additional Info**
I use a folder called `/lib` for the additional dlls (resPath), in which I have `Npgsql.dll`, `System.Data.Common.dll`, `System.Runtime.CompilerServices.Unsafe.dll` and `System.Threading.Tasks.Extensions.dll`.

**Comment by Shmew** [comment]
I haven't had any issues targeting .NET Core 3.1. Looking at my project dependencies I do see some differences:

![image](https://user-images.githubusercontent.com/11186595/92149945-5275ce00-ede4-11ea-8360-219ad57052b9.png)

In development I targeted a localdb mssql instance, and it targets mssql in production.

Don't know if any of that is helpful, but hopefully it is!

**Comment by Thorium** [comment]
There has been some issues with System.Data.SqlClient on .Net Core 3.1, so there is the dynamic version: https://github.com/fsprojects/SQLProvider/issues/645#issuecomment-639163535

**Comment by Thorium** [comment]
Should be fixed already
