### ISSUE TITLE
fsx works in vs2019 but not in vscode

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/SQLProvider#705]
**Describe the bug**
A simple .fsx file that tries to use SQLProvider works in vs2019 but fails in vscode.

**To Reproduce**
Test.fsx:
```
#r "nuget: SQLProvider" 

open FSharp.Data.Sql

[<Literal>]
let connStr = @"Server=localhost\SQLEXPRESS;Database=AdventureWorksLT2019;Trusted_Connection=True;"

type DB = SqlDataProvider<
                        Common.DatabaseProviderTypes.MSSQLSERVER
                        ,ConnectionString = connStr
                     >
```

**Expected behavior**
It works in vs2019, but fails in vscode/ionide with:
"Could not load type 'System.Data.SqlClient.SqlCommand' from assembly 'System.Data.SqlClient, Version=4.6.1.0, ..."

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SQLProvider v1.1.98
 - dotnet --version 5.0.101

**Additional context**
If this is a duplicate I can close it, but I thought that the fact that it works in vs2019 might be pertinent information.

**Comment by Thorium** [comment]
I'd expect you run VS fsx with .Net full and code with dotnet? If you have the dll in resolutionPath, it should work on both.

**Comment by JordanMarr** [comment]
I didn't realize that VS2019 was not using dotnet to run the script! 
But that must be the case because it fails if I manually run the script via dotnet command line.
