### ISSUE TITLE
Dacpac location + some testing

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#706]
Ping @JordanMarr 

I'm testing the dacpac system.
Initially I'll setup the dacpac path as follows:
```fsharp
SsdtPath = __SOURCE_DIRECTORY__ + "database/bin/Debug/database.dacpac",
```
...the type provider says `error: SsdtPath must point to a dacpac file`. Which I thought it does, but obviously something is wrong, so it would be nice to display the path it tries when fails.

The second try, absolute path, this is not as nice, as this won't work in both Mac and Windows:

```fsharp
SsdtPath = @"C:\git\MyProject\database\bin\Debug\database.dacpac",
```

Now the intellisense works great. However when I build my (multi-project) solution, it fails:

```
1>C:\git\MyProject\Program.fs(23,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to find .dacpac file at: 'C:\git\MyProject\packages\SQLProvider\lib\net451\database.dacpac'
```

Why is it trying to load it from that path?

---

_Edit:_
I copied my dacpac file under my packages path so that the build will find it.
Then I had to restart my VS just that the tables are found in other source files also.

The few things I note not to work:
- View column with `select col1 + col2 as Sum` has type `obj` when it should be `Option<decimal>`
- View column with `select case when 1=0 then datecol1 else datecol2 end as mydate` has type `obj` when it should be `Option<DateTime>`
- Computed columns are not found
- Invoking a stored procedure seems to return `Unit` when it should return `SprocResult` having a ResultSet of `SqlEntity[]`

Other than that looks very good!

**Comment by JordanMarr** [comment]
> ```fsharp
> SsdtPath = _SOURCE_DIRECTORY_ + "database/bin/Debug/database.dacpac",
> ```
> 
> ...the type provider says `error: SsdtPath must point to a dacpac file`. Which I thought it does, but obviously something is wrong, so it would be nice to display the path it tries when fails.
> 

It definitely needs a forward slash directly after __SOURCE_DIRECTORY__:
`__SOURCE_DIRECTORY__ + "/database/bin/Debug/database.dacpac"`

The only way it throws the "SsdtPath must point to a dacpac file" is if `SsdtPath.EndsWith(".dacpac")` fails, which is odd because yours does.  
Line 64 in SqlDesignTime.fs: `elif not (ssdtPath.EndsWith(".dacpac")) then failwith "SsdtPath must point to a .dacpac file."`

I'll mess around with it.  

> The second try, absolute path, this is not as nice, as this won't work in both Mac and Windows:
> 
> ```fsharp
> SsdtPath = @"C:\git\MyProject\database\bin\Debug\database.dacpac",
> ```
> 
> Now the intellisense works great. However when I build my (multi-project) solution, it fails:
> 
> ```
> 1>C:\git\MyProject\Program.fs(23,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to find .dacpac file at: 'C:\git\MyProject\packages\SQLProvider\lib\net451\database.dacpac'
> ```
> 
> Why is it trying to load it from that path?

I am able to reproduce where it falsely reports the source path as being in the `.nuget/packages/sqlprovider` path. I think I can fix this.

> 
> _Edit:_
> I copied my dacpac file under my packages path so that the build will find it.
> Then I had to restart my VS just that the tables are found in other source files also.
> 
> The few things I note not to work:
> 
> * View column with `select col1 + col2 as Sum` has type `obj` when it should be `Option<decimal>`
> * View column with `select case when 1=0 then datecol1 else datecol2 end as mydate` has type `obj` when it should be `Option<DateTime>`
> * Computed columns are not found

The .dacpac AST doesn't provide reference column info for some view columns - mostly computed and expressions. 
I set those to `obj` so that the user could at least manually cast them. This was supposed to be in the docs "known issues", but I think I inadvertently deleted it. 
This area definitely needs some more love. It might be possible to do some more investigative parsing to determine the type.
If not, maybe another creative workaround may be needed, like adding some sort of data type override to the options.  

> * Invoking a stored procedure seems to return `Unit` when it should return `SprocResult` having a ResultSet of `SqlEntity[]`

That definitely sounds like a bug!

> Other than that looks very good!

Glad it is mostly working. 😁

**Comment by JordanMarr** [comment]
I'm still investigating some options on how to resolve some of the missing view column (obj) types. But if I hit a dead-end, I'm thinking that it might be nice to allow users to decorate types (when needed) in their view definitions via comment. 
For example, take two view columns that are defined with via subquery that are difficult or impossible to trace back to a reference table column:

```
        (SELECT SUM(Hours) FROM Actual a WHERE a.TaskId = t.Id) as ActualHours /* int */,
        (SELECT SUM(Hours) FROM Planned p WHERE p.TaskId = t.Id) as PlannedHours /* int */,
```

Decorating it with an inline comment specifying the sql data type would be a fairly painless workaround.
Of course it would be totally optional. The other option being to simply cast it manually in code.

**Comment by Thorium** [comment]
I'd like to have it easy way to migrate between the MsSQL and MsSQL.Ssdt, so that the same code compiles on both. Annotation seems reasonable if no better options found.

**Comment by JordanMarr** [comment]
> * Invoking a stored procedure seems to return `Unit` when it should return `SprocResult` having a ResultSet of `SqlEntity[]`

I'm not currently using the stored procedure feature in my project, so can you provide me with a sample sproc that I can use to fix this bug?

**Comment by Thorium** [comment]
Input parameters would appear like this, which is parsed:
```xml
<Relationship Name="Parameters">
	<Entry>
		<Element ...
```

But if you do just a basic stored procedure having selects, shortest here:

```sql
CREATE PROCEDURE [dbo].[GET_EMPLOYEES]
AS   
BEGIN   
   --THROW 50001, 'EARRRR', 1
  SELECT * FROM employees;   
END
```

it will look like this, and not have the output-parameters:

```xml
		<Element Type="SqlProcedure" Name="[dbo].[GET_EMPLOYEES]">
			<Property Name="BodyScript">
				<Value QuotedIdentifiers="True" AnsiNulls="True"><![CDATA[   
BEGIN   
   --THROW 50001, 'EARRRR', 1
  SELECT * FROM employees;   
END]]></Value>
			</Property>
			<Property Name="IsAnsiNullsOn" Value="True" />
			<Relationship Name="BodyDependencies">
				<Entry>
					<References Name="[dbo].[EMPLOYEES]" />
				</Entry>
			</Relationship>
			<Relationship Name="Schema">
				<Entry>
					<References ExternalSource="BuiltIns" Name="[dbo]" />
				</Entry>
			</Relationship>
			<Annotation Type="SysCommentsObjectAnnotation">
				<Property Name="CreateOffset" Value="153" />
				<Property Name="Length" Value="273" />
				<Property Name="StartLine" Value="1" />
				<Property Name="StartColumn" Value="1" />
				<Property Name="HeaderContents" Value="--------------------------------------------------------&#xD;&#xA;--  DDL for Procedure GET_EMPLOYEES&#xD;&#xA;--------------------------------------------------------&#xD;&#xA;CREATE PROCEDURE [dbo].[GET_EMPLOYEES]&#xD;&#xA;AS" />
			</Annotation>
		</Element>
```

...so the provider thinks it returns `Unit`, even though in real life it returns meaningful stuff.

**Comment by Thorium** [comment]
I think the provider could always return a `SprocResult` having a ResultSet property of `SqlEntity[]` instead of `Unit`. The ResultSet can be empty, but that way e.g. this would compile:

```fsharp
let r = ctx.Procedures.MySproc.Invoke()
let returnedData = r.ResultSet |> Array.map(fun i -> i.ColumnValues |> Map.ofSeq)
```

And even if the real procedure wouldn't return anything, the you could still call it, just ignore the result.

**Comment by Thorium** [comment]
With SQLProvider the table and column descriptions are showed in Visual Studio (or other IDE) as tooltips.

Currently SSDT provider doesn't use them as it stores only `SsdtColumn.Description = "Simple Column"`.
They could be supported as in the dacpac they are stored, as follows:

```xml
<Element Type="SqlExtendedProperty" Name="[SqlTableBase].[dbo].[mytable].[MS_Description]">
    <Property Name="Value">
        <Value><![CDATA[N'Mytable is the most important table you should know of.']]></Value>
    </Property>
    <Relationship Name="Host">
        <Entry>
            <References Name="[dbo].[mytable]" />
        </Entry>
    </Relationship>
</Element>

<Element Type="SqlExtendedProperty" Name="[SqlColumn].[dbo].[mytable].[MyColumn].[MS_Description]">
    <Property Name="Value">
        <Value><![CDATA[N'My column is used for storing phone number']]></Value>
    </Property>
    <Relationship Name="Host">
        <Entry>
            <References Name="[dbo].[myTable].[MyColumn]" />
        </Entry>
    </Relationship>
</Element>
```

**Comment by Thorium** [comment]
Should the view type annotations override the computed annotations?

I have this kind of view:
```sql
CREATE view [dbo].[myView] as
  select 
     p.Id as [PersonId] /* uniqueidentifier not null */, 
     c.Id as [CarId]    /* uniqueidentifier null */, -- ...due to left join
  from dbo.Person p	
  left join dbo.Car c on (p.Id = c.PersonId)
GO
```

Now, SSDT provider picks the `CarId` being `uniqueidentifier not null`.
Which is the correct data type in Car-table.

However, as the left-join can produce no-hits included, the CarId of this view can actually be null.

When I query the running SQL-server INFORMATION_SCHEMA.COLUMNS, the view CarId-field is nullable.

**Comment by JordanMarr** [comment]
> Should the view type annotations override the computed types?

Currently it only checks for an annotation if a table column can't be referenced. 
But after looking at your example, I think that it should always check for an annotation first and use it if found.

**Comment by Thorium** [comment]
After the latest changes (NuGet 1.0.101) I'm actually able to build quite complex project aginst SSDT dacpac.

**Comment by Thorium** [comment]
Everything seems to be working ok, I'll close this one.
