### ISSUE TITLE
Roadmap to net5.0?

### ISSUE THREAD

**Issue by halcwb** [fsprojects/SQLProvider#710]
**Is your feature request related to a problem? Please describe.**
Is there a road map to completely switch to net5.0 and get red of all the old dependencies, like System.Data.SqlClient, etc...?

**Describe the solution you'd like**
It would help if this project completely switched to net5.0, this would make running on different systems much easier.

**Comment by Thorium** [comment]
This should be already compatible/usable in .NET 5.0 projects, is it not...?
Also, there is a [.NET Standard](https://github.com/fsprojects/SQLProvider/tree/net-standard) branch which is building the system with the new project file layouts, however the current Nuget packages are still released from the master branch.

**Comment by halcwb** [comment]
@Thorium That's great. I was confusing SQLProvider with FSharp.Data.TypeProviders. Leaving me a bit puzzled, should I switch to SQLProvider? It seems that FSharp.Data.TypeProviders will be deprecated?

**Comment by Thorium** [comment]
I don't know it's status, and I'm not saying a tool is better than some other tool, as every tool has their advantages and disadvantages. For a platform it's a richness to have multiple tools to select from. For me SQLProvider has worked very well.

Some activity stats to consider, in GitHub:
FSharp.Data.TypeProviders has 34 stars and 9 contributors
SQLProvider has 404 stars and 69 contributors. 

[Here](https://fsprojects.github.io/FSharp.Data.SqlClient/comparison.html) is a comparison page of type providers. It's hosted by one of them, so maybe not totally objective, but at least it gives you some point of views.

**Comment by halcwb** [comment]
OK, they are effectively different libraries. Thanks for the info.
