### ISSUE TITLE
Commit history appears squashed on GitHub

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/SQLProvider#716]
**Describe the bug**
It’s looks like the commit history that is displayed on GitHub was inadvertently squashed when the net-standard branch was merged. Every file within the src folder shows “1 contributor”, and the history button only shows a few recent merge commits. 

interestingly, when I view file history on my local machine, it still shows the full history. 

Is it a bug with GitHub?

**To Reproduce**
 View a src file in the GitHub browser and hit the History icon button;
 then view the same file’s history locally with git. 

**Expected behavior**
Should show the full history and contributors on GitHub.

**Comment by Thorium** [comment]
As far as I remember all the files where location is changed are moved via `git mv` so they should be correct.

**Comment by Thorium** [comment]
I think this is a "feature" of GitHub.
E.g. Blame is working still:
https://github.com/fsprojects/SQLProvider/blame/master/src/SQLProvider.Runtime/Providers.MsSqlServer.fs
