### ISSUE TITLE
ConnectionStringName Parameter Not Finding Value in App.confg

### ISSUE THREAD

**Issue by raquila** [fsprojects/SQLProvider#722]
**Describe the bug**
I just upgrade from version 1.1.5.0 to 1.2.1 and the same code that was working is now throwing an error that the connection string was not found.

Error	FS3033	The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not find a connection string with name 'APPDB'

If I revert back, the error goes away.

**To Reproduce**
Upgrade from version 1.1.5.0 to 1.2.1, this line of code now throws error.
SqlDataProvider<Common.DatabaseProviderTypes.MSSQLSERVER,ConnectionStringName="APPDB",UseOptionTypes=true>
App.config contains a connection string called APPDB

**Expected behavior**
No errors

**Additional context**
.Net 4.8
fsharp.core 4.7.2

**Comment by Thorium** [comment]
I expect any 1.1.x is working and 1.2 needs a proper connection string... Is there such thing as App.config in .Net Standard?

**Comment by JordanMarr** [comment]
You would typically use an appSettings.json file in .NET core.
https://blog.hildenco.com/2020/05/configuration-in-net-core-console.html
