### ISSUE TITLE
Cannot use IQueryable Count in where clause

### ISSUE THREAD

**Issue by halcwb** [fsprojects/SQLProvider#727]
**Is your feature request related to a problem? Please describe.**
I am trying to convert an FSharp.Data.TypeProviders project to SQLProvider, as the former is no longer maintained. 

**Describe the solution you'd like**
With the former TypeProviders, the following code could be used:

```fsharp
open System.Linq

let test _ =
    let ctx = DataContext.getDataContextWithLog()
    let list : string list = []
    let list = list.AsQueryable()

    query {
        for p in ctx.Dbo.Parameters do
        where (list.Count() > 0)
        select p.ParameterId
    }
```

However with SQLProvider I get:

> Unsupported expression. Ensure all server-side objects won't have any .NET-operators/methods that can't be converted to SQL. The In and Not In operators only support the inline
> array syntax. ([].Count() > 0)
> 

**Describe alternatives you've considered**
Not yet considered an alternative.

**Comment by Thorium** [comment]
I'd recommend doing a temp-variable before `query`:
```fsharp
let anyItems = list.Count() > 0
```

**Comment by Thorium** [comment]
What is the SQL-clause you expect your initial code should generate?

**Comment by halcwb** [comment]
@Thorium. Thinks for the quick reply. Your workaround could absolutely work but would generate some boilerplate code for my use case, which looks like:

```fsharp
  <@ fun _ ->
      query {
          for s in ctx.Dbo.FreeTextSignals do
          join p in ctx.Dbo.Parameters // ((%getPar) ())
              on (s.ParameterId = p.ParameterId)
          join h in ctx.Dbo.Patients
              on (s.PatientId = h.PatientId)
          where ((patsqry.Count() = 0 ) && ((%signPred) s) && ((%parPred') p))
          select (h.HospitalNumber, s, p.ParameterName, p.Abbreviation) } @>
```

This is code I am porting from FSharp.Data.TypeProviders. I have multiple queries like these with complicated predicates. 

Note: I also had to remove the join over a quotations expression, I moved that to the where clause.

**Comment by Thorium** [comment]
How do we know what `patsqry` Count() should look like as SQL, and do you want to execute it in the SQL or in the .NET-business logic? Is FSharp.Data.TypeProviders dumping this into a single SQL-clause? Why would you like to do "Count() = 0" which is counting items in the database, let's say 10000, when all you need is .Any(), wouldn't that be inefficient SQL?

I'm just saying this SQL would be more efficient and probably hit your database indexes better, even though executed as 2 separate clauses, because we can short-circuit the full sub-query away if non hit:

```fsharp
  <@ fun _ ->
      let noPatqry = (patsqry |> Seq.tryHead).IsNone
      query {
          for s in ctx.Dbo.FreeTextSignals do
          join p in ctx.Dbo.Parameters // ((%getPar) ())
              on (s.ParameterId = p.ParameterId)
          join h in ctx.Dbo.Patients
              on (s.PatientId = h.PatientId)
          where (noPatqry || patsqry.Contains(h.HospitalNumber.Value)) && ((%signPred) s) && ((%parPred') p))
          select (h.HospitalNumber, s, p.ParameterName, p.Abbreviation) } @>
```

**Comment by halcwb** [comment]
@Thorium Agreed. Thanks for examplaining.
