### ISSUE TITLE
Making illegal states un-representable at compile time

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#736]
Typically when I write F# programs, when they compile they often work.
With Farmer, we are still quite far.

Currently Farmer gathers each builder states and then does its validation at runtime:
[`failwith $"You must specify a username for virtual machine {this.Name.Value}"`](https://github.com/CompositionalIT/farmer/blob/bbc7600ad4039584506b7f4c0152ca59b83213e1/src/Farmer/Builders/Builders.Vm.fs#L72)

Could we go to the direction where the compiler would notice the most clear validation issues?
We still want to keep the current specification freedom and backward compatibility as much as possible.

![illegalstates](https://user-images.githubusercontent.com/229355/125278263-65153980-e30a-11eb-800f-787fa043596a.png)

I think this could be done by splitting the current mega-state of each builder.
Then doing the custom_operators as strongly-typed for only the states that they are allowed.
And if the "final valid state" is not achieved then the compiler will not type-check.

Example:
https://github.com/Thorium/farmer/commit/2881d8b48b13dc394a19870f2b894724622c92db

So in this small code-sample, I have changed the VM-builder as:
- ".Yield" returns type of VmInitialConfig, not a VmConfig.
- "name"-operators are valid for VmInitialConfig and "VmConfig".
- "username" takes an VmInitialConfig and returns VmConfig.

Quite minimal code-change, and now it validates at compile-time, like in the picture.

This is not PR, this is a question of design-decisions, to what direction should Farmer go, to make things more simple for the end-user. For example, things to consider:
- If you have more complex validation rules, how to avoid the explosion of state transformation method count?
- It seems you can't have multiple CustomOperation-attributes in a class for the same name/operation, the overloads have to be listed below each other. That makes the current interface-implementation inherited custom-operators hard.

**Comment by TheJayMann** [comment]
Did you happen to post this in the wrong repository?  I'm failing to understand what Farmer configuration has to do with SQLProvider.

**Comment by Thorium** [comment]
Yes :D
