### ISSUE TITLE
Created entry not available unless I restart the application?

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/SQLProvider#737]
### Description

I’m using SQLProvider to communicate with an MSSQL Server in an application written in F#. I do have a problem, though. 

When I run the application I can use the DataContext to add new entries to the Database and submit them. This works and I can see the entries in the SQL server. However, if I then use the same F# application to browse the entries in the database, I do not find them in the DataContext, unless I restart the application. 

There must be some way to update the DataContext to see all entries without restarting the application, but I haven’t been able to figure out how this is done. Any tips?

### Repro steps

1. Open a connection to an SQL Server with the SQLProvider 
2. Get the DataContext
3. Create new entries in one or more tables in the database (by calling `let row = ctx.Dbo.TableName.Create()` and adding entries to each column by calling `row.columnName <- "value"`).
4. Submit updates by calling `ctx.SubmitUpdates()`
5. Query the database with a query command and I cannot see the added entry (outside the F# application I can see them in the SQL server, so they are there)
6. Restart the application and the new entry is there.

### Expected behaviour

I'd expect the updates to be available in the DataContext when they are submitted.

### Actual behaviour

I cannot find them until I restart the program

### Related information 
* Operating system
    - [x] windows
    - [x] macOs
    - [ ] linux [insert flavor/version here]
* Platform
    - [x] dotnet core
    - [ ] dotnet full
    - [ ] mono
* Branch or release version: SQLProvider 1.2.5
* Database versions and sample databases being used: MSSQL Server 2019 (latest?)

**Comment by Thorium** [comment]
That sounds weird.
1) how about if you create them with a long `.``Create(col1, ...)``("test")` ?
2) could this be that your transactions block the visibility somehow?

**Comment by Thorium** [comment]
You can monitor the query creation like this: http://fsprojects.github.io/SQLProvider/core/querying.html

**Comment by JordanMarr** [comment]
> That sounds weird.
> 
> 1. how about if you create them with a long `` .``Create(col1, ...)``("test") `` ?
> 2. could this be that your transactions block the visibility somehow?

It does sound like a connection or a transaction is not being closed or disposed.

**Comment by arnesahlberg** [comment]
Thank you for your comments. 

I've figured out the problem. It turns out it wasn't an SQLProvider issue, but an issue with the application content not being reloaded as it should.

Closing issue.
