### ISSUE TITLE
Access statically typed row from C#

### ISSUE THREAD

**Issue by easysoft2k15** [fsprojects/SQLProvider#740]
I have a function in F# that is selecting a row from a SQL table.
If I use that function from F#  the row is statically type and I can access all columns via the dot notation.
Is it possible calling the same function from C# to achieve the same result?
Right now the only way I was able to access the data from C# was using the ColumnValues property.
Thank You

**Comment by Thorium** [comment]
No, sorry, this is F# erasing type-provider, the F# compiler will compile the database types away.

I guess the LINQ expression trees could be transferable.

**Comment by easysoft2k15** [comment]
OK. Thank You anyway
