### ISSUE TITLE
Unable to use SQLProvider for Access with .net 5.0

### ISSUE THREAD

**Issue by prateek-khandelwal** [fsprojects/SQLProvider#747]
**Describe the bug**
I am trying to use SQLProvider for accessing an MS Access DB on windows platform.
The project targets .net 5.0, and the latest release for SQLProvider from nuget. 

During compilation, I face build error complaining that `System.Data.OleDb` is not supported for the current platform.
From the target matrix available [here](http://fsprojects.github.io/SQLProvider/core/netstandard.html), I get a sense that `.net 4.5.1` should support Access DB ( and since the version mentioned on the page is 1.1.18, I would assume that the latest version of SQLProvider should also support it ) 

Can someone please clarify if I am doing anything wrong here ? 
PS: I had to create a bug cause I couldn't figure out any other channel for seeking help on this

**Comment by Thorium** [comment]
If you are doing .NET 4.5.1 then the System.Data.OldeDb.dll should be part of the .NET Framework library and not a separate NuGet-package, right?

**Comment by prateek-khandelwal** [comment]
I am using .net 5 however.
I apologise if my answers sound vague, i am not that familiar with dotnet world, I just want to use mu OCaml experience to access an access db i have

**Comment by TheJayMann** [comment]
.NET Framework 4.5.1 uses a completely different framework and runtime than .NET 5.  The latter is really a continuation from .NET Core 3.1.  For someone not familiar with the dotnet ecosystem, a general rule of thumb is anything that requires .NET 4.x actually requires .NET Framework, and might not work on .NET 5+ unless otherwise stated.

**Comment by prateek-khandelwal** [comment]
Aha, I think I understand it now. I was under the impression that `.Net 5` is `.Net Framework 5`. Thanks a lot for the clarification !

I'll close this issue for now and experiment a bit more, Thanks !
