### ISSUE TITLE
Support table names with spaces

### ISSUE THREAD

**Issue by aciq** [fsprojects/SQLProvider#759]
Some applications have table names with spaces  
using MSSQLSERVER provider

![image](https://user-images.githubusercontent.com/36763595/155171292-b5a56d05-89bd-46a0-b215-463716bfbf0f.png)

querying tables without spaces works, all tables with spaces in the name fail

![image](https://user-images.githubusercontent.com/36763595/155171572-02a420f4-be1b-4294-bb71-620496597476.png)

**Comment by nr-4** [comment]
problem seems to be in the quotes surrounding the table

```
SELECT  FROM [dbo].["Application Object Metadata"] as [x] WHERE (([x].[Object ID] > @param1)) -- params @param1 - 50000;
```

**Comment by nr-4** [comment]
turns out the first identifier allows quotes but the one after FROM does not, 

generated sql:
```
SELECT ["Application Object Metadata"].[Object ID] as 'Object ID' FROM [dbo].["Application Object Metadata"] as ["Application Object Metadata"]  -- params
```

tested correct sql
```
SELECT ["Application Object Metadata"].[Object ID] as 'Object ID' FROM [dbo].[Application Object Metadata] as ["Application Object Metadata"]  -- params
```

where is this FROM expression in code?
