### ISSUE TITLE
Usage does not align with docs or this is just broken.

### ISSUE THREAD

**Issue by P-Louw** [fsprojects/SQLProvider#768]
I have been avoiding database work with F# because it never worked. What I mean by this is the libraries are just non existent when following the official docs.

I visit the type provider site and follow the link to nuget.
After adding it I try to follow the instructions.
- Open namespace FSharp.Data.<provider name>
This is where it breaks. All that is present in this namespace is 'UnitSystems'.

If these steps are incorrect the docs need to reflect that or just remove the package.
I have revisited data access over the past 2 years and nothing has changed. 

Using dapper and just raw queries seems to be the only solution but falling back to C#
just seems a better workflow honestly. It's a shame since F# boasts about happy coding and data manipulation but this seems far from the truth. 

I like F# and use it a lot but just can't advise using it since the database related tasks seems totally broken.

**Comment by P-Louw** [comment]
Not interested in using this library or F# for anything serious any more.

**Comment by P-Louw** [comment]
Decided to close this since it doesn't seem exclusive to this library also decided to drop F# the whole paket and support issues is just too time consuming.

**Comment by JordanMarr** [comment]
Most devs don’t really need the advanced features that paket offers, although it can be useful for library developers. 
You don’t have to use it. (I don’t.)
