### ISSUE TITLE
Is it possible to pull down a partial row and then update it?

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/SQLProvider#804]
Hi @Thorium,

This is more of a question than a bug.

I have a table with a large json column.  
I want to pull that record and make some updates to the other columns, but I don't want to pull down the json column because it's really big and I don't need to touch it. The problem is that if I `select` a subset of columns into a projection, then I can no longer update the columns.
Is there a way to do this, or maybe a workaround?

**Comment by Thorium** [comment]
A little bit hack, but yes: https://github.com/fsprojects/SQLProvider/issues/561#issuecomment-404956768
