### ISSUE TITLE
Error in simple SQLProvider project. 'dataContext' does not define the field Main.

### ISSUE THREAD

**Issue by shin0kaze** [fsprojects/SQLProvider#820]
**Describe the bug**
When I run simple project from documentation I got following error:
`Error FS0039 : The type 'dataContext' does not define the field, constructor or member 'Main'.`

**To Reproduce**
Just launch this project.

**Expected behavior**
No errors, on such simple project

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
My project that contains this error https://github.com/shin0kaze/sqlError

I'm actually don't know if it's bug, or I doing something wrong. I'm new to f#.

**Comment by Thorium** [comment]
You are missing `Microsoft.Data.Sqlite.dll` from your files path.
Copy the netstandard2.0 version of it to there.
You can get it e.g. from C:\Users\(yourname)\.nuget\packages\microsoft.data.sqlite.core\8.0.4\lib\netstandard2.0

**Comment by shin0kaze** [comment]
Thanks for the suggestion. I added a new lib, and copied the existing ones again from netstandart2.0 as well for compatibility (pushed to the repo). But that didn't help. Maybe something is wrong with these dlls?

**Comment by Thorium** [comment]
Hmm, I took your original report, just added Microsoft.Data.Sqlite.dll to your files and it worked  (VS2022).

**Comment by shin0kaze** [comment]
Switched to the previous commit and added the new lib. But still error persist. Then updated and repaired VS 2022, also didn't helped. Tried Rider - same result. I don't know, maybe I should reinstall the entire.net?

Tomorrow, I will also try to run it on another PC.

**Comment by Thorium** [comment]
Silly question but did you have the database file also in place?

**Comment by shin0kaze** [comment]
Oh, there was an empty file test.db)) I thought it would create the database in ReadWriteCreate mode if none existed. Thanks for helping!
