### ISSUE TITLE
Code can run for `SQLite`, but displays an error in the editor

### ISSUE THREAD

**Issue by phasetr** [fsprojects/SQLProvider#826]
**Describe the bug**
The code executes correctly,
but, on vscode or Rider, `SqlDataProvider` shows an error message.

The following message is displayed in the editor.

On `vscode`:

>The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Cannot create connection, db driver raised exception: Could not load file or assembly 'SQLitePCLRaw.core, Version=2.1.6.2060, Culture=neutral, PublicKeyToken=1488e028ca7ab535'. The system cannot find the file specified.

On `Rider`:

>The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not load type 'SQLitePCL.strdelegate_collation' from assembly 'SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535'.

**To Reproduce**

Open the following code in editors.

```fsharp
#r "nuget: SQLProvider"
#r "nuget: Microsoft.Data.Sqlite"
open FSharp.Data.Sql

// copy dll
let home = System.Environment.GetEnvironmentVariable("HOME")
System.IO.File.Copy($"{home}/.nuget/packages/microsoft.data.sqlite.core/8.0.7/lib/net8.0/Microsoft.Data.Sqlite.dll", "Microsoft.Data.Sqlite.dll", true)
let [<Literal>] sqliteConnStr = "Data Source=grate-sqlite.db"
let [<Literal>] sqliteResPath = __SOURCE_DIRECTORY__ + "/"
type sqlite = SqlDataProvider<
  DatabaseVendor = Common.DatabaseProviderTypes.SQLITE,
  SQLiteLibrary = Common.SQLiteLibrary.MicrosoftDataSqlite,
  ConnectionString = sqliteConnStr,
  ResolutionPath = sqliteResPath,
  IndividualsAmount = 1000,
  UseOptionTypes = FSharp.Data.Sql.Common.NullableColumnType.OPTION>

let sqliteCtx = sqlite.GetDataContext()

query {
    for user in sqliteCtx.Main.Users do
    select (user.Id, user.Name)
}
|> Seq.toList
|> printfn "%A"
```

**Expected behavior**
I want to ensure that no errors appear in the editor.
(There are no errors with PostgreSQL and MariaDB codes.)

**Screenshots**
<img width="1139" alt="スクリーンショット 2024-08-03 14 51 04" src="https://github.com/user-attachments/assets/d1bc2efd-1788-4616-8c49-bf6159b8183b">

**Desktop (please complete the following information):**
 - OS: Apple M1 Pro, Sonoma 14.5
 - .NET: 8.0.204
 - VSCode: 1.92.0
 - Rider: JetBrains Rider 2024.1.4

**Additional context**

**Comment by Thorium** [comment]
The editor needs SQLitePCLRaw.core.dll to ResolutionPath folder to get the schema from the database at compile time.

**Comment by phasetr** [comment]
Thank you for your comment, I added the dll.
But, in the editor (vscode), I get a message `The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().`
<img width="988" alt="スクリーンショット 2024-08-03 17 06 41" src="https://github.com/user-attachments/assets/1416460b-e5f0-4e9f-bcf7-09e3b1397030">

Furthermore, after adding the dll, I cannot run the code. When running `SqlDataProvider`, I got the follwoing error:

>/Users/phasetr/dev/CSharp/ASP.NET-Core/FSharpDbComparison/sqlprovider-sqlite.fsx(10,15): error FS3033: 型プロバイダー 'FSharp.Data.Sql.SqlTypeProvider' がエラーを報告しました: Cannot create connection, db driver raised exception: Method 'sqlite3_malloc' in type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=2.1.6.2060, Culture=neutral, PublicKeyToken=9c301db686d0bd12' does not have an implementation.

Then I added `SQLitePCL.SQLite3Provider_e_sqlite3.dll` from `~/.nuget/packages/sqlitepclraw.provider.e_sqlite3/2.1.8/lib/netstandard2.0`. This time I got the following error.

>/Users/phasetr/dev/CSharp/ASP.NET-Core/FSharpDbComparison/sqlprovider-sqlite.fsx(10,15): error FS3033: 型プロバイダー 'FSharp.Data.Sql.SqlTypeProvider' がエラーを報告しました: Cannot create connection, db driver raised exception: Method 'sqlite3_malloc' in type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=2.1.6.2060, Culture=neutral, PublicKeyToken=9c301db686d0bd12' does not have an implementation.

Did I face some version problems for dlls?

**Comment by Thorium** [comment]
Sometimes a nuget package has multiple versions of a dll, did you add the correct one?

**Comment by phasetr** [comment]
Do you know proper versions, and how to get them? If it's not immediately clear, I'll consider giving up on verifying with SQLite for now since it doesn't have a significant impact.

**Comment by Thorium** [comment]
I've seen people having possibly the same issue e.g. https://github.com/fsprojects/SQLProvider/issues/684 and https://github.com/fsprojects/SQLProvider/issues/818 however I've not had that issue. SQLite drivers are not having very clear NuGet dependency hierarchy and there are some hacks in the drivers to pick the correct dlls.

It can be get to work but I don't have my Mac near to show exactly correct versions. The issue is that you may need to restart your IDE when you try other combination. The resolution path can have multiple paths separated with semicolon if that helps.

**Comment by phasetr** [comment]
Thank you for your great help! I've decided to give up on adjustments this time. I appreciate you quick feedback and responses, and I'll close the issue.
