### ISSUE TITLE
When using context schema path the generated schema file is not correct

### ISSUE THREAD

**Issue by halcwb** [fsprojects/SQLProvider#835]
**Describe the bug**
When trying to use the `ContextSchemaPath` the build will fails with: The type 'dbo.UsersEntity' does not define the field, constructor or member 'UserId'. In fact, this happens for all generated types.

First I didn't use the context schema path. When trying to use this feature, the schema files are generated but they do not contain any column names and seem only to list tables.

As an example of a generated schema file:

{"Columns@":[],"Individuals@":[],"IsOffline@":true,"Packages@":[],"PrimaryKeys@":[],"Relationships@":[],"SprocsParams@":[],"Sprocs@":[],"Tables@":[{"Key":"dbo.FreeTextSignals","Value":{"Name@":"FreeTextSignals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Signals","Value":{"Name@":"Signals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.EventSignals","Value":{"Name@":"EventSignals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.PendingOrders","Value":{"Name@":"PendingOrders","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.OrderEntry","Value":{"Name@":"OrderEntry","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.PendingRangeSignals","Value":{"Name@":"PendingRangeSignals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.ParametersCategories","Value":{"Name@":"ParametersCategories","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.PatientLogs","Value":{"Name@":"PatientLogs","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Patients","Value":{"Name@":"Patients","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Micro_Microbes","Value":{"Name@":"Micro_Microbes","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Integration_MSG_Info","Value":{"Name@":"Integration_MSG_Info","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Units","Value":{"Name@":"Units","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.ORD_StandardTimes","Value":{"Name@":"ORD_StandardTimes","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.t_OrderType","Value":{"Name@":"t_OrderType","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Parameters","Value":{"Name@":"Parameters","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Transfer","Value":{"Name@":"Transfer","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Transport","Value":{"Name@":"Transport","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Users","Value":{"Name@":"Users","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.TextSignals","Value":{"Name@":"TextSignals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.ParametersText","Value":{"Name@":"ParametersText","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Beds","Value":{"Name@":"Beds","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Micro_Specimen","Value":{"Name@":"Micro_Specimen","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.DateTimeSignals","Value":{"Name@":"DateTimeSignals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.LogicalUnits","Value":{"Name@":"LogicalUnits","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Micro_GroupMaterial","Value":{"Name@":"Micro_GroupMaterial","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Micro_Result","Value":{"Name@":"Micro_Result","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Orders_MedicationActiveComponents","Value":{"Name@":"Orders_MedicationActiveComponents","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.RangeSignals","Value":{"Name@":"RangeSignals","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.PatientOwnerships","Value":{"Name@":"PatientOwnerships","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.DripUnits","Value":{"Name@":"DripUnits","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Micro_Material","Value":{"Name@":"Micro_Material","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Orders_Routes","Value":{"Name@":"Orders_Routes","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.OrderCategories","Value":{"Name@":"OrderCategories","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.Orders_Locations","Value":{"Name@":"Orders_Locations","Schema@":"dbo","Type@":"base table"}},{"Key":"dbo.PlannedOrders","Value":{"Name@":"PlannedOrders","Schema@":"dbo","Type@":"base table"}}]}

This file should be much larger. 

Using MSSQL.

Tried:

- Deleting the generated schema files, cleaning the solution and trying to build fresh. But still the same problems

This works:
- First 
  - Cleaning the solution, deleting all schema files. 
  - Then build the whole solution. 
  - Open up each project file separately. 
  - Wait for the project being completely loaded in VSCode
  - Then just type `ctx.``Design Time Commands``.SaveContextSchema` 
  - Do not save the just typed code

So it seems that you need to first:
1. Successfully build the project
2. Set a path to the ContextSchemaPath
3. Use `ctx.`Design Time Commands``.SaveContextSchema`` ` only to trigger the build of the schema file.

If there is no schema file nothing happens until you type in step 3. 

I completely didn't get this at first. I thought this was done at compile time.

Environment:
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.3068a692
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

**Comment by Thorium** [comment]
It’s lazy, it won’t save all the database, just the columns you use.

**Comment by Thorium** [comment]
Which database you are using?

**Comment by halcwb** [comment]
> It’s lazy, it won’t save all the database, just the columns you use.

Then it is extremely lazy as it doesn't add any columns at all :-)

**Comment by halcwb** [comment]
After making all the mistakes that were made in the past issues. I finally got this working. I will try and create a blog about using SQLProvider, because I think there quite some caveats (at least I ran into).

@Thorium Thanks! (not sarcastically but well meant).

**Comment by Thorium** [comment]
If you use MS SQL Server then I recommend the SSDT (sqlproj/dacpac) version. But if you use something else like Postgres or MySQL then I guess SaveContextSchema is your way to do offline builds.

**Comment by halcwb** [comment]
> If you use MS SQL Server then I recommend the SSDT (sqlproj/dacpac) version. But if you use something else like Postgres or MySQL then I guess SaveContextSchema is your way to do offline builds.

I do use MSSQL. However, I have to query a very large legacy database and only use a limited set of tables. So, the schema file option is a very good match en currently working! So, I am completely happy, thanks.
