### ISSUE TITLE
Everything is in upper case (MSSQL)

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/SQLProvider#94]
I built it from source and it generates everything in upper case now (the version that lays in NuGet generates normal names).

Is it intentional?

**Comment by Thorium** [comment]
+1
Can't wait to get this from NuGet. ;-)

**Comment by colinbull** [comment]
Yeah, sorry!! we keep saying we will get a release out soon. But I have been super busy for what seems like forever, on C# projects.

**Comment by pezipink** [comment]
Sorry, yes, I am terrible as well.  We have some proper docs being written and I am intending to spend some time with this project soon and get it sorted out, it's been a year since the last package (!!)

**Comment by Thorium** [comment]
After #143 you can now do this:

    open FSharp.Data.Sql.Common
    type sql = 
      SqlDataProvider<(* ... *), CaseSensitivityChange=CaseSensitivityChange.ORIGINAL>
